/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RequireAuthRouteImport } from './routes/_requireAuth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RequireAuthIndexRouteImport } from './routes/_requireAuth/index'
import { Route as RequireAuthUriRouteImport } from './routes/_requireAuth/$uri'
import { Route as RequireAuthOrgsRouteImport } from './routes/_requireAuth/orgs'
import { Route as SessionCallbackRouteImport } from './routes/session.callback'
import { Route as SessionOrgCallbackRouteImport } from './routes/session.org-callback'
import { Route as WebhookSapRouteImport } from './routes/webhook.sap'
import { Route as WsDocIdRouteImport } from './routes/ws.$docId'

const RequireAuthRoute = RequireAuthRouteImport.update({
  id: '/_requireAuth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RequireAuthIndexRoute = RequireAuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RequireAuthRoute,
} as any)
const RequireAuthUriRoute = RequireAuthUriRouteImport.update({
  id: '/$uri',
  path: '/$uri',
  getParentRoute: () => RequireAuthRoute,
} as any)
const RequireAuthOrgsRoute = RequireAuthOrgsRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => RequireAuthRoute,
} as any)
const SessionCallbackRoute = SessionCallbackRouteImport.update({
  id: '/session/callback',
  path: '/session/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionOrgCallbackRoute = SessionOrgCallbackRouteImport.update({
  id: '/session/org-callback',
  path: '/session/org-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhookSapRoute = WebhookSapRouteImport.update({
  id: '/webhook/sap',
  path: '/webhook/sap',
  getParentRoute: () => rootRouteImport,
} as any)
const WsDocIdRoute = WsDocIdRouteImport.update({
  id: '/ws/$docId',
  path: '/ws/$docId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof RequireAuthIndexRoute
  '/login': typeof LoginRoute
  '/$uri': typeof RequireAuthUriRoute
  '/orgs': typeof RequireAuthOrgsRoute
  '/session/callback': typeof SessionCallbackRoute
  '/session/org-callback': typeof SessionOrgCallbackRoute
  '/webhook/sap': typeof WebhookSapRoute
  '/ws/$docId': typeof WsDocIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/$uri': typeof RequireAuthUriRoute
  '/orgs': typeof RequireAuthOrgsRoute
  '/session/callback': typeof SessionCallbackRoute
  '/session/org-callback': typeof SessionOrgCallbackRoute
  '/webhook/sap': typeof WebhookSapRoute
  '/ws/$docId': typeof WsDocIdRoute
  '/': typeof RequireAuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_requireAuth': typeof RequireAuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_requireAuth/$uri': typeof RequireAuthUriRoute
  '/_requireAuth/orgs': typeof RequireAuthOrgsRoute
  '/session/callback': typeof SessionCallbackRoute
  '/session/org-callback': typeof SessionOrgCallbackRoute
  '/webhook/sap': typeof WebhookSapRoute
  '/ws/$docId': typeof WsDocIdRoute
  '/_requireAuth/': typeof RequireAuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$uri'
    | '/orgs'
    | '/session/callback'
    | '/session/org-callback'
    | '/webhook/sap'
    | '/ws/$docId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/$uri'
    | '/orgs'
    | '/session/callback'
    | '/session/org-callback'
    | '/webhook/sap'
    | '/ws/$docId'
    | '/'
  id:
    | '__root__'
    | '/_requireAuth'
    | '/login'
    | '/_requireAuth/$uri'
    | '/_requireAuth/orgs'
    | '/session/callback'
    | '/session/org-callback'
    | '/webhook/sap'
    | '/ws/$docId'
    | '/_requireAuth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RequireAuthRoute: typeof RequireAuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  SessionCallbackRoute: typeof SessionCallbackRoute
  SessionOrgCallbackRoute: typeof SessionOrgCallbackRoute
  WebhookSapRoute: typeof WebhookSapRoute
  WsDocIdRoute: typeof WsDocIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_requireAuth': {
      id: '/_requireAuth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof RequireAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_requireAuth/': {
      id: '/_requireAuth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RequireAuthIndexRouteImport
      parentRoute: typeof RequireAuthRoute
    }
    '/_requireAuth/$uri': {
      id: '/_requireAuth/$uri'
      path: '/$uri'
      fullPath: '/$uri'
      preLoaderRoute: typeof RequireAuthUriRouteImport
      parentRoute: typeof RequireAuthRoute
    }
    '/_requireAuth/orgs': {
      id: '/_requireAuth/orgs'
      path: '/orgs'
      fullPath: '/orgs'
      preLoaderRoute: typeof RequireAuthOrgsRouteImport
      parentRoute: typeof RequireAuthRoute
    }
    '/session/callback': {
      id: '/session/callback'
      path: '/session/callback'
      fullPath: '/session/callback'
      preLoaderRoute: typeof SessionCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/org-callback': {
      id: '/session/org-callback'
      path: '/session/org-callback'
      fullPath: '/session/org-callback'
      preLoaderRoute: typeof SessionOrgCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhook/sap': {
      id: '/webhook/sap'
      path: '/webhook/sap'
      fullPath: '/webhook/sap'
      preLoaderRoute: typeof WebhookSapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ws/$docId': {
      id: '/ws/$docId'
      path: '/ws/$docId'
      fullPath: '/ws/$docId'
      preLoaderRoute: typeof WsDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RequireAuthRouteChildren {
  RequireAuthUriRoute: typeof RequireAuthUriRoute
  RequireAuthOrgsRoute: typeof RequireAuthOrgsRoute
  RequireAuthIndexRoute: typeof RequireAuthIndexRoute
}

const RequireAuthRouteChildren: RequireAuthRouteChildren = {
  RequireAuthUriRoute: RequireAuthUriRoute,
  RequireAuthOrgsRoute: RequireAuthOrgsRoute,
  RequireAuthIndexRoute: RequireAuthIndexRoute,
}

const RequireAuthRouteWithChildren = RequireAuthRoute._addFileChildren(
  RequireAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  RequireAuthRoute: RequireAuthRouteWithChildren,
  LoginRoute: LoginRoute,
  SessionCallbackRoute: SessionCallbackRoute,
  SessionOrgCallbackRoute: SessionOrgCallbackRoute,
  WebhookSapRoute: WebhookSapRoute,
  WsDocIdRoute: WsDocIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
