/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RequireAuthIndexRouteImport } from './routes/_requireAuth/index'

const RequireAuthIndexRoute = RequireAuthIndexRouteImport.update({
  id: '/_requireAuth/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof RequireAuthIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof RequireAuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_requireAuth/': typeof RequireAuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/_requireAuth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RequireAuthIndexRoute: typeof RequireAuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_requireAuth/': {
      id: '/_requireAuth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RequireAuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  RequireAuthIndexRoute: RequireAuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
