-- Baseline of the tables GORM's AutoMigrate used to create at startup,
-- generated by Atlas and then edited to use IF NOT EXISTS so it is a no-op on
-- databases AutoMigrate already created. Later migrations are generated
-- against this state, not against any live database.
-- +goose Up
-- create "clique_members" table
CREATE TABLE IF NOT EXISTS `clique_members` (
  `owner` text NULL,
  `key` text NULL,
  `member` text NULL,
  `created_at` datetime NULL,
  PRIMARY KEY (`owner`, `key`, `member`)
);
-- create "domain_mappings" table
CREATE TABLE IF NOT EXISTS `domain_mappings` (
  `domain` text NULL,
  `org_did` text NOT NULL,
  `login_method` text NOT NULL,
  PRIMARY KEY (`domain`)
);
-- create "member_emails" table
CREATE TABLE IF NOT EXISTS `member_emails` (
  `email` text NULL,
  `org_did` text NOT NULL,
  `did` text NOT NULL,
  PRIMARY KEY (`email`)
);
-- create index "idx_member_emails_d_id" to table: "member_emails"
CREATE UNIQUE INDEX IF NOT EXISTS `idx_member_emails_d_id` ON `member_emails` (`did`);
-- create "idents" table
CREATE TABLE IF NOT EXISTS `idents` (
  `handle` text NULL,
  `opaque_id` text NULL,
  `signing_public_key` text NULL,
  `signing_private_key_enc` text NULL,
  `created_at` datetime NULL,
  `updated_at` datetime NULL,
  PRIMARY KEY (`handle`)
);
-- create index "idx_idents_opaque_id" to table: "idents"
CREATE UNIQUE INDEX IF NOT EXISTS `idx_idents_opaque_id` ON `idents` (`opaque_id`);
-- create "instance_settings" table
CREATE TABLE IF NOT EXISTS `instance_settings` (
  `id` integer NULL PRIMARY KEY AUTOINCREMENT,
  `instance_name` text NULL,
  `org_creation_policy` text NULL,
  `signing_secret` text NULL,
  `created_at` datetime NULL
);
-- create "instance_invites" table
CREATE TABLE IF NOT EXISTS `instance_invites` (
  `token` text NULL,
  `created_at` datetime NULL,
  `used_at` datetime NULL,
  PRIMARY KEY (`token`)
);
-- create "password_entries" table
CREATE TABLE IF NOT EXISTS `password_entries` (
  `did` text NULL,
  `password` text NULL,
  PRIMARY KEY (`did`)
);
-- create "google_credentials_models" table
CREATE TABLE IF NOT EXISTS `google_credentials_models` (
  `email` text NULL,
  `access_token` text NULL,
  `refresh_token` text NULL,
  `expiry` datetime NULL,
  `id_token` text NULL,
  `created_at` datetime NULL,
  `updated_at` datetime NULL,
  PRIMARY KEY (`email`)
);
-- create "registrations" table
CREATE TABLE IF NOT EXISTS `registrations` (
  `space` text NULL,
  `repo` text NULL,
  `endpoint` text NULL,
  `expires_at` datetime NULL,
  `created_at` datetime NULL,
  `updated_at` datetime NULL,
  PRIMARY KEY (`space`, `repo`, `endpoint`)
);
-- create "o_auth_requests" table
CREATE TABLE IF NOT EXISTS `o_auth_requests` (
  `key` text NULL,
  `client_id` text NULL,
  `subject` text NULL,
  `scopes` text NULL,
  `code_challenge` text NULL,
  `code_challenge_method` text NULL,
  `redirect_uri` text NULL,
  `state` text NULL,
  `response_type` text NULL,
  `response_mode` text NULL,
  `expires_at` datetime NULL,
  PRIMARY KEY (`key`)
);
-- create index "idx_o_auth_requests_expires_at" to table: "o_auth_requests"
CREATE INDEX IF NOT EXISTS `idx_o_auth_requests_expires_at` ON `o_auth_requests` (`expires_at`);
-- create "o_auth_sessions" table
CREATE TABLE IF NOT EXISTS `o_auth_sessions` (
  `signature` text NULL,
  `client_id` text NULL,
  `subject` text NULL,
  `scopes` text NULL,
  `expires_at` datetime NULL,
  PRIMARY KEY (`signature`)
);
-- create "connected_apps" table
CREATE TABLE IF NOT EXISTS `connected_apps` (
  `subject` text NULL,
  `client_id` text NULL,
  `scopes` text NULL,
  `created_at` datetime NULL,
  `updated_at` datetime NULL
);
-- create "registered_clients" table
CREATE TABLE IF NOT EXISTS `registered_clients` (
  `client_id` text NULL,
  `client_name` text NULL,
  `redirect_uris` blob NULL,
  `grant_types` blob NULL,
  `created_at` datetime NULL,
  PRIMARY KEY (`client_id`)
);
-- create "invite_rows" table
CREATE TABLE IF NOT EXISTS `invite_rows` (
  `id` text NULL,
  `org_id` text NOT NULL,
  `invitee` text NOT NULL,
  `roles` text NOT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
);
-- create index "idx_invite_org_invitee" to table: "invite_rows"
CREATE UNIQUE INDEX IF NOT EXISTS `idx_invite_org_invitee` ON `invite_rows` (`org_id`, `invitee`);
-- create "organizations" table
CREATE TABLE IF NOT EXISTS `organizations` (
  `id` text NULL,
  `name` text NULL,
  `login_method` text NULL,
  `signing_secret` text NULL,
  `created_at` datetime NULL,
  `handle_subdomain` text NULL,
  `contact_email` text NULL,
  PRIMARY KEY (`id`)
);
-- create index "organizations_handle_subdomain" to table: "organizations"
CREATE UNIQUE INDEX IF NOT EXISTS `organizations_handle_subdomain` ON `organizations` (`handle_subdomain`);
-- create "members" table
CREATE TABLE IF NOT EXISTS `members` (
  `org_id` text NULL,
  `did` text NULL,
  `role` text NOT NULL,
  `login_id` text NOT NULL,
  `created_at` datetime NULL,
  PRIMARY KEY (`org_id`, `did`),
  CONSTRAINT `fk_members_organization` FOREIGN KEY (`org_id`) REFERENCES `organizations` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- create index "idx_members_login_id" to table: "members"
CREATE INDEX IF NOT EXISTS `idx_members_login_id` ON `members` (`login_id`);
-- create "spent_tokens" table
CREATE TABLE IF NOT EXISTS `spent_tokens` (
  `org_id` text NULL,
  `jti` text NULL,
  `consumed_at` datetime NOT NULL,
  PRIMARY KEY (`org_id`, `jti`)
);
-- create "pds_credentials_models" table
CREATE TABLE IF NOT EXISTS `pds_credentials_models` (
  `did` text NULL,
  `access_token` text NULL,
  `refresh_token` text NULL,
  `token_type` text NULL,
  `scope` text NULL,
  `dpop_key` blob NULL,
  `created_at` datetime NULL,
  `updated_at` datetime NULL,
  PRIMARY KEY (`did`)
);
-- create "permissions" table
CREATE TABLE IF NOT EXISTS `permissions` (
  `grantee` text NULL,
  `owner` text NULL,
  `collection` text NULL,
  `rkey` text NULL,
  `created_at` datetime NULL,
  `updated_at` datetime NULL,
  PRIMARY KEY (`grantee`, `owner`, `collection`, `rkey`)
);
-- create "records" table
CREATE TABLE IF NOT EXISTS `records` (
  `did` text NULL,
  `collection` text NULL,
  `rkey` text NULL,
  `value` blob NULL,
  `created_at` datetime NULL,
  `updated_at` datetime NULL,
  PRIMARY KEY (`did`, `collection`, `rkey`)
);
-- create "blobs" table
CREATE TABLE IF NOT EXISTS `blobs` (
  `id` integer NULL PRIMARY KEY AUTOINCREMENT,
  `created_at` datetime NULL,
  `updated_at` datetime NULL,
  `deleted_at` datetime NULL,
  `did` text NULL,
  `cid` text NULL,
  `mime_type` text NULL,
  `blob` blob NULL
);
-- create index "idx_blobs_deleted_at" to table: "blobs"
CREATE INDEX IF NOT EXISTS `idx_blobs_deleted_at` ON `blobs` (`deleted_at`);
-- create "links" table
CREATE TABLE IF NOT EXISTS `links` (
  `cid` text NULL,
  `did` text NULL,
  `ref` text NULL,
  PRIMARY KEY (`cid`, `did`, `ref`)
);
-- create "spaces" table
CREATE TABLE IF NOT EXISTS `spaces` (
  `owner` text NULL,
  `type` text NULL,
  `skey` text NULL,
  `created_at` datetime NULL,
  PRIMARY KEY (`owner`, `type`, `skey`)
);
-- create "space_records" table
CREATE TABLE IF NOT EXISTS `space_records` (
  `space` text NULL,
  `repo` text NULL,
  `collection` text NULL,
  `rkey` text NULL,
  `value` blob NULL,
  `rev` text NULL,
  `cid` text NULL,
  `prev_cid` text NULL,
  `created_at` datetime NULL,
  `updated_at` datetime NULL,
  `deleted_at` datetime NULL,
  PRIMARY KEY (`space`, `repo`, `collection`, `rkey`)
);
-- create index "idx_space_records_rev" to table: "space_records"
CREATE UNIQUE INDEX IF NOT EXISTS `idx_space_records_rev` ON `space_records` (`rev`);
-- create "space_repos" table
CREATE TABLE IF NOT EXISTS `space_repos` (
  `space` text NULL,
  `repo` text NULL,
  `hash` blob NULL,
  `rev` text NULL,
  `remote` numeric NULL,
  `updated_at` datetime NULL,
  `deleted_at` datetime NULL,
  PRIMARY KEY (`space`, `repo`)
);

-- +goose Down
-- The baseline adopts tables that predate migrations, so rolling it back must
-- not drop them.
SELECT 1;
