packages:
  - frontend
  - camera
  - typescript/internal
  - typescript/apps/*
  - typescript/api

catalog:
  '@tanstack/devtools-vite': ^0.3.11
  '@tanstack/react-devtools': ^0.7.0
  '@tanstack/react-query': ^5.90.12
  '@tanstack/react-router': ^1.132.0
  '@tanstack/react-router-devtools': ^1.132.0
  '@tanstack/router-plugin': ^1.132.0
  '@testing-library/dom': ^10.4.0
  '@testing-library/react': ^16.2.0
  '@types/node': ^22.10.2
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.0
  '@vitejs/plugin-react': 5.1.2
  idb: ^8.0.0
  jsdom: ^27.0.0
  react: ^19.2.3
  react-dom: ^19.2.0
  react-hook-form: 7.65.0
  typescript: ^5.7.2
  vite: 7.1.12
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.0.5
