import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import apiSidebar from "./docs/api/sidebar";

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: "doc",
      id: "habitat",
    },
    {
      type: "category",
      label: "Getting started",
      items: [{ type: "autogenerated", dirName: "guides" }],
    },
    {
      type: "category",
      label: "Building on Habitat",
      items: [{ type: "autogenerated", dirName: "building" }],
    },
    {
      type: "category",
      label: "Architecture",
      items: [{ type: "autogenerated", dirName: "arch" }],
    },
    {
      type: "category",
      label: "HTTP Reference",
      items: apiSidebar.filter(
        (item: { label: string; }) =>
          !("label" in item) ||
          (item.label !== "network.habitat.clique" &&
            item.label !== "network.habitat.repo" &&
            item.label !== "network.habitat.permissions" &&
            item.label !== "network.habitat.internal" &&
            item.label !== "network.habitat.listConnectedApps")
      ),
    },
  ],
};

export default sidebars;
