import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import apiSidebar from "./docs/api/sidebar";

// Lexicon groups kept out of the public HTTP reference.
const hiddenGroups = new Set([
  "network.habitat.clique",
  "network.habitat.repo",
  "network.habitat.permissions",
  "network.habitat.internal",
  "network.habitat.listConnectedApps",
  "network.habitat.docs",
]);

// Individual endpoints kept out of the public HTTP reference: deprecated
// aliases of the network.habitat.simplespace.* methods.
const hiddenEndpoints = new Set([
  "network.habitat.space.createSpace",
  "network.habitat.space.addMember",
  "network.habitat.space.removeMember",
  "network.habitat.space.deleteSpace",
]);

type ApiSidebarItem = { label?: string; items?: ApiSidebarItem[] };

const sidebars: SidebarsConfig = {
  ods: [
    {
      type: "doc",
      id: "habitat",
    },
    {
      type: "category",
      label: "Getting started",
      items: [{ type: "autogenerated", dirName: "guides" }],
    },
    {
      type: "category",
      label: "Building on Habitat",
      items: [{ type: "autogenerated", dirName: "building" }],
    },
    {
      type: "category",
      label: "Architecture",
      items: [{ type: "autogenerated", dirName: "arch" }],
    },
  ],
  spaceProxy: [{ type: "autogenerated", dirName: "space-proxy" }],
  httpReference: (apiSidebar as ApiSidebarItem[])
    .filter((item) => item.label === undefined || !hiddenGroups.has(item.label))
    .map((item) =>
      item.items === undefined
        ? item
        : {
            ...item,
            items: item.items.filter(
              (endpoint) =>
                endpoint.label === undefined ||
                !hiddenEndpoints.has(endpoint.label),
            ),
          },
    ) as SidebarsConfig[string],
};

export default sidebars;
