import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import apiSidebar from "./docs/api/sidebar";

const sidebars: SidebarsConfig = {
  ods: [
    {
      type: "doc",
      id: "habitat",
    },
    {
      type: "category",
      label: "Getting started",
      items: [{ type: "autogenerated", dirName: "guides" }],
    },
    {
      type: "category",
      label: "Building on Habitat",
      items: [{ type: "autogenerated", dirName: "building" }],
    },
    {
      type: "category",
      label: "Architecture",
      items: [{ type: "autogenerated", dirName: "arch" }],
    },
  ],
  spaceProxy: [{ type: "autogenerated", dirName: "space-proxy" }],
  httpReference: apiSidebar.filter(
    (item: { label: string }) =>
      !("label" in item) ||
      (item.label !== "network.habitat.clique" &&
        item.label !== "network.habitat.repo" &&
        item.label !== "network.habitat.permissions" &&
        item.label !== "network.habitat.internal" &&
        item.label !== "network.habitat.listConnectedApps" &&
        item.label !== "network.habitat.docs"),
  ),
};

export default sidebars;
