-- Baseline of the tables GORM's AutoMigrate used to create at startup,
-- generated by Atlas and then edited to use IF NOT EXISTS so it is a no-op on
-- databases AutoMigrate already created. Later migrations are generated
-- against this state, not against any live database.
-- +goose Up
-- create "o_auth_requests" table
CREATE TABLE IF NOT EXISTS "o_auth_requests" (
  "key" text NOT NULL,
  "client_id" character varying(1024) NULL,
  "subject" character varying(255) NULL,
  "scopes" character varying(512) NULL,
  "code_challenge" character varying(255) NULL,
  "code_challenge_method" character varying(32) NULL,
  "redirect_uri" character varying(1024) NULL,
  "state" character varying(1024) NULL,
  "response_type" character varying(64) NULL,
  "response_mode" character varying(32) NULL,
  "expires_at" timestamptz NULL,
  PRIMARY KEY ("key")
);
-- create index "idx_o_auth_requests_expires_at" to table: "o_auth_requests"
CREATE INDEX IF NOT EXISTS "idx_o_auth_requests_expires_at" ON "o_auth_requests" ("expires_at");
-- create "space_records" table
CREATE TABLE IF NOT EXISTS "space_records" (
  "space" text NOT NULL,
  "repo" text NOT NULL,
  "collection" text NOT NULL,
  "rkey" text NOT NULL,
  "value" bytea NULL,
  "rev" text NULL,
  "cid" text NULL,
  "prev_cid" text NULL,
  "created_at" timestamptz NULL,
  "updated_at" timestamptz NULL,
  "deleted_at" timestamptz NULL,
  PRIMARY KEY ("space", "repo", "collection", "rkey")
);
-- create index "idx_space_records_rev" to table: "space_records"
CREATE UNIQUE INDEX IF NOT EXISTS "idx_space_records_rev" ON "space_records" ("rev");
-- create "connected_apps" table
CREATE TABLE IF NOT EXISTS "connected_apps" (
  "subject" text NULL,
  "client_id" text NULL,
  "scopes" text NULL,
  "created_at" timestamptz NULL,
  "updated_at" timestamptz NULL
);
-- create "domain_mappings" table
CREATE TABLE IF NOT EXISTS "domain_mappings" (
  "domain" text NOT NULL,
  "org_did" text NOT NULL,
  "login_method" text NOT NULL,
  PRIMARY KEY ("domain")
);
-- create "google_credentials_models" table
CREATE TABLE IF NOT EXISTS "google_credentials_models" (
  "email" text NOT NULL,
  "access_token" text NULL,
  "refresh_token" text NULL,
  "expiry" timestamptz NULL,
  "id_token" text NULL,
  "created_at" timestamptz NULL,
  "updated_at" timestamptz NULL,
  PRIMARY KEY ("email")
);
-- create "idents" table
CREATE TABLE IF NOT EXISTS "idents" (
  "handle" text NOT NULL,
  "opaque_id" text NULL,
  "signing_public_key" text NULL,
  "signing_private_key_enc" text NULL,
  "created_at" timestamptz NULL,
  "updated_at" timestamptz NULL,
  PRIMARY KEY ("handle")
);
-- create index "idx_idents_opaque_id" to table: "idents"
CREATE UNIQUE INDEX IF NOT EXISTS "idx_idents_opaque_id" ON "idents" ("opaque_id");
-- create "instance_invites" table
CREATE TABLE IF NOT EXISTS "instance_invites" (
  "token" text NOT NULL,
  "created_at" timestamptz NULL,
  "used_at" timestamptz NULL,
  PRIMARY KEY ("token")
);
-- create "instance_settings" table
CREATE TABLE IF NOT EXISTS "instance_settings" (
  "id" bigserial NOT NULL,
  "instance_name" text NULL,
  "org_creation_policy" text NULL,
  "signing_secret" text NULL,
  "created_at" timestamptz NULL,
  PRIMARY KEY ("id")
);
-- create "invite_rows" table
CREATE TABLE IF NOT EXISTS "invite_rows" (
  "id" text NOT NULL,
  "org_id" text NOT NULL,
  "invitee" text NOT NULL,
  "roles" text NOT NULL,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- create index "idx_invite_org_invitee" to table: "invite_rows"
CREATE UNIQUE INDEX IF NOT EXISTS "idx_invite_org_invitee" ON "invite_rows" ("org_id", "invitee");
-- create "links" table
CREATE TABLE IF NOT EXISTS "links" (
  "cid" text NOT NULL,
  "did" text NOT NULL,
  "ref" text NOT NULL,
  PRIMARY KEY ("cid", "did", "ref")
);
-- create "member_emails" table
CREATE TABLE IF NOT EXISTS "member_emails" (
  "email" text NOT NULL,
  "org_did" text NOT NULL,
  "did" text NOT NULL,
  PRIMARY KEY ("email")
);
-- create index "idx_member_emails_d_id" to table: "member_emails"
CREATE UNIQUE INDEX IF NOT EXISTS "idx_member_emails_d_id" ON "member_emails" ("did");
-- create "spent_tokens" table
CREATE TABLE IF NOT EXISTS "spent_tokens" (
  "org_id" text NOT NULL,
  "jti" text NOT NULL,
  "consumed_at" timestamptz NOT NULL,
  PRIMARY KEY ("org_id", "jti")
);
-- create "clique_members" table
CREATE TABLE IF NOT EXISTS "clique_members" (
  "owner" text NOT NULL,
  "key" text NOT NULL,
  "member" text NOT NULL,
  "created_at" timestamptz NULL,
  PRIMARY KEY ("owner", "key", "member")
);
-- create "organizations" table
CREATE TABLE IF NOT EXISTS "organizations" (
  "id" text NOT NULL,
  "name" text NULL,
  "login_method" text NULL,
  "signing_secret" text NULL,
  "created_at" timestamptz NULL,
  "handle_subdomain" text NULL,
  "contact_email" text NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "uni_organizations_handle_subdomain" UNIQUE ("handle_subdomain")
);
-- create "blobs" table
CREATE TABLE IF NOT EXISTS "blobs" (
  "id" bigserial NOT NULL,
  "created_at" timestamptz NULL,
  "updated_at" timestamptz NULL,
  "deleted_at" timestamptz NULL,
  "did" text NULL,
  "cid" text NULL,
  "mime_type" text NULL,
  "blob" bytea NULL,
  PRIMARY KEY ("id")
);
-- create index "idx_blobs_deleted_at" to table: "blobs"
CREATE INDEX IF NOT EXISTS "idx_blobs_deleted_at" ON "blobs" ("deleted_at");
-- create "password_entries" table
CREATE TABLE IF NOT EXISTS "password_entries" (
  "did" text NOT NULL,
  "password" text NULL,
  PRIMARY KEY ("did")
);
-- create "pds_credentials_models" table
CREATE TABLE IF NOT EXISTS "pds_credentials_models" (
  "did" text NOT NULL,
  "access_token" text NULL,
  "refresh_token" text NULL,
  "token_type" text NULL,
  "scope" text NULL,
  "dpop_key" bytea NULL,
  "created_at" timestamptz NULL,
  "updated_at" timestamptz NULL,
  PRIMARY KEY ("did")
);
-- create "permissions" table
CREATE TABLE IF NOT EXISTS "permissions" (
  "grantee" text NOT NULL,
  "owner" text NOT NULL,
  "collection" text NOT NULL,
  "rkey" text NOT NULL,
  "created_at" timestamptz NULL,
  "updated_at" timestamptz NULL,
  PRIMARY KEY ("grantee", "owner", "collection", "rkey")
);
-- create "records" table
CREATE TABLE IF NOT EXISTS "records" (
  "did" text NOT NULL,
  "collection" text NOT NULL,
  "rkey" text NOT NULL,
  "value" bytea NULL,
  "created_at" timestamptz NULL,
  "updated_at" timestamptz NULL,
  PRIMARY KEY ("did", "collection", "rkey")
);
-- create "registered_clients" table
CREATE TABLE IF NOT EXISTS "registered_clients" (
  "client_id" text NOT NULL,
  "client_name" text NULL,
  "redirect_uris" bytea NULL,
  "grant_types" bytea NULL,
  "created_at" timestamptz NULL,
  PRIMARY KEY ("client_id")
);
-- create "registrations" table
CREATE TABLE IF NOT EXISTS "registrations" (
  "space" text NOT NULL,
  "repo" text NOT NULL,
  "endpoint" text NOT NULL,
  "expires_at" timestamptz NULL,
  "created_at" timestamptz NULL,
  "updated_at" timestamptz NULL,
  PRIMARY KEY ("space", "repo", "endpoint")
);
-- create "o_auth_sessions" table
CREATE TABLE IF NOT EXISTS "o_auth_sessions" (
  "signature" text NOT NULL,
  "client_id" text NULL,
  "subject" text NULL,
  "scopes" text NULL,
  "expires_at" timestamptz NULL,
  PRIMARY KEY ("signature")
);
-- create "space_repos" table
CREATE TABLE IF NOT EXISTS "space_repos" (
  "space" text NOT NULL,
  "repo" text NOT NULL,
  "hash" bytea NULL,
  "rev" text NULL,
  "remote" boolean NULL,
  "updated_at" timestamptz NULL,
  "deleted_at" timestamptz NULL,
  PRIMARY KEY ("space", "repo")
);
-- create "spaces" table
CREATE TABLE IF NOT EXISTS "spaces" (
  "owner" text NOT NULL,
  "type" text NOT NULL,
  "skey" text NOT NULL,
  "created_at" timestamptz NULL,
  PRIMARY KEY ("owner", "type", "skey")
);
-- create "members" table
CREATE TABLE IF NOT EXISTS "members" (
  "org_id" text NOT NULL,
  "did" text NOT NULL,
  "role" text NOT NULL,
  "login_id" text NOT NULL,
  "created_at" timestamptz NULL,
  PRIMARY KEY ("org_id", "did"),
  CONSTRAINT "fk_members_organization" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- create index "idx_members_login_id" to table: "members"
CREATE INDEX IF NOT EXISTS "idx_members_login_id" ON "members" ("login_id");

-- +goose Down
-- The baseline adopts tables that predate migrations, so rolling it back must
-- not drop them.
SELECT 1;
