const test = require("node:test");
const assert = require("node:assert");
const fs = require("node:fs");
const path = require("node:path");

const DOCS_DIR = path.join(__dirname, "..", "docs");

function docFiles(dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    // docs/api is generated by `docusaurus gen-api-docs` on every build.
    if (entry.isDirectory()) {
      if (entry.name === "api") continue;
      out.push(...docFiles(full));
    } else if (entry.name.endsWith(".mdx") || entry.name.endsWith(".md")) {
      out.push(full);
    }
  }
  return out;
}

test("no page declares a slug ending in .mdx", () => {
  const offenders = [];
  for (const file of docFiles(DOCS_DIR)) {
    const slug = /^slug:\s*(.+)$/m.exec(fs.readFileSync(file, "utf8"));
    if (slug && slug[1].trim().endsWith(".mdx")) {
      offenders.push(path.relative(DOCS_DIR, file));
    }
  }
  assert.deepEqual(
    offenders,
    [],
    `frontmatter slugs must not end in .mdx: ${offenders.join(", ")}`,
  );
});

test("every page declares a slug", () => {
  for (const file of docFiles(DOCS_DIR)) {
    const raw = fs.readFileSync(file, "utf8");
    assert.match(
      raw,
      /^slug:\s*\S+$/m,
      `missing slug in ${path.relative(DOCS_DIR, file)}`,
    );
  }
});
