import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { collections } from "../collections.config.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

function lexiconTypeToValidator(prop) {
  switch (prop.type) {
    case "string":
      return "v.string()";
    case "integer":
      return "v.number()";
    case "boolean":
      return "v.boolean()";
    case "bytes":
      return "v.bytes()";
    case "cid-link":
      return "v.string()";
    case "array":
      return `v.array(${lexiconTypeToValidator(prop.items)})`;
    case "object": {
      const required = new Set(prop.required ?? []);
      const fields = Object.entries(prop.properties ?? {})
        .map(([name, sub]) => {
          const validator = lexiconTypeToValidator(sub);
          return `    ${name}: ${required.has(name) ? validator : `v.optional(${validator})`},`;
        })
        .join("\n");
      return `v.object({\n${fields}\n  })`;
    }
    // $ref, union, blob, and anything else: not resolved for this prototype.
    default:
      return "v.any()";
  }
}

function generateTable(collection) {
  const lexiconPath = path.join(__dirname, "..", collection.lexiconPath);
  const lexicon = JSON.parse(readFileSync(lexiconPath, "utf8"));
  const record = lexicon.defs.main.record;
  const required = new Set(record.required ?? []);

  const fields = Object.entries(record.properties ?? {})
    .map(([name, prop]) => {
      const validator = lexiconTypeToValidator(prop);
      return `    ${name}: ${required.has(name) ? validator : `v.optional(${validator})`},`;
    })
    .join("\n");

  return `  ${collection.table}: defineTable({
    uri: v.string(),
    did: v.string(),
    cid: v.optional(v.string()),
    rev: v.optional(v.string()),
    syncStatus: v.union(v.literal("pending"), v.literal("confirmed"), v.literal("failed")),
${fields}
  }).index("by_uri", ["uri"]),`;
}

const tables = collections.map(generateTable).join("\n");

const output = `// GENERATED by scripts/gen-schema.mjs from collections.config.mjs — do not hand-edit.
// Regenerate with: node scripts/gen-schema.mjs
import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
${tables}
});
`;

writeFileSync(path.join(__dirname, "..", "convex", "schema.ts"), output);
console.log("wrote convex/schema.ts");
