// GENERATED by scripts/gen-schema.mjs from collections.config.mjs — do not hand-edit.
// Regenerate with: node scripts/gen-schema.mjs
import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  userRelations: defineTable({
    uri: v.string(),
    did: v.string(),
    cid: v.optional(v.string()),
    rev: v.optional(v.string()),
    syncStatus: v.union(v.literal("pending"), v.literal("confirmed"), v.literal("failed")),
    subject: v.string(),
    relation: v.string(),
    createdAt: v.optional(v.string()),
  }).index("by_uri", ["uri"]),
});
