package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatAdminGetSettingsOutput represents the output for network.habitat.admin.getSettings
type NetworkHabitatAdminGetSettingsOutput struct {
	InstanceName      string `json:"instanceName"`
	OrgCreationPolicy string `json:"orgCreationPolicy"`
}
