package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatAdminUpdateSettingsInput represents the input for network.habitat.admin.updateSettings
type NetworkHabitatAdminUpdateSettingsInput struct {
	InstanceName      string `json:"instanceName,omitempty"`
	OrgCreationPolicy string `json:"orgCreationPolicy,omitempty"`
}

// NetworkHabitatAdminUpdateSettingsOutput represents the output for network.habitat.admin.updateSettings
type NetworkHabitatAdminUpdateSettingsOutput struct {
	InstanceName      string `json:"instanceName"`
	OrgCreationPolicy string `json:"orgCreationPolicy"`
}
