package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatAdminIssueInviteOutput represents the output for network.habitat.admin.issueInvite
type NetworkHabitatAdminIssueInviteOutput struct {
	Token string `json:"token"`
}
