package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatArenaGetItemsOutput represents the output for network.habitat.arena.getItems
type NetworkHabitatArenaGetItemsOutput struct {
	Items []string `json:"items,omitempty"`
}
