package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatArenaGetItemsParams represents the input parameters for network.habitat.arena.getItems
type NetworkHabitatArenaGetItemsParams struct {
	ArenaID string `json:"arenaID"`
}

// NetworkHabitatArenaGetItemsOutput represents the output for network.habitat.arena.getItems
type NetworkHabitatArenaGetItemsOutput struct {
	AllowToken string   `json:"allowToken"`
	Items      []string `json:"items"`
}
