package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatArenaSendItemInput represents the input for network.habitat.arena.sendItem
type NetworkHabitatArenaSendItemInput struct {
	ArenaID string `json:"arenaID"`
	Item    string `json:"item"`
}

// NetworkHabitatArenaSendItemOutput represents the output for network.habitat.arena.sendItem
type NetworkHabitatArenaSendItemOutput struct {
	Message string `json:"message,omitempty"`
	Status  string `json:"status,omitempty"`
}
