package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatArenaAddItemInput represents the input for network.habitat.arena.addItem
type NetworkHabitatArenaAddItemInput struct {
	ArenaID string `json:"arenaID"`
	Item    string `json:"item"`
}
