package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatAuthzenEvaluateAction represents a action object
type NetworkHabitatAuthzenEvaluateAction struct {
	Name       string      `json:"name"`
	Properties interface{} `json:"properties,omitempty"`
}

// NetworkHabitatAuthzenEvaluateEntity represents a entity object
type NetworkHabitatAuthzenEvaluateEntity struct {
	Id         string      `json:"id"`
	Properties interface{} `json:"properties,omitempty"`
	Type       string      `json:"type"`
}

// NetworkHabitatAuthzenEvaluateInput represents the input for network.habitat.authzen.evaluate
type NetworkHabitatAuthzenEvaluateInput struct {
	Action   NetworkHabitatAuthzenEvaluateAction `json:"action"`
	Context  interface{}                         `json:"context,omitempty"`
	Resource NetworkHabitatAuthzenEvaluateEntity `json:"resource"`
	Subject  NetworkHabitatAuthzenEvaluateEntity `json:"subject"`
}

// NetworkHabitatAuthzenEvaluateOutput represents the output for network.habitat.authzen.evaluate
type NetworkHabitatAuthzenEvaluateOutput struct {
	Context  interface{} `json:"context,omitempty"`
	Decision bool        `json:"decision"`
}
