package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatAuthzenEvaluateAction represents a action object
type NetworkHabitatAuthzenEvaluateAction struct {
	Name       string                 `json:"name"`
	Properties map[string]interface{} `json:"properties,omitempty"`
}

// NetworkHabitatAuthzenEvaluateInput represents the input for network.habitat.authzen.evaluate
type NetworkHabitatAuthzenEvaluateInput struct {
	Action   NetworkHabitatAuthzenEvaluateAction   `json:"action"`
	Context  map[string]interface{}                `json:"context,omitempty"`
	Resource NetworkHabitatAuthzenEvaluateResource `json:"resource"`
	Subject  NetworkHabitatAuthzenEvaluateSubject  `json:"subject"`
}

// NetworkHabitatAuthzenEvaluateOutput represents the output for network.habitat.authzen.evaluate
type NetworkHabitatAuthzenEvaluateOutput struct {
	Context  map[string]interface{} `json:"context,omitempty"`
	Decision bool                   `json:"decision"`
}

// NetworkHabitatAuthzenEvaluateResource represents a resource object
type NetworkHabitatAuthzenEvaluateResource struct {
	Id         string                 `json:"id"`
	Properties map[string]interface{} `json:"properties,omitempty"`
	Type       string                 `json:"type"`
}

// NetworkHabitatAuthzenEvaluateSubject represents a subject object
type NetworkHabitatAuthzenEvaluateSubject struct {
	Id         string                 `json:"id"`
	Properties map[string]interface{} `json:"properties,omitempty"`
	Type       string                 `json:"type"`
}
