package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatCliqueCreateCliqueOutput represents the output for network.habitat.clique.createClique
type NetworkHabitatCliqueCreateCliqueOutput struct {
	Clique string `json:"clique"`
}
