package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatCliqueCreateCliqueInput represents the input for network.habitat.clique.createClique
type NetworkHabitatCliqueCreateCliqueInput struct {
	Members []string `json:"members,omitempty"`
}

// NetworkHabitatCliqueCreateCliqueOutput represents the output for network.habitat.clique.createClique
type NetworkHabitatCliqueCreateCliqueOutput struct {
	Clique string `json:"clique"`
}
