package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatCliqueAddItemInput represents the input for network.habitat.clique.addItem
type NetworkHabitatCliqueAddItemInput struct {
	CliqueID string `json:"cliqueID"`
	Item     string `json:"item"`
}
