package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatCliqueAddMembersInput represents the input for network.habitat.clique.addMembers
type NetworkHabitatCliqueAddMembersInput struct {
	Clique  NetworkHabitatGranteeClique `json:"clique"`
	Members []string                    `json:"members"`
}
