package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatCliqueGetMembersParams represents the input parameters for network.habitat.clique.getMembers
type NetworkHabitatCliqueGetMembersParams struct {
	Clique string `json:"clique"`
}

// NetworkHabitatCliqueGetMembersOutput represents the output for network.habitat.clique.getMembers
type NetworkHabitatCliqueGetMembersOutput struct {
	Members []string `json:"members"`
}
