package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatCliqueIsMemberParams represents the input parameters for network.habitat.clique.isMember
type NetworkHabitatCliqueIsMemberParams struct {
	Clique string `json:"clique"`
	Did    string `json:"did"`
}
