package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatCliqueGetItemsOutput represents the output for network.habitat.clique.getItems
type NetworkHabitatCliqueGetItemsOutput struct {
	Items []string `json:"items,omitempty"`
}
