package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatCliqueGetItemsParams represents the input parameters for network.habitat.clique.getItems
type NetworkHabitatCliqueGetItemsParams struct {
	CliqueID string `json:"cliqueID"`
}

// NetworkHabitatCliqueGetItemsOutput represents the output for network.habitat.clique.getItems
type NetworkHabitatCliqueGetItemsOutput struct {
	Items []string `json:"items,omitempty"`
}
