package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatCliqueMain represents a main object
type NetworkHabitatCliqueMain struct {
	LexiconTypeID string `json:"$type"`
}

// MarshalJSON sets $type to "network.habitat.clique#main" before encoding.
func (t NetworkHabitatCliqueMain) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.clique#main"
	type alias NetworkHabitatCliqueMain
	return json.Marshal(alias(t))
}
