package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatCliqueRemoveMembersInput represents the input for network.habitat.clique.removeMembers
type NetworkHabitatCliqueRemoveMembersInput struct {
	Clique  NetworkHabitatGranteeClique `json:"clique"`
	Members []string                    `json:"members"`
}
