package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatCollectionsListCollectionsParams represents the input parameters for network.habitat.collections.listCollections
type NetworkHabitatCollectionsListCollectionsParams struct {
}

// NetworkHabitatCollectionsListCollectionsOutput represents the output for network.habitat.collections.listCollections
type NetworkHabitatCollectionsListCollectionsOutput struct {
	Collections []NetworkHabitatCollectionsDefsCollectionView `json:"collections"`
}
