package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatCollectionsDefsCollectionView represents a collectionView object
type NetworkHabitatCollectionsDefsCollectionView struct {
	Collection  string `json:"collection"`
	RecordCount int64  `json:"recordCount"`
}

// NetworkHabitatCollectionsDefsRecordView represents a recordView object
type NetworkHabitatCollectionsDefsRecordView struct {
	Collection string   `json:"collection"`
	Repo       string   `json:"repo"`
	Rkey       string   `json:"rkey"`
	Spaces     []string `json:"spaces"`
	Uri        string   `json:"uri"`
}
