package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatCollectionsDefsCollectionView represents a collectionView object
type NetworkHabitatCollectionsDefsCollectionView struct {
	LexiconTypeID string `json:"$type"`
	Collection    string `json:"collection"`
	RecordCount   int64  `json:"recordCount"`
}

// MarshalJSON sets $type to "network.habitat.collections.defs#collectionView" before encoding.
func (t NetworkHabitatCollectionsDefsCollectionView) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.collections.defs#collectionView"
	type alias NetworkHabitatCollectionsDefsCollectionView
	return json.Marshal(alias(t))
}

// NetworkHabitatCollectionsDefsRecordView represents a recordView object
type NetworkHabitatCollectionsDefsRecordView struct {
	LexiconTypeID string `json:"$type"`
	Collection    string `json:"collection"`
	Repo          string `json:"repo"`
	Rkey          string `json:"rkey"`
	Space         string `json:"space"`
	Uri           string `json:"uri"`
}

// MarshalJSON sets $type to "network.habitat.collections.defs#recordView" before encoding.
func (t NetworkHabitatCollectionsDefsRecordView) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.collections.defs#recordView"
	type alias NetworkHabitatCollectionsDefsRecordView
	return json.Marshal(alias(t))
}
