package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatCollectionsListRecordsParams represents the input parameters for network.habitat.collections.listRecords
type NetworkHabitatCollectionsListRecordsParams struct {
	Collection string `json:"collection"`
}

// NetworkHabitatCollectionsListRecordsOutput represents the output for network.habitat.collections.listRecords
type NetworkHabitatCollectionsListRecordsOutput struct {
	Records []NetworkHabitatCollectionsDefsRecordView `json:"records"`
}
