package habitat

// Code generated by lexgen. DO NOT EDIT.

// ComAtprotoSpaceGetRepoParams represents the input parameters for com.atproto.space.getRepo
type ComAtprotoSpaceGetRepoParams struct {
	Repo  string `json:"repo"`
	Space string `json:"space"`
}
