package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatDocListDocsDocView represents a docView object
type NetworkHabitatDocListDocsDocView struct {
	DocId string `json:"docId"`
	Title string `json:"title"`
	Uri   string `json:"uri"`
}

// NetworkHabitatDocListDocsOutput represents the output for network.habitat.doc.listDocs
type NetworkHabitatDocListDocsOutput struct {
	Docs []NetworkHabitatDocListDocsDocView `json:"docs"`
}
