package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatDocUpdateDocInput represents the input for network.habitat.doc.updateDoc
type NetworkHabitatDocUpdateDocInput struct {
	DocId  string `json:"docId"`
	Update string `json:"update"`
}

// NetworkHabitatDocUpdateDocOutput represents the output for network.habitat.doc.updateDoc
type NetworkHabitatDocUpdateDocOutput struct {
	Cid string `json:"cid,omitempty"`
	Uri string `json:"uri"`
}
