package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatDocCreateDocInput represents the input for network.habitat.doc.createDoc
type NetworkHabitatDocCreateDocInput struct {
	Name string `json:"name"`
}

// NetworkHabitatDocCreateDocOutput represents the output for network.habitat.doc.createDoc
type NetworkHabitatDocCreateDocOutput struct {
	DocId string `json:"docId"`
	Uri   string `json:"uri"`
}
