package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatDocsCrdt represents a network.habitat.docs.crdt record
type NetworkHabitatDocsCrdt struct {
	LexiconTypeID string `json:"$type"`
	Blob          string `json:"blob"`
}

// MarshalJSON sets $type to "network.habitat.docs.crdt" before encoding.
func (t NetworkHabitatDocsCrdt) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.docs.crdt"
	type alias NetworkHabitatDocsCrdt
	return json.Marshal(alias(t))
}
