package habitat

// Code generated by lexgen. DO NOT EDIT.

import (
	"encoding/json"
	"github.com/bluesky-social/indigo/atproto/atdata"
)

// NetworkHabitatDocsComment represents a network.habitat.docs.comment record
type NetworkHabitatDocsComment struct {
	LexiconTypeID string       `json:"$type"`
	AnchorEnd     atdata.Bytes `json:"anchorEnd"`
	AnchorStart   atdata.Bytes `json:"anchorStart"`
	Body          string       `json:"body"`
	CreatedAt     string       `json:"createdAt"`
	QuotedText    string       `json:"quotedText,omitempty"`
}

// MarshalJSON sets $type to "network.habitat.docs.comment" before encoding.
func (t NetworkHabitatDocsComment) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.docs.comment"
	type alias NetworkHabitatDocsComment
	return json.Marshal(alias(t))
}
