package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatDocs represents a network.habitat.docs record
type NetworkHabitatDocs struct {
	Blob         string `json:"blob"`
	EditorClique string `json:"editorClique,omitempty"`
	Name         string `json:"name"`
}
