package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatDocsCreateDocInput represents the input for network.habitat.docs.createDoc
type NetworkHabitatDocsCreateDocInput struct {
	Name string `json:"name"`
}

// NetworkHabitatDocsCreateDocOutput represents the output for network.habitat.docs.createDoc
type NetworkHabitatDocsCreateDocOutput struct {
	DocId string `json:"docId"`
	Uri   string `json:"uri"`
}
