package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatDocsCommentReplyCommentRef represents a commentRef object
type NetworkHabitatDocsCommentReplyCommentRef struct {
	LexiconTypeID string `json:"$type"`
	Cid           string `json:"cid"`
	Uri           string `json:"uri"`
}

// MarshalJSON sets $type to "network.habitat.docs.commentReply#commentRef" before encoding.
func (t NetworkHabitatDocsCommentReplyCommentRef) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.docs.commentReply#commentRef"
	type alias NetworkHabitatDocsCommentReplyCommentRef
	return json.Marshal(alias(t))
}

// NetworkHabitatDocsCommentReply represents a network.habitat.docs.commentReply record
type NetworkHabitatDocsCommentReply struct {
	LexiconTypeID string                                   `json:"$type"`
	Body          string                                   `json:"body"`
	Comment       NetworkHabitatDocsCommentReplyCommentRef `json:"comment"`
	CreatedAt     string                                   `json:"createdAt"`
}

// MarshalJSON sets $type to "network.habitat.docs.commentReply" before encoding.
func (t NetworkHabitatDocsCommentReply) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.docs.commentReply"
	type alias NetworkHabitatDocsCommentReply
	return json.Marshal(alias(t))
}
