package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatDocsListCommentsCommentView represents a commentView object
type NetworkHabitatDocsListCommentsCommentView struct {
	Author    string                                    `json:"author"`
	Body      string                                    `json:"body"`
	CreatedAt string                                    `json:"createdAt"`
	Range     NetworkHabitatDocsListCommentsRangeView   `json:"range,omitempty"`
	Replies   []NetworkHabitatDocsListCommentsReplyView `json:"replies"`
	Uri       string                                    `json:"uri"`
}

// NetworkHabitatDocsListCommentsParams represents the input parameters for network.habitat.docs.listComments
type NetworkHabitatDocsListCommentsParams struct {
	DocId string `json:"docId"`
}

// NetworkHabitatDocsListCommentsOutput represents the output for network.habitat.docs.listComments
type NetworkHabitatDocsListCommentsOutput struct {
	Comments []NetworkHabitatDocsListCommentsCommentView `json:"comments"`
}

// NetworkHabitatDocsListCommentsRangeView represents a rangeView object
type NetworkHabitatDocsListCommentsRangeView struct {
	End   string `json:"end"`
	Start string `json:"start"`
}

// NetworkHabitatDocsListCommentsReplyView represents a replyView object
type NetworkHabitatDocsListCommentsReplyView struct {
	Author    string `json:"author"`
	Body      string `json:"body"`
	CreatedAt string `json:"createdAt"`
	Uri       string `json:"uri"`
}
