package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatDocsListDocsDocView represents a docView object
type NetworkHabitatDocsListDocsDocView struct {
	DocId string `json:"docId"`
	Title string `json:"title"`
	Uri   string `json:"uri"`
}

// NetworkHabitatDocsListDocsOutput represents the output for network.habitat.docs.listDocs
type NetworkHabitatDocsListDocsOutput struct {
	Docs []NetworkHabitatDocsListDocsDocView `json:"docs"`
}
