package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatDocsMarkdown represents a network.habitat.docs.markdown record
type NetworkHabitatDocsMarkdown struct {
	LexiconTypeID string `json:"$type"`
	Content       string `json:"content"`
	Title         string `json:"title"`
}

// MarshalJSON sets $type to "network.habitat.docs.markdown" before encoding.
func (t NetworkHabitatDocsMarkdown) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.docs.markdown"
	type alias NetworkHabitatDocsMarkdown
	return json.Marshal(alias(t))
}
