package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatDocsCommentResolution represents a network.habitat.docs.commentResolution record
type NetworkHabitatDocsCommentResolution struct {
	LexiconTypeID string                  `json:"$type"`
	Comment       ComAtprotoRepoStrongRef `json:"comment"`
	CreatedAt     string                  `json:"createdAt"`
	Resolved      bool                    `json:"resolved"`
}

// MarshalJSON sets $type to "network.habitat.docs.commentResolution" before encoding.
func (t NetworkHabitatDocsCommentResolution) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.docs.commentResolution"
	type alias NetworkHabitatDocsCommentResolution
	return json.Marshal(alias(t))
}
