package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatDocsCommentReply represents a network.habitat.docs.commentReply record
type NetworkHabitatDocsCommentReply struct {
	LexiconTypeID string                  `json:"$type"`
	Body          string                  `json:"body"`
	Comment       ComAtprotoRepoStrongRef `json:"comment"`
	CreatedAt     string                  `json:"createdAt"`
}

// MarshalJSON sets $type to "network.habitat.docs.commentReply" before encoding.
func (t NetworkHabitatDocsCommentReply) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.docs.commentReply"
	type alias NetworkHabitatDocsCommentReply
	return json.Marshal(alias(t))
}
