package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatDocsCrdt represents a network.habitat.docs.crdt record
type NetworkHabitatDocsCrdt struct {
	LexiconTypeID string `json:"$type,const=network.habitat.docs.crdt"`
	Blob          string `json:"blob"`
}
