package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatDocsListDocsDocView represents a docView object
type NetworkHabitatDocsListDocsDocView struct {
	LexiconTypeID string `json:"$type"`
	DocId         string `json:"docId"`
	Title         string `json:"title"`
	Uri           string `json:"uri"`
}

// MarshalJSON sets $type to "network.habitat.docs.listDocs#docView" before encoding.
func (t NetworkHabitatDocsListDocsDocView) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.docs.listDocs#docView"
	type alias NetworkHabitatDocsListDocsDocView
	return json.Marshal(alias(t))
}

// NetworkHabitatDocsListDocsOutput represents the output for network.habitat.docs.listDocs
type NetworkHabitatDocsListDocsOutput struct {
	Docs []NetworkHabitatDocsListDocsDocView `json:"docs"`
}
