package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatDocsComment represents a network.habitat.docs.comment record
type NetworkHabitatDocsComment struct {
	Body      string                         `json:"body"`
	CreatedAt string                         `json:"createdAt"`
	DocSpace  string                         `json:"docSpace"`
	Parent    string                         `json:"parent,omitempty"`
	Range     NetworkHabitatDocsCommentRange `json:"range,omitempty"`
}

// NetworkHabitatDocsCommentRange represents a range object
type NetworkHabitatDocsCommentRange struct {
	End   string `json:"end"`
	Start string `json:"start"`
}
