package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatDocsMarkdown represents a network.habitat.docs.markdown record
type NetworkHabitatDocsMarkdown struct {
	LexiconTypeID string `json:"$type,const=network.habitat.docs.markdown"`
	Content       string `json:"content"`
	Title         string `json:"title"`
}
