package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatDocsUpdateDocInput represents the input for network.habitat.docs.updateDoc
type NetworkHabitatDocsUpdateDocInput struct {
	DocId  string `json:"docId"`
	Update string `json:"update"`
}

// NetworkHabitatDocsUpdateDocOutput represents the output for network.habitat.docs.updateDoc
type NetworkHabitatDocsUpdateDocOutput struct {
	Cid string `json:"cid,omitempty"`
	Uri string `json:"uri"`
}
