package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatDocsEdit represents a network.habitat.docs.edit record
type NetworkHabitatDocsEdit struct {
	Blob         string `json:"blob"`
	Doc          string `json:"doc"`
	EditorClique string `json:"editorClique,omitempty"`
	Name         string `json:"name"`
}
