package habitat

// Code generated by lexgen. DO NOT EDIT.

import (
	"encoding/json"
	"github.com/bluesky-social/indigo/atproto/atdata"
)

// NetworkHabitatDropFile represents a network.habitat.drop.file record
type NetworkHabitatDropFile struct {
	LexiconTypeID string      `json:"$type"`
	CreatedAt     string      `json:"createdAt"`
	File          atdata.Blob `json:"file"`
	Name          string      `json:"name"`
	UploadedBy    string      `json:"uploadedBy,omitempty"`
}

// MarshalJSON sets $type to "network.habitat.drop.file" before encoding.
func (t NetworkHabitatDropFile) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.drop.file"
	type alias NetworkHabitatDropFile
	return json.Marshal(alias(t))
}
