package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatEmaildomainCreateOrgInput represents the input for network.habitat.emaildomain.createOrg
type NetworkHabitatEmaildomainCreateOrgInput struct {
	Domain string `json:"domain"`
	Handle string `json:"handle"`
}

// NetworkHabitatEmaildomainCreateOrgOutput represents the output for network.habitat.emaildomain.createOrg
type NetworkHabitatEmaildomainCreateOrgOutput struct {
	Org string `json:"org"`
}
