package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatGranteeDidGrantee represents a didGrantee object
type NetworkHabitatGranteeDidGrantee struct {
	Did string `json:"did"`
}

// NetworkHabitatGranteeCliqueRef represents a cliqueRef object
type NetworkHabitatGranteeCliqueRef struct {
	Uri string `json:"uri"`
}
