package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatGranteeDidGrantee represents a didGrantee object
type NetworkHabitatGranteeDidGrantee struct {
	Did string `json:"did"`
}

// NetworkHabitatGranteeClique represents a clique object
type NetworkHabitatGranteeClique struct {
	Clique string `json:"clique"`
}
