package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatGreenskyPost represents a network.habitat.greensky.post record
type NetworkHabitatGreenskyPost struct {
	CreatedAt string                             `json:"createdAt"`
	Reply     NetworkHabitatGreenskyPostReplyRef `json:"reply,omitempty"`
	Text      string                             `json:"text"`
}

// NetworkHabitatGreenskyPostReplyRef represents a replyRef object
type NetworkHabitatGreenskyPostReplyRef struct {
	Parent string `json:"parent"`
	Root   string `json:"root"`
}
