package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatGreenskyGetPostsOutput represents the output for network.habitat.greensky.getPosts
type NetworkHabitatGreenskyGetPostsOutput struct {
	Threads []NetworkHabitatGreenskyGetPostsThreadView `json:"threads"`
}

// NetworkHabitatGreenskyGetPostsPostView represents a postView object
type NetworkHabitatGreenskyGetPostsPostView struct {
	Author    string `json:"author"`
	CreatedAt string `json:"createdAt"`
	IndexedAt string `json:"indexedAt,omitempty"`
	SpaceUri  string `json:"spaceUri"`
	Text      string `json:"text"`
	Uri       string `json:"uri"`
}

// NetworkHabitatGreenskyGetPostsThreadView represents a threadView object
type NetworkHabitatGreenskyGetPostsThreadView struct {
	Post    NetworkHabitatGreenskyGetPostsPostView   `json:"post"`
	Replies []NetworkHabitatGreenskyGetPostsPostView `json:"replies"`
}
