package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatGroupsListGroupsParams represents the input parameters for network.habitat.groups.listGroups
type NetworkHabitatGroupsListGroupsParams struct {
}

// NetworkHabitatGroupsListGroupsOutput represents the output for network.habitat.groups.listGroups
type NetworkHabitatGroupsListGroupsOutput struct {
	Groups []NetworkHabitatGroupsDefsGroupView `json:"groups"`
}
