package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatGroupsAddMemberInput represents the input for network.habitat.groups.addMember
type NetworkHabitatGroupsAddMemberInput struct {
	Group        string `json:"group"`
	SubjectDid   string `json:"subjectDid,omitempty"`
	SubjectGroup string `json:"subjectGroup,omitempty"`
}

// NetworkHabitatGroupsAddMemberOutput represents the output for network.habitat.groups.addMember
type NetworkHabitatGroupsAddMemberOutput struct {
	Uri string `json:"uri,omitempty"`
}
