package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatGroupsCreateGroupInput represents the input for network.habitat.groups.createGroup
type NetworkHabitatGroupsCreateGroupInput struct {
	Description string `json:"description,omitempty"`
	Name        string `json:"name"`
}

// NetworkHabitatGroupsCreateGroupOutput represents the output for network.habitat.groups.createGroup
type NetworkHabitatGroupsCreateGroupOutput struct {
	Uri string `json:"uri"`
}
