package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatGroupsUpdateGroupInput represents the input for network.habitat.groups.updateGroup
type NetworkHabitatGroupsUpdateGroupInput struct {
	Description string `json:"description,omitempty"`
	Group       string `json:"group"`
	Name        string `json:"name,omitempty"`
}

// NetworkHabitatGroupsUpdateGroupOutput represents the output for network.habitat.groups.updateGroup
type NetworkHabitatGroupsUpdateGroupOutput struct {
	Uri string `json:"uri"`
}
