package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatGroupsDefsGroupRef represents a groupRef object
type NetworkHabitatGroupsDefsGroupRef struct {
	Name string `json:"name"`
	Uri  string `json:"uri"`
}

// NetworkHabitatGroupsDefsGroupView represents a groupView object
type NetworkHabitatGroupsDefsGroupView struct {
	CanManage       bool                                 `json:"canManage"`
	CreatedAt       string                               `json:"createdAt,omitempty"`
	Description     string                               `json:"description,omitempty"`
	InheritedGroups []NetworkHabitatGroupsDefsGroupRef   `json:"inheritedGroups,omitempty"`
	IsMember        bool                                 `json:"isMember"`
	MemberCount     int64                                `json:"memberCount,omitempty"`
	Members         []NetworkHabitatGroupsDefsMemberView `json:"members,omitempty"`
	Name            string                               `json:"name"`
	Uri             string                               `json:"uri"`
}

// NetworkHabitatGroupsDefsMemberView represents a memberView object
type NetworkHabitatGroupsDefsMemberView struct {
	Did      string `json:"did"`
	Direct   bool   `json:"direct"`
	Role     string `json:"role,omitempty"`
	ViaGroup string `json:"viaGroup,omitempty"`
}
