package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatGroupProfile represents a network.habitat.group.profile record
type NetworkHabitatGroupProfile struct {
	LexiconTypeID string `json:"$type"`
	CreatedAt     string `json:"createdAt,omitempty"`
	Description   string `json:"description,omitempty"`
	Name          string `json:"name"`
}

// MarshalJSON sets $type to "network.habitat.group.profile" before encoding.
func (t NetworkHabitatGroupProfile) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.group.profile"
	type alias NetworkHabitatGroupProfile
	return json.Marshal(alias(t))
}
