package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatGroupProfile represents a network.habitat.group.profile record
type NetworkHabitatGroupProfile struct {
	LexiconTypeID string `json:"$type,const=network.habitat.group.profile"`
	CreatedAt     string `json:"createdAt,omitempty"`
	Description   string `json:"description,omitempty"`
	Name          string `json:"name"`
}
