package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatGroupsGetGroupParams represents the input parameters for network.habitat.groups.getGroup
type NetworkHabitatGroupsGetGroupParams struct {
	Group string `json:"group"`
}

// NetworkHabitatGroupsGetGroupOutput represents the output for network.habitat.groups.getGroup
type NetworkHabitatGroupsGetGroupOutput struct {
}
