package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatGroup represents a network.habitat.group record
type NetworkHabitatGroup struct {
	Description string   `json:"description,omitempty"`
	Members     []string `json:"members"`
	Name        string   `json:"name"`
}
