package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatGroupsDefsGroupRef represents a groupRef object
type NetworkHabitatGroupsDefsGroupRef struct {
	LexiconTypeID string `json:"$type"`
	Name          string `json:"name"`
	Uri           string `json:"uri"`
}

// MarshalJSON sets $type to "network.habitat.groups.defs#groupRef" before encoding.
func (t NetworkHabitatGroupsDefsGroupRef) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.groups.defs#groupRef"
	type alias NetworkHabitatGroupsDefsGroupRef
	return json.Marshal(alias(t))
}

// NetworkHabitatGroupsDefsGroupView represents a groupView object
type NetworkHabitatGroupsDefsGroupView struct {
	LexiconTypeID   string                               `json:"$type"`
	CanManage       bool                                 `json:"canManage"`
	CreatedAt       string                               `json:"createdAt,omitempty"`
	Description     string                               `json:"description,omitempty"`
	InheritedGroups []NetworkHabitatGroupsDefsGroupRef   `json:"inheritedGroups,omitempty"`
	IsMember        bool                                 `json:"isMember"`
	MemberCount     int64                                `json:"memberCount,omitempty"`
	Members         []NetworkHabitatGroupsDefsMemberView `json:"members,omitempty"`
	Name            string                               `json:"name"`
	Uri             string                               `json:"uri"`
}

// MarshalJSON sets $type to "network.habitat.groups.defs#groupView" before encoding.
func (t NetworkHabitatGroupsDefsGroupView) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.groups.defs#groupView"
	type alias NetworkHabitatGroupsDefsGroupView
	return json.Marshal(alias(t))
}

// NetworkHabitatGroupsDefsMemberView represents a memberView object
type NetworkHabitatGroupsDefsMemberView struct {
	LexiconTypeID string `json:"$type"`
	Did           string `json:"did"`
	Direct        bool   `json:"direct"`
	Role          string `json:"role,omitempty"`
	ViaGroup      string `json:"viaGroup,omitempty"`
}

// MarshalJSON sets $type to "network.habitat.groups.defs#memberView" before encoding.
func (t NetworkHabitatGroupsDefsMemberView) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.groups.defs#memberView"
	type alias NetworkHabitatGroupsDefsMemberView
	return json.Marshal(alias(t))
}
