package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatGroupsDeleteMemberInput represents the input for network.habitat.groups.deleteMember
type NetworkHabitatGroupsDeleteMemberInput struct {
	Group        string `json:"group"`
	SubjectDid   string `json:"subjectDid,omitempty"`
	SubjectGroup string `json:"subjectGroup,omitempty"`
}
