package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatHiveMintIdentityInput represents the input for network.habitat.hive.mintIdentity
type NetworkHabitatHiveMintIdentityInput struct {
	Handle string `json:"handle"`
}
