package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatInstanceDescribeInstanceOutput represents the output for network.habitat.instance.describeInstance
type NetworkHabitatInstanceDescribeInstanceOutput struct {
	InviteRequired bool   `json:"inviteRequired"`
	Name           string `json:"name"`
}
