package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatInternalGrantPermissionInput represents the input for network.habitat.internal.grantPermission
type NetworkHabitatInternalGrantPermissionInput struct {
	Proof string `json:"proof"`
}

// NetworkHabitatInternalGrantPermissionOutput represents the output for network.habitat.internal.grantPermission
type NetworkHabitatInternalGrantPermissionOutput struct {
	Message string `json:"message,omitempty"`
	Status  string `json:"status,omitempty"`
}
