package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatInternalNotifyOfUpdateInput represents the input for network.habitat.internal.notifyOfUpdate
type NetworkHabitatInternalNotifyOfUpdateInput struct {
	Collection string `json:"collection"`
	Recipient  string `json:"recipient"`
	Rkey       string `json:"rkey"`
}
