package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatInternalGetRecordParams represents the input parameters for network.habitat.internal.getRecord
type NetworkHabitatInternalGetRecordParams struct {
	AllowToken string `json:"allowToken,omitempty"`
	Collection string `json:"collection"`
	Repo       string `json:"repo"`
	Rkey       string `json:"rkey"`
}

// NetworkHabitatInternalGetRecordOutput represents the output for network.habitat.internal.getRecord
type NetworkHabitatInternalGetRecordOutput struct {
	Uri   string      `json:"uri"`
	Value interface{} `json:"value"`
}
