package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatListConnectedAppsOutput represents the output for network.habitat.listConnectedApps
type NetworkHabitatListConnectedAppsOutput struct {
	Apps []NetworkHabitatListConnectedAppsApp `json:"apps"`
}

// NetworkHabitatListConnectedAppsApp represents a app object
type NetworkHabitatListConnectedAppsApp struct {
	ClientID  string `json:"clientID"`
	ClientUri string `json:"clientUri"`
	LastUsed  string `json:"lastUsed"`
	LogoUri   string `json:"logoUri,omitempty"`
	Name      string `json:"name"`
}
