package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatListRecordsRecord represents a record object
type NetworkHabitatListRecordsRecord struct {
	Cid   string      `json:"cid"`
	Uri   string      `json:"uri"`
	Value interface{} `json:"value"`
}

// NetworkHabitatListRecordsInput represents the input for network.habitat.listRecords
type NetworkHabitatListRecordsInput struct {
	Collection string   `json:"collection"`
	Cursor     string   `json:"cursor,omitempty"`
	Limit      int64    `json:"limit,omitempty"`
	Since      string   `json:"since,omitempty"`
	Subjects   []string `json:"subjects"`
}

// NetworkHabitatListRecordsOutput represents the output for network.habitat.listRecords
type NetworkHabitatListRecordsOutput struct {
	Cursor  string                            `json:"cursor,omitempty"`
	Records []NetworkHabitatListRecordsRecord `json:"records"`
}
