package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatListConnectedAppsApp represents a app object
type NetworkHabitatListConnectedAppsApp struct {
	LexiconTypeID string `json:"$type"`
	ClientID      string `json:"clientID"`
	ClientUri     string `json:"clientUri"`
	LastUsed      string `json:"lastUsed"`
	LogoUri       string `json:"logoUri,omitempty"`
	Name          string `json:"name"`
}

// MarshalJSON sets $type to "network.habitat.listConnectedApps#app" before encoding.
func (t NetworkHabitatListConnectedAppsApp) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.listConnectedApps#app"
	type alias NetworkHabitatListConnectedAppsApp
	return json.Marshal(alias(t))
}

// NetworkHabitatListConnectedAppsOutput represents the output for network.habitat.listConnectedApps
type NetworkHabitatListConnectedAppsOutput struct {
	Apps []NetworkHabitatListConnectedAppsApp `json:"apps"`
}
