package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatListRecordsInput represents the input for network.habitat.listRecords
type NetworkHabitatListRecordsInput struct {
	Collection string        `json:"collection"`
	Since      string        `json:"since,omitempty"`
	Subjects   []interface{} `json:"subjects"`
}

// NetworkHabitatListRecordsOutput represents the output for network.habitat.listRecords
type NetworkHabitatListRecordsOutput struct {
}
