package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatMcpServer represents a network.habitat.mcp.server record
type NetworkHabitatMcpServer struct {
	LexiconTypeID string `json:"$type"`
	Description   string `json:"description,omitempty"`
	Name          string `json:"name"`
	NangoKey      string `json:"nangoKey"`
	UpdatedAt     string `json:"updatedAt"`
}

// MarshalJSON sets $type to "network.habitat.mcp.server" before encoding.
func (t NetworkHabitatMcpServer) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.mcp.server"
	type alias NetworkHabitatMcpServer
	return json.Marshal(alias(t))
}
