package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatMcpStartAuthorizationInput represents the input for network.habitat.mcp.startAuthorization
type NetworkHabitatMcpStartAuthorizationInput struct {
	Id          string `json:"id"`
	Org         string `json:"org"`
	RedirectUri string `json:"redirectUri"`
}

// NetworkHabitatMcpStartAuthorizationOutput represents the output for network.habitat.mcp.startAuthorization
type NetworkHabitatMcpStartAuthorizationOutput struct {
	AuthorizationUrl string `json:"authorizationUrl"`
}
