package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatMcpDefsHeader represents a header object
type NetworkHabitatMcpDefsHeader struct {
	LexiconTypeID string `json:"$type"`
	Name          string `json:"name"`
	Value         string `json:"value"`
}

// MarshalJSON sets $type to "network.habitat.mcp.defs#header" before encoding.
func (t NetworkHabitatMcpDefsHeader) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.mcp.defs#header"
	type alias NetworkHabitatMcpDefsHeader
	return json.Marshal(alias(t))
}

// NetworkHabitatMcpDefsServer represents a server object
type NetworkHabitatMcpDefsServer struct {
	LexiconTypeID string `json:"$type"`
	AuthType      string `json:"authType"`
	Description   string `json:"description,omitempty"`
	Id            string `json:"id"`
	Name          string `json:"name"`
}

// MarshalJSON sets $type to "network.habitat.mcp.defs#server" before encoding.
func (t NetworkHabitatMcpDefsServer) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.mcp.defs#server"
	type alias NetworkHabitatMcpDefsServer
	return json.Marshal(alias(t))
}
