package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatMcpCompleteAddServerInput represents the input for network.habitat.mcp.completeAddServer
type NetworkHabitatMcpCompleteAddServerInput struct {
	Description string `json:"description,omitempty"`
	Id          string `json:"id"`
	Name        string `json:"name"`
	Org         string `json:"org"`
}

// NetworkHabitatMcpCompleteAddServerOutput represents the output for network.habitat.mcp.completeAddServer
type NetworkHabitatMcpCompleteAddServerOutput struct {
	Server NetworkHabitatMcpDefsServer `json:"server"`
}
