package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatMcpConnectServerInput represents the input for network.habitat.mcp.connectServer
type NetworkHabitatMcpConnectServerInput struct {
	Credential string `json:"credential"`
	Id         string `json:"id"`
}
