package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatMcpUpdateServerInput represents the input for network.habitat.mcp.updateServer
type NetworkHabitatMcpUpdateServerInput struct {
	Description string                        `json:"description,omitempty"`
	Headers     []NetworkHabitatMcpDefsHeader `json:"headers,omitempty"`
	Id          string                        `json:"id"`
	Org         string                        `json:"org"`
	Url         string                        `json:"url,omitempty"`
}

// NetworkHabitatMcpUpdateServerOutput represents the output for network.habitat.mcp.updateServer
type NetworkHabitatMcpUpdateServerOutput struct {
	Server NetworkHabitatMcpDefsServer `json:"server"`
}
