package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatMcpUpdateServerInput represents the input for network.habitat.mcp.updateServer
type NetworkHabitatMcpUpdateServerInput struct {
	AuthType    string `json:"authType,omitempty"`
	Description string `json:"description,omitempty"`
	Id          string `json:"id"`
	Name        string `json:"name,omitempty"`
	Url         string `json:"url,omitempty"`
}

// NetworkHabitatMcpUpdateServerOutput represents the output for network.habitat.mcp.updateServer
type NetworkHabitatMcpUpdateServerOutput struct {
	Server NetworkHabitatMcpDefsServer `json:"server"`
}
