package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatMcpCancelAddServerInput represents the input for network.habitat.mcp.cancelAddServer
type NetworkHabitatMcpCancelAddServerInput struct {
	Id  string `json:"id"`
	Org string `json:"org"`
}
