package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatMcpAddServerInput represents the input for network.habitat.mcp.addServer
type NetworkHabitatMcpAddServerInput struct {
	Description string `json:"description,omitempty"`
	Name        string `json:"name"`
	Org         string `json:"org"`
}

// NetworkHabitatMcpAddServerOutput represents the output for network.habitat.mcp.addServer
type NetworkHabitatMcpAddServerOutput struct {
	Id           string `json:"id"`
	SessionToken string `json:"sessionToken"`
}
