package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatMcpRemoveServerInput represents the input for network.habitat.mcp.removeServer
type NetworkHabitatMcpRemoveServerInput struct {
	Id  string `json:"id"`
	Org string `json:"org"`
}
