package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatMcpDefsServer represents a server object
type NetworkHabitatMcpDefsServer struct {
	LexiconTypeID string `json:"$type"`
	AuthType      string `json:"authType"`
	Description   string `json:"description,omitempty"`
	Id            string `json:"id"`
	Name          string `json:"name"`
	Url           string `json:"url"`
}

// MarshalJSON sets $type to "network.habitat.mcp.defs#server" before encoding.
func (t NetworkHabitatMcpDefsServer) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.mcp.defs#server"
	type alias NetworkHabitatMcpDefsServer
	return json.Marshal(alias(t))
}
