package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatMcpConfirmConnectionInput represents the input for network.habitat.mcp.confirmConnection
type NetworkHabitatMcpConfirmConnectionInput struct {
	ConnectionId string `json:"connectionId"`
	Id           string `json:"id"`
	Org          string `json:"org"`
}
