package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatMcpDisconnectServerInput represents the input for network.habitat.mcp.disconnectServer
type NetworkHabitatMcpDisconnectServerInput struct {
	Id string `json:"id"`
}
