package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatMcpListServersOutput represents the output for network.habitat.mcp.listServers
type NetworkHabitatMcpListServersOutput struct {
	Servers []NetworkHabitatMcpListServersServerWithStatus `json:"servers"`
}

// NetworkHabitatMcpListServersServerWithStatus represents a serverWithStatus object
type NetworkHabitatMcpListServersServerWithStatus struct {
	LexiconTypeID string                      `json:"$type"`
	Connected     bool                        `json:"connected"`
	Server        NetworkHabitatMcpDefsServer `json:"server"`
}

// MarshalJSON sets $type to "network.habitat.mcp.listServers#serverWithStatus" before encoding.
func (t NetworkHabitatMcpListServersServerWithStatus) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.mcp.listServers#serverWithStatus"
	type alias NetworkHabitatMcpListServersServerWithStatus
	return json.Marshal(alias(t))
}
