package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatMcpAddServerInput represents the input for network.habitat.mcp.addServer
type NetworkHabitatMcpAddServerInput struct {
	AuthType    string `json:"authType"`
	Description string `json:"description,omitempty"`
	Name        string `json:"name"`
	Url         string `json:"url"`
}

// NetworkHabitatMcpAddServerOutput represents the output for network.habitat.mcp.addServer
type NetworkHabitatMcpAddServerOutput struct {
	Server NetworkHabitatMcpDefsServer `json:"server"`
}
