package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatNotificationListNotificationsRecord represents a record object
type NetworkHabitatNotificationListNotificationsRecord struct {
	Cid   string                                     `json:"cid"`
	Uri   string                                     `json:"uri"`
	Value NetworkHabitatNotificationDefsNotification `json:"value"`
}

// NetworkHabitatNotificationListNotificationsParams represents the input parameters for network.habitat.notification.listNotifications
type NetworkHabitatNotificationListNotificationsParams struct {
	Collection string `json:"collection,omitempty"`
}

// NetworkHabitatNotificationListNotificationsOutput represents the output for network.habitat.notification.listNotifications
type NetworkHabitatNotificationListNotificationsOutput struct {
	Cursor  string                                              `json:"cursor,omitempty"`
	Records []NetworkHabitatNotificationListNotificationsRecord `json:"records"`
}
