package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatNotificationListNotificationsParams represents the input parameters for network.habitat.notification.listNotifications
type NetworkHabitatNotificationListNotificationsParams struct {
	Collection string `json:"collection,omitempty"`
	Cursor     string `json:"cursor,omitempty"`
	Limit      int64  `json:"limit,omitempty"`
	Reverse    bool   `json:"reverse,omitempty"`
}

// NetworkHabitatNotificationListNotificationsOutput represents the output for network.habitat.notification.listNotifications
type NetworkHabitatNotificationListNotificationsOutput struct {
	Cursor  string                                              `json:"cursor,omitempty"`
	Records []NetworkHabitatNotificationListNotificationsRecord `json:"records"`
}

// NetworkHabitatNotificationListNotificationsRecord represents a record object
type NetworkHabitatNotificationListNotificationsRecord struct {
	Cid   string                                                  `json:"cid"`
	Uri   string                                                  `json:"uri"`
	Value NetworkHabitatNotificationListNotificationsNotification `json:"value"`
}

// NetworkHabitatNotificationListNotificationsNotification represents a notification object
type NetworkHabitatNotificationListNotificationsNotification struct {
	Collection string `json:"collection"`
	OriginDid  string `json:"originDid"`
	Rkey       string `json:"rkey"`
}
