package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatNotificationDefsNotification represents a notification object
type NetworkHabitatNotificationDefsNotification struct {
	Collection string `json:"collection"`
	Did        string `json:"did"`
	OriginDid  string `json:"originDid"`
	Rkey       string `json:"rkey"`
}
