package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatNotificationCreateNotificationInput represents the input for network.habitat.notification.createNotification
type NetworkHabitatNotificationCreateNotificationInput struct {
	Collection string `json:"collection"`
	Did        string `json:"did"`
	Rkey       string `json:"rkey"`
}

// NetworkHabitatNotificationCreateNotificationOutput represents the output for network.habitat.notification.createNotification
type NetworkHabitatNotificationCreateNotificationOutput struct {
	Uri              string `json:"uri"`
	ValidationStatus string `json:"validationStatus,omitempty"`
}
