package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatOpensocialGetProfilesParams represents the input parameters for network.habitat.opensocial.getProfiles
type NetworkHabitatOpensocialGetProfilesParams struct {
	Dids []string `json:"dids"`
	Org  string   `json:"org"`
}

// NetworkHabitatOpensocialGetProfilesOutput represents the output for network.habitat.opensocial.getProfiles
type NetworkHabitatOpensocialGetProfilesOutput struct {
	Profiles []NetworkHabitatOpensocialGetProfilesProfileView `json:"profiles"`
}

// NetworkHabitatOpensocialGetProfilesProfileView represents a profileView object
type NetworkHabitatOpensocialGetProfilesProfileView struct {
	LexiconTypeID string `json:"$type"`
	AvatarUrl     string `json:"avatarUrl,omitempty"`
	Bio           string `json:"bio,omitempty"`
	Did           string `json:"did"`
	DisplayName   string `json:"displayName,omitempty"`
	Handle        string `json:"handle"`
}

// MarshalJSON sets $type to "network.habitat.opensocial.getProfiles#profileView" before encoding.
func (t NetworkHabitatOpensocialGetProfilesProfileView) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.opensocial.getProfiles#profileView"
	type alias NetworkHabitatOpensocialGetProfilesProfileView
	return json.Marshal(alias(t))
}
