package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatOpensocialCreateOrgInput represents the input for network.habitat.opensocial.createOrg
type NetworkHabitatOpensocialCreateOrgInput struct {
	Handle string `json:"handle"`
}

// NetworkHabitatOpensocialCreateOrgOutput represents the output for network.habitat.opensocial.createOrg
type NetworkHabitatOpensocialCreateOrgOutput struct {
	Org string `json:"org"`
}
