package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatOrgRequestCrawlInput represents the input for network.habitat.org.requestCrawl
type NetworkHabitatOrgRequestCrawlInput struct {
	OrgDid string `json:"orgDid"`
}

// NetworkHabitatOrgRequestCrawlOutput represents the output for network.habitat.org.requestCrawl
type NetworkHabitatOrgRequestCrawlOutput struct {
	Message string `json:"message,omitempty"`
	Status  string `json:"status"`
}
