package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatOrgDowngradeAdminInput represents the input for network.habitat.org.downgradeAdmin
type NetworkHabitatOrgDowngradeAdminInput struct {
	Admin string `json:"admin"`
}
