package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatOrgCreateInput represents the input for network.habitat.org.create
type NetworkHabitatOrgCreateInput struct {
	AdminHandle   string `json:"admin_handle"`
	AdminPassword string `json:"admin_password"`
	Name          string `json:"name,omitempty"`
	Subdomain     string `json:"subdomain"`
}

// NetworkHabitatOrgCreateOutput represents the output for network.habitat.org.create
type NetworkHabitatOrgCreateOutput struct {
	AdminDid    string `json:"admin_did"`
	AdminHandle string `json:"admin_handle"`
	Name        string `json:"name,omitempty"`
	OrgId       string `json:"org_id"`
}
