package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatOrgGetAdminsOutput represents the output for network.habitat.org.getAdmins
type NetworkHabitatOrgGetAdminsOutput struct {
	Admins []NetworkHabitatOrgGetAdminsMember `json:"admins"`
}

// NetworkHabitatOrgGetAdminsMember represents a member object
type NetworkHabitatOrgGetAdminsMember struct {
	LexiconTypeID string `json:"$type"`
	Did           string `json:"did"`
	Handle        string `json:"handle"`
}

// MarshalJSON sets $type to "network.habitat.org.getAdmins#member" before encoding.
func (t NetworkHabitatOrgGetAdminsMember) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.org.getAdmins#member"
	type alias NetworkHabitatOrgGetAdminsMember
	return json.Marshal(alias(t))
}
