package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatOrgIssueInviteTokenInput represents the input for network.habitat.org.issueInviteToken
type NetworkHabitatOrgIssueInviteTokenInput struct {
	ExpiresAt string `json:"expiresAt,omitempty"`
	Reusable  bool   `json:"reusable,omitempty"`
}

// NetworkHabitatOrgIssueInviteTokenOutput represents the output for network.habitat.org.issueInviteToken
type NetworkHabitatOrgIssueInviteTokenOutput struct {
	Token string `json:"token"`
}
