package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatOrgGetMetadataOutput represents the output for network.habitat.org.getMetadata
type NetworkHabitatOrgGetMetadataOutput struct {
	Description string `json:"description,omitempty"`
	Domain      string `json:"domain"`
	Name        string `json:"name,omitempty"`
}
