package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatOrgRemoveAdminInput represents the input for network.habitat.org.removeAdmin
type NetworkHabitatOrgRemoveAdminInput struct {
	Admin string `json:"admin"`
}
