package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatOrgAddMembersInput represents the input for network.habitat.org.addMembers
type NetworkHabitatOrgAddMembersInput struct {
	Members []string `json:"members"`
}
