package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatOrgLoginMemberInput represents the input for network.habitat.org.loginMember
type NetworkHabitatOrgLoginMemberInput struct {
	Handle   string `json:"handle"`
	Password string `json:"password"`
}

// NetworkHabitatOrgLoginMemberOutput represents the output for network.habitat.org.loginMember
type NetworkHabitatOrgLoginMemberOutput struct {
	CallbackURL string `json:"callbackURL"`
}
