package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatOrgGetMembersOutput represents the output for network.habitat.org.getMembers
type NetworkHabitatOrgGetMembersOutput struct {
	Members []string `json:"members"`
}
