package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatOrgGetAdminsOutput represents the output for network.habitat.org.getAdmins
type NetworkHabitatOrgGetAdminsOutput struct {
	Admins []NetworkHabitatOrgGetAdminsMember `json:"admins"`
}

// NetworkHabitatOrgGetAdminsMember represents a member object
type NetworkHabitatOrgGetAdminsMember struct {
	Did    string `json:"did"`
	Handle string `json:"handle"`
}
