package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatOrgNotifyAppInput represents the input for network.habitat.org.notifyApp
type NetworkHabitatOrgNotifyAppInput struct {
	Org string `json:"org"`
}
