package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatOrgRemoveMembersInput represents the input for network.habitat.org.removeMembers
type NetworkHabitatOrgRemoveMembersInput struct {
	Members []string `json:"members"`
}
