package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatOrgGetMembersOutput represents the output for network.habitat.org.getMembers
type NetworkHabitatOrgGetMembersOutput struct {
	Members []NetworkHabitatOrgGetMembersMember `json:"members"`
}

// NetworkHabitatOrgGetMembersMember represents a member object
type NetworkHabitatOrgGetMembersMember struct {
	Did    string `json:"did"`
	Handle string `json:"handle"`
}
