package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatOrgAddAdminInput represents the input for network.habitat.org.addAdmin
type NetworkHabitatOrgAddAdminInput struct {
	Admin string `json:"admin"`
}
