package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatOrgGetAdminsOutput represents the output for network.habitat.org.getAdmins
type NetworkHabitatOrgGetAdminsOutput struct {
	Admins []string `json:"admins"`
}
