package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatOrgGetProfileParams represents the input parameters for network.habitat.org.getProfile
type NetworkHabitatOrgGetProfileParams struct {
	Did string `json:"did"`
}

// NetworkHabitatOrgGetProfileOutput represents the output for network.habitat.org.getProfile
type NetworkHabitatOrgGetProfileOutput struct {
	AvatarUrl   string `json:"avatarUrl,omitempty"`
	Bio         string `json:"bio,omitempty"`
	Did         string `json:"did"`
	DisplayName string `json:"displayName,omitempty"`
	Handle      string `json:"handle"`
}
