package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatOrgCreateInput represents the input for network.habitat.org.create
type NetworkHabitatOrgCreateInput struct {
	AdminHandle     string `json:"admin_handle"`
	AdminPassword   string `json:"admin_password"`
	HandleSubdomain string `json:"handle_subdomain"`
	LoginId         string `json:"login_id,omitempty"`
	LoginMethod     string `json:"login_method,omitempty"`
	Name            string `json:"name,omitempty"`
}

// NetworkHabitatOrgCreateOutput represents the output for network.habitat.org.create
type NetworkHabitatOrgCreateOutput struct {
	AdminDid    string `json:"admin_did"`
	AdminHandle string `json:"admin_handle"`
	Name        string `json:"name"`
	OrgId       string `json:"org_id"`
}
