package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatOrgGetMembersOutput represents the output for network.habitat.org.getMembers
type NetworkHabitatOrgGetMembersOutput struct {
	Members []NetworkHabitatOrgGetMembersMember `json:"members"`
}

// NetworkHabitatOrgGetMembersMember represents a member object
type NetworkHabitatOrgGetMembersMember struct {
	LexiconTypeID string `json:"$type"`
	Did           string `json:"did"`
	Handle        string `json:"handle"`
}

// MarshalJSON sets $type to "network.habitat.org.getMembers#member" before encoding.
func (t NetworkHabitatOrgGetMembersMember) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.org.getMembers#member"
	type alias NetworkHabitatOrgGetMembersMember
	return json.Marshal(alias(t))
}
