package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatOrgGetMetadataParams represents the input parameters for network.habitat.org.getMetadata
type NetworkHabitatOrgGetMetadataParams struct {
	OrgId string `json:"orgId,omitempty"`
}

// NetworkHabitatOrgGetMetadataOutput represents the output for network.habitat.org.getMetadata
type NetworkHabitatOrgGetMetadataOutput struct {
	Description     string `json:"description,omitempty"`
	HandleSubdomain string `json:"handleSubdomain"`
	LoginMethod     string `json:"loginMethod"`
	Name            string `json:"name,omitempty"`
	OrgId           string `json:"orgId"`
}
