package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatOrgDefsProfileView represents a profileView object
type NetworkHabitatOrgDefsProfileView struct {
	LexiconTypeID string `json:"$type"`
	AvatarUrl     string `json:"avatarUrl,omitempty"`
	Bio           string `json:"bio,omitempty"`
	Did           string `json:"did"`
	DisplayName   string `json:"displayName,omitempty"`
	Handle        string `json:"handle"`
}

// MarshalJSON sets $type to "network.habitat.org.defs#profileView" before encoding.
func (t NetworkHabitatOrgDefsProfileView) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.org.defs#profileView"
	type alias NetworkHabitatOrgDefsProfileView
	return json.Marshal(alias(t))
}
