package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatOrgGetProfilesParams represents the input parameters for network.habitat.org.getProfiles
type NetworkHabitatOrgGetProfilesParams struct {
	Dids []string `json:"dids"`
}

// NetworkHabitatOrgGetProfilesOutput represents the output for network.habitat.org.getProfiles
type NetworkHabitatOrgGetProfilesOutput struct {
	Profiles []NetworkHabitatOrgDefsProfileView `json:"profiles"`
}
