package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatOrgCreateInput represents the input for network.habitat.org.create
type NetworkHabitatOrgCreateInput struct {
	Domain        string `json:"domain"`
	AdminHandle   string `json:"admin_handle"`
	AdminPassword string `json:"admin_password"`
}

// NetworkHabitatOrgCreateOutput represents the output for network.habitat.org.create
type NetworkHabitatOrgCreateOutput struct {
	OrgID       string `json:"org_id"`
	AdminDID    string `json:"admin_did"`
	AdminHandle string `json:"admin_handle"`
}
