package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatOrgMintMemberIdentityInput represents the input for network.habitat.org.mintMemberIdentity
type NetworkHabitatOrgMintMemberIdentityInput struct {
	Handle string `json:"handle,omitempty"`
	Token  string `json:"token,omitempty"`
}

// NetworkHabitatOrgMintMemberIdentityOutput represents the output for network.habitat.org.mintMemberIdentity
type NetworkHabitatOrgMintMemberIdentityOutput struct {
	Did    string `json:"did"`
	Handle string `json:"handle"`
}
