package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatOrgMintMemberIdentityInput represents the input for network.habitat.org.mintMemberIdentity
type NetworkHabitatOrgMintMemberIdentityInput struct {
	OrgID    string `json:"org_id"`
	Handle   string `json:"handle"`
	Password string `json:"password"`
	Token    string `json:"token"`
}

// NetworkHabitatOrgMintMemberIdentityOutput represents the output for network.habitat.org.mintMemberIdentity
type NetworkHabitatOrgMintMemberIdentityOutput struct {
	Did    string `json:"did"`
	Handle string `json:"handle"`
}
