package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatPermissionsAddPermissionInput represents the input for network.habitat.permissions.addPermission
type NetworkHabitatPermissionsAddPermissionInput struct {
	Did     string `json:"did"`
	Lexicon string `json:"lexicon"`
}
