package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatPermissionsAddPermissionInput represents the input for network.habitat.permissions.addPermission
type NetworkHabitatPermissionsAddPermissionInput struct {
	Collection string        `json:"collection"`
	Grantees   []interface{} `json:"grantees"`
	Rkey       string        `json:"rkey,omitempty"`
}
