package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatPermissionsRemovePermissionInput represents the input for network.habitat.permissions.removePermission
type NetworkHabitatPermissionsRemovePermissionInput struct {
	Collection string        `json:"collection"`
	Grantees   []interface{} `json:"grantees"`
	Rkey       string        `json:"rkey,omitempty"`
}
