package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatPermissionsListPermissionsOutput represents the output for network.habitat.permissions.listPermissions
type NetworkHabitatPermissionsListPermissionsOutput struct {
	Permissions []NetworkHabitatPermissionsListPermissionsPermission `json:"permissions"`
}

// NetworkHabitatPermissionsListPermissionsPermission represents a permission object
type NetworkHabitatPermissionsListPermissionsPermission struct {
	LexiconTypeID string `json:"$type"`
	Collection    string `json:"collection"`
	Effect        string `json:"effect"`
	Grantee       string `json:"grantee"`
	Rkey          string `json:"rkey,omitempty"`
}

// MarshalJSON sets $type to "network.habitat.permissions.listPermissions#permission" before encoding.
func (t NetworkHabitatPermissionsListPermissionsPermission) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.permissions.listPermissions#permission"
	type alias NetworkHabitatPermissionsListPermissionsPermission
	return json.Marshal(alias(t))
}
