package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatPermissionsRemovePermissionInput represents the input for network.habitat.permissions.removePermission
type NetworkHabitatPermissionsRemovePermissionInput struct {
	Did     string `json:"did"`
	Lexicon string `json:"lexicon"`
}
