package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatPermissionsAddPermissionDidGrantee represents a didGrantee object
type NetworkHabitatPermissionsAddPermissionDidGrantee struct {
	Did string `json:"did"`
}

// NetworkHabitatPermissionsAddPermissionCliqueRef represents a cliqueRef object
type NetworkHabitatPermissionsAddPermissionCliqueRef struct {
	Uri string `json:"uri"`
}

// NetworkHabitatPermissionsAddPermissionInput represents the input for network.habitat.permissions.addPermission
type NetworkHabitatPermissionsAddPermissionInput struct {
	Collection string      `json:"collection"`
	Grantee    interface{} `json:"grantee"`
	Rkey       string      `json:"rkey,omitempty"`
}
