package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatPermissionsListPermissionsOutput represents the output for network.habitat.permissions.listPermissions
type NetworkHabitatPermissionsListPermissionsOutput struct {
}
