package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatPermissionsListPermissionsPermission represents a permission object
type NetworkHabitatPermissionsListPermissionsPermission struct {
	Collection string `json:"collection"`
	Effect     string `json:"effect"`
	Grantee    string `json:"grantee"`
	Rkey       string `json:"rkey,omitempty"`
}

// NetworkHabitatPermissionsListPermissionsOutput represents the output for network.habitat.permissions.listPermissions
type NetworkHabitatPermissionsListPermissionsOutput struct {
	Permissions []NetworkHabitatPermissionsListPermissionsPermission `json:"permissions"`
}
