package habitat

// Code generated by lexgen. DO NOT EDIT.

import "github.com/bluesky-social/indigo/atproto/atdata"

// NetworkHabitatPhoto represents a network.habitat.photo record
type NetworkHabitatPhoto struct {
	LexiconTypeID string      `json:"$type,const=network.habitat.photo"`
	CreatedAt     string      `json:"createdAt,omitempty"`
	Ref           atdata.Blob `json:"ref"`
}
