package habitat

// Code generated by lexgen. DO NOT EDIT.

import (
	"encoding/json"
	"github.com/bluesky-social/indigo/atproto/atdata"
)

// NetworkHabitatPhoto represents a network.habitat.photo record
type NetworkHabitatPhoto struct {
	LexiconTypeID string      `json:"$type"`
	CreatedAt     string      `json:"createdAt,omitempty"`
	Ref           atdata.Blob `json:"ref"`
}

// MarshalJSON sets $type to "network.habitat.photo" before encoding.
func (t NetworkHabitatPhoto) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.photo"
	type alias NetworkHabitatPhoto
	return json.Marshal(alias(t))
}
