package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatPhoto represents a network.habitat.photo record
type NetworkHabitatPhoto struct {
	CreatedAt string      `json:"createdAt,omitempty"`
	Ref       interface{} `json:"ref"`
}
