package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRelationshipWriteSpaceRelationInput represents the input for network.habitat.relationship.writeSpaceRelation
type NetworkHabitatRelationshipWriteSpaceRelationInput struct {
	Relation    string `json:"relation"`
	Space       string `json:"space"`
	Subject     string `json:"subject"`
	SubjectRole string `json:"subjectRole"`
}

// NetworkHabitatRelationshipWriteSpaceRelationOutput represents the output for network.habitat.relationship.writeSpaceRelation
type NetworkHabitatRelationshipWriteSpaceRelationOutput struct {
	Uri string `json:"uri"`
}
