package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRelationshipListInheritingSpacesParams represents the input parameters for network.habitat.relationship.listInheritingSpaces
type NetworkHabitatRelationshipListInheritingSpacesParams struct {
	Relation string `json:"relation,omitempty"`
	Space    string `json:"space"`
}

// NetworkHabitatRelationshipListInheritingSpacesOutput represents the output for network.habitat.relationship.listInheritingSpaces
type NetworkHabitatRelationshipListInheritingSpacesOutput struct {
	Spaces []string `json:"spaces"`
}
