package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRelationshipUserRelation represents a network.habitat.relationship.userRelation record
type NetworkHabitatRelationshipUserRelation struct {
	CreatedAt string                                    `json:"createdAt,omitempty"`
	Object    NetworkHabitatRelationshipDefsSpaceObject `json:"object"`
	Relation  string                                    `json:"relation"`
	Subject   NetworkHabitatRelationshipDefsUserSubject `json:"subject"`
}
