package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRelationshipDeleteRelationInput represents the input for network.habitat.relationship.deleteRelation
type NetworkHabitatRelationshipDeleteRelationInput struct {
	Uri string `json:"uri"`
}
