package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRelationshipSetUserRelationInput represents the input for network.habitat.relationship.setUserRelation
type NetworkHabitatRelationshipSetUserRelationInput struct {
	Relation string `json:"relation"`
	Space    string `json:"space"`
	Subject  string `json:"subject"`
}

// NetworkHabitatRelationshipSetUserRelationOutput represents the output for network.habitat.relationship.setUserRelation
type NetworkHabitatRelationshipSetUserRelationOutput struct {
	Uri string `json:"uri"`
}
