package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRelationshipSpaceRelation represents a network.habitat.relationship.spaceRelation record
type NetworkHabitatRelationshipSpaceRelation struct {
	CreatedAt string                                         `json:"createdAt,omitempty"`
	Object    NetworkHabitatRelationshipDefsSpaceObject      `json:"object"`
	Relation  string                                         `json:"relation"`
	Subject   NetworkHabitatRelationshipDefsSpaceRoleSubject `json:"subject"`
}
