package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRelationshipWriteUserRelationInput represents the input for network.habitat.relationship.writeUserRelation
type NetworkHabitatRelationshipWriteUserRelationInput struct {
	Relation string `json:"relation"`
	Space    string `json:"space"`
	Subject  string `json:"subject"`
}

// NetworkHabitatRelationshipWriteUserRelationOutput represents the output for network.habitat.relationship.writeUserRelation
type NetworkHabitatRelationshipWriteUserRelationOutput struct {
	Uri string `json:"uri"`
}
