package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatRelationshipSpaceRelation represents a network.habitat.relationship.spaceRelation record
type NetworkHabitatRelationshipSpaceRelation struct {
	LexiconTypeID string `json:"$type"`
	CreatedAt     string `json:"createdAt,omitempty"`
	Relation      string `json:"relation"`
	Subject       string `json:"subject"`
	SubjectRole   string `json:"subjectRole"`
}

// MarshalJSON sets $type to "network.habitat.relationship.spaceRelation" before encoding.
func (t NetworkHabitatRelationshipSpaceRelation) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.relationship.spaceRelation"
	type alias NetworkHabitatRelationshipSpaceRelation
	return json.Marshal(alias(t))
}
