package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRelationshipCheckSpaceRelationParams represents the input parameters for network.habitat.relationship.checkSpaceRelation
type NetworkHabitatRelationshipCheckSpaceRelationParams struct {
	Relation    string `json:"relation"`
	Space       string `json:"space"`
	Subject     string `json:"subject"`
	SubjectRole string `json:"subjectRole"`
}

// NetworkHabitatRelationshipCheckSpaceRelationOutput represents the output for network.habitat.relationship.checkSpaceRelation
type NetworkHabitatRelationshipCheckSpaceRelationOutput struct {
	Allowed bool `json:"allowed"`
}
