package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRelationshipDefsGroupObject represents a groupObject object
type NetworkHabitatRelationshipDefsGroupObject struct {
	Group string `json:"group"`
}

// NetworkHabitatRelationshipDefsGroupSubject represents a groupSubject object
type NetworkHabitatRelationshipDefsGroupSubject struct {
	Group string `json:"group"`
}

// NetworkHabitatRelationshipDefsOrgRoleSubject represents a orgRoleSubject object
type NetworkHabitatRelationshipDefsOrgRoleSubject struct {
	Org  string `json:"org"`
	Role string `json:"role"`
}

// NetworkHabitatRelationshipDefsSpaceObject represents a spaceObject object
type NetworkHabitatRelationshipDefsSpaceObject struct {
	Space string `json:"space"`
}

// NetworkHabitatRelationshipDefsSpaceRoleSubject represents a spaceRoleSubject object
type NetworkHabitatRelationshipDefsSpaceRoleSubject struct {
	Role  string `json:"role"`
	Space string `json:"space"`
}

// NetworkHabitatRelationshipDefsUserSubject represents a userSubject object
type NetworkHabitatRelationshipDefsUserSubject struct {
	Did string `json:"did"`
}
