package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRelationshipResolveRelationsParams represents the input parameters for network.habitat.relationship.resolveRelations
type NetworkHabitatRelationshipResolveRelationsParams struct {
	Relation string `json:"relation"`
	Space    string `json:"space"`
}

// NetworkHabitatRelationshipResolveRelationsOutput represents the output for network.habitat.relationship.resolveRelations
type NetworkHabitatRelationshipResolveRelationsOutput struct {
	Dids []string `json:"dids"`
}
