package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRelationshipDeleteTupleInput represents the input for network.habitat.relationship.deleteTuple
type NetworkHabitatRelationshipDeleteTupleInput struct {
	Uri string `json:"uri"`
}
