package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatRelationshipListRelationsParams represents the input parameters for network.habitat.relationship.listRelations
type NetworkHabitatRelationshipListRelationsParams struct {
	Relation    string `json:"relation,omitempty"`
	Space       string `json:"space"`
	SubjectDid  string `json:"subjectDid,omitempty"`
	SubjectType string `json:"subjectType,omitempty"`
}

// NetworkHabitatRelationshipListRelationsOutput represents the output for network.habitat.relationship.listRelations
type NetworkHabitatRelationshipListRelationsOutput struct {
	Relations []interface{} `json:"relations"`
}

// NetworkHabitatRelationshipListRelationsSpaceRelationView represents a spaceRelationView object
type NetworkHabitatRelationshipListRelationsSpaceRelationView struct {
	LexiconTypeID string `json:"$type"`
	Object        string `json:"object"`
	Relation      string `json:"relation"`
	Subject       string `json:"subject"`
	SubjectRole   string `json:"subjectRole"`
	Uri           string `json:"uri"`
}

// MarshalJSON sets $type to "network.habitat.relationship.listRelations#spaceRelationView" before encoding.
func (t NetworkHabitatRelationshipListRelationsSpaceRelationView) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.relationship.listRelations#spaceRelationView"
	type alias NetworkHabitatRelationshipListRelationsSpaceRelationView
	return json.Marshal(alias(t))
}

// NetworkHabitatRelationshipListRelationsUserRelationView represents a userRelationView object
type NetworkHabitatRelationshipListRelationsUserRelationView struct {
	LexiconTypeID string `json:"$type"`
	Object        string `json:"object"`
	Relation      string `json:"relation"`
	Subject       string `json:"subject"`
	Uri           string `json:"uri"`
}

// MarshalJSON sets $type to "network.habitat.relationship.listRelations#userRelationView" before encoding.
func (t NetworkHabitatRelationshipListRelationsUserRelationView) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.relationship.listRelations#userRelationView"
	type alias NetworkHabitatRelationshipListRelationsUserRelationView
	return json.Marshal(alias(t))
}
