package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRelationshipDeleteGroupInput represents the input for network.habitat.relationship.deleteGroup
type NetworkHabitatRelationshipDeleteGroupInput struct {
	Uri string `json:"uri"`
}
