package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRelationshipListObjectsParams represents the input parameters for network.habitat.relationship.listObjects
type NetworkHabitatRelationshipListObjectsParams struct {
	Did      string `json:"did"`
	Relation string `json:"relation"`
	Type     string `json:"type,omitempty"`
}

// NetworkHabitatRelationshipListObjectsOutput represents the output for network.habitat.relationship.listObjects
type NetworkHabitatRelationshipListObjectsOutput struct {
	Spaces []string `json:"spaces"`
}
