package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRelationshipSetSpaceRelationInput represents the input for network.habitat.relationship.setSpaceRelation
type NetworkHabitatRelationshipSetSpaceRelationInput struct {
	Relation    string `json:"relation"`
	Space       string `json:"space"`
	Subject     string `json:"subject"`
	SubjectRole string `json:"subjectRole"`
}

// NetworkHabitatRelationshipSetSpaceRelationOutput represents the output for network.habitat.relationship.setSpaceRelation
type NetworkHabitatRelationshipSetSpaceRelationOutput struct {
	Uri string `json:"uri"`
}
