package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRelationshipListGroupsGroupView represents a groupView object
type NetworkHabitatRelationshipListGroupsGroupView struct {
	CreatedAt   string `json:"createdAt,omitempty"`
	Description string `json:"description,omitempty"`
	Name        string `json:"name"`
	Uri         string `json:"uri"`
}

// NetworkHabitatRelationshipListGroupsParams represents the input parameters for network.habitat.relationship.listGroups
type NetworkHabitatRelationshipListGroupsParams struct {
	Space string `json:"space"`
}

// NetworkHabitatRelationshipListGroupsOutput represents the output for network.habitat.relationship.listGroups
type NetworkHabitatRelationshipListGroupsOutput struct {
	Groups []NetworkHabitatRelationshipListGroupsGroupView `json:"groups"`
}
