package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRelationshipWriteTupleInput represents the input for network.habitat.relationship.writeTuple
type NetworkHabitatRelationshipWriteTupleInput struct {
	Object   interface{} `json:"object"`
	Relation string      `json:"relation"`
	Subject  interface{} `json:"subject"`
}

// NetworkHabitatRelationshipWriteTupleOutput represents the output for network.habitat.relationship.writeTuple
type NetworkHabitatRelationshipWriteTupleOutput struct {
	Uri string `json:"uri"`
}
