package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRelationshipDefsSpaceObject represents a spaceObject object
type NetworkHabitatRelationshipDefsSpaceObject struct {
	Space string `json:"space"`
}

// NetworkHabitatRelationshipDefsSpaceRoleSubject represents a spaceRoleSubject object
type NetworkHabitatRelationshipDefsSpaceRoleSubject struct {
	Role  string `json:"role"`
	Space string `json:"space"`
}

// NetworkHabitatRelationshipDefsUserSubject represents a userSubject object
type NetworkHabitatRelationshipDefsUserSubject struct {
	Did string `json:"did"`
}
