package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRelationshipListRelationsParams represents the input parameters for network.habitat.relationship.listRelations
type NetworkHabitatRelationshipListRelationsParams struct {
	Object      string `json:"object,omitempty"`
	Relation    string `json:"relation,omitempty"`
	Space       string `json:"space"`
	SubjectDid  string `json:"subjectDid,omitempty"`
	SubjectType string `json:"subjectType,omitempty"`
}

// NetworkHabitatRelationshipListRelationsOutput represents the output for network.habitat.relationship.listRelations
type NetworkHabitatRelationshipListRelationsOutput struct {
	Relations []interface{} `json:"relations"`
}

// NetworkHabitatRelationshipListRelationsSpaceRelationView represents a spaceRelationView object
type NetworkHabitatRelationshipListRelationsSpaceRelationView struct {
	Object   NetworkHabitatRelationshipDefsSpaceObject      `json:"object"`
	Relation string                                         `json:"relation"`
	Subject  NetworkHabitatRelationshipDefsSpaceRoleSubject `json:"subject"`
	Uri      string                                         `json:"uri"`
}

// NetworkHabitatRelationshipListRelationsUserRelationView represents a userRelationView object
type NetworkHabitatRelationshipListRelationsUserRelationView struct {
	Object   NetworkHabitatRelationshipDefsSpaceObject `json:"object"`
	Relation string                                    `json:"relation"`
	Subject  NetworkHabitatRelationshipDefsUserSubject `json:"subject"`
	Uri      string                                    `json:"uri"`
}
