package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatRelationshipTuple represents a network.habitat.relationship.tuple record
type NetworkHabitatRelationshipTuple struct {
	LexiconTypeID string                                    `json:"$type"`
	CreatedAt     string                                    `json:"createdAt,omitempty"`
	Object        NetworkHabitatRelationshipDefsSpaceObject `json:"object"`
	Relation      string                                    `json:"relation"`
	Subject       interface{}                               `json:"subject"`
}

// MarshalJSON sets $type to "network.habitat.relationship.tuple" before encoding.
func (t NetworkHabitatRelationshipTuple) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.relationship.tuple"
	type alias NetworkHabitatRelationshipTuple
	return json.Marshal(alias(t))
}
