package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRelationshipTuple represents a network.habitat.relationship.tuple record
type NetworkHabitatRelationshipTuple struct {
	CreatedAt string                                    `json:"createdAt,omitempty"`
	Object    NetworkHabitatRelationshipDefsSpaceObject `json:"object"`
	Relation  string                                    `json:"relation"`
	Subject   interface{}                               `json:"subject"`
}
