package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatRelationshipListTuplesParams represents the input parameters for network.habitat.relationship.listTuples
type NetworkHabitatRelationshipListTuplesParams struct {
	Object      string `json:"object,omitempty"`
	Relation    string `json:"relation,omitempty"`
	Space       string `json:"space"`
	SubjectDid  string `json:"subjectDid,omitempty"`
	SubjectType string `json:"subjectType,omitempty"`
}

// NetworkHabitatRelationshipListTuplesOutput represents the output for network.habitat.relationship.listTuples
type NetworkHabitatRelationshipListTuplesOutput struct {
	Tuples []NetworkHabitatRelationshipListTuplesTupleView `json:"tuples"`
}

// NetworkHabitatRelationshipListTuplesTupleView represents a tupleView object
type NetworkHabitatRelationshipListTuplesTupleView struct {
	LexiconTypeID string                                    `json:"$type"`
	Object        NetworkHabitatRelationshipDefsSpaceObject `json:"object"`
	Relation      string                                    `json:"relation"`
	Subject       interface{}                               `json:"subject"`
	Uri           string                                    `json:"uri"`
}

// MarshalJSON sets $type to "network.habitat.relationship.listTuples#tupleView" before encoding.
func (t NetworkHabitatRelationshipListTuplesTupleView) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.relationship.listTuples#tupleView"
	type alias NetworkHabitatRelationshipListTuplesTupleView
	return json.Marshal(alias(t))
}
