package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRelationshipListSubjectsParams represents the input parameters for network.habitat.relationship.listSubjects
type NetworkHabitatRelationshipListSubjectsParams struct {
	Relation string `json:"relation"`
	Space    string `json:"space"`
}

// NetworkHabitatRelationshipListSubjectsOutput represents the output for network.habitat.relationship.listSubjects
type NetworkHabitatRelationshipListSubjectsOutput struct {
	Dids []string `json:"dids"`
}
