package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRelationshipCheckParams represents the input parameters for network.habitat.relationship.check
type NetworkHabitatRelationshipCheckParams struct {
	Did      string `json:"did"`
	Relation string `json:"relation"`
	Space    string `json:"space"`
}

// NetworkHabitatRelationshipCheckOutput represents the output for network.habitat.relationship.check
type NetworkHabitatRelationshipCheckOutput struct {
	Allowed bool `json:"allowed"`
}
