package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRelationshipGroup represents a network.habitat.relationship.group record
type NetworkHabitatRelationshipGroup struct {
	CreatedAt   string `json:"createdAt,omitempty"`
	Description string `json:"description,omitempty"`
	Name        string `json:"name"`
}
