package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRelationshipListRelatedSpacesParams represents the input parameters for network.habitat.relationship.listRelatedSpaces
type NetworkHabitatRelationshipListRelatedSpacesParams struct {
	Did      string `json:"did"`
	Relation string `json:"relation"`
	Type     string `json:"type,omitempty"`
}

// NetworkHabitatRelationshipListRelatedSpacesOutput represents the output for network.habitat.relationship.listRelatedSpaces
type NetworkHabitatRelationshipListRelatedSpacesOutput struct {
	Spaces []string `json:"spaces"`
}
