package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatRelationshipUserRelation represents a network.habitat.relationship.userRelation record
type NetworkHabitatRelationshipUserRelation struct {
	LexiconTypeID string `json:"$type"`
	CreatedAt     string `json:"createdAt,omitempty"`
	Object        string `json:"object"`
	Relation      string `json:"relation"`
	Subject       string `json:"subject"`
}

// MarshalJSON sets $type to "network.habitat.relationship.userRelation" before encoding.
func (t NetworkHabitatRelationshipUserRelation) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.relationship.userRelation"
	type alias NetworkHabitatRelationshipUserRelation
	return json.Marshal(alias(t))
}
