package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatRelationshipDefsSpaceObject represents a spaceObject object
type NetworkHabitatRelationshipDefsSpaceObject struct {
	LexiconTypeID string `json:"$type"`
	Space         string `json:"space"`
}

// MarshalJSON sets $type to "network.habitat.relationship.defs#spaceObject" before encoding.
func (t NetworkHabitatRelationshipDefsSpaceObject) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.relationship.defs#spaceObject"
	type alias NetworkHabitatRelationshipDefsSpaceObject
	return json.Marshal(alias(t))
}

// NetworkHabitatRelationshipDefsSpaceRoleSubject represents a spaceRoleSubject object
type NetworkHabitatRelationshipDefsSpaceRoleSubject struct {
	LexiconTypeID string `json:"$type"`
	Role          string `json:"role"`
	Space         string `json:"space"`
}

// MarshalJSON sets $type to "network.habitat.relationship.defs#spaceRoleSubject" before encoding.
func (t NetworkHabitatRelationshipDefsSpaceRoleSubject) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.relationship.defs#spaceRoleSubject"
	type alias NetworkHabitatRelationshipDefsSpaceRoleSubject
	return json.Marshal(alias(t))
}

// NetworkHabitatRelationshipDefsUserSubject represents a userSubject object
type NetworkHabitatRelationshipDefsUserSubject struct {
	LexiconTypeID string `json:"$type"`
	Did           string `json:"did"`
}

// MarshalJSON sets $type to "network.habitat.relationship.defs#userSubject" before encoding.
func (t NetworkHabitatRelationshipDefsUserSubject) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.relationship.defs#userSubject"
	type alias NetworkHabitatRelationshipDefsUserSubject
	return json.Marshal(alias(t))
}
