package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRelationshipCheckUserRelationParams represents the input parameters for network.habitat.relationship.checkUserRelation
type NetworkHabitatRelationshipCheckUserRelationParams struct {
	Relation string `json:"relation"`
	Space    string `json:"space"`
	Subject  string `json:"subject"`
}

// NetworkHabitatRelationshipCheckUserRelationOutput represents the output for network.habitat.relationship.checkUserRelation
type NetworkHabitatRelationshipCheckUserRelationOutput struct {
	Allowed bool `json:"allowed"`
}
