package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRelationshipResolveSpacesParams represents the input parameters for network.habitat.relationship.resolveSpaces
type NetworkHabitatRelationshipResolveSpacesParams struct {
	Relation string `json:"relation,omitempty"`
	Space    string `json:"space"`
}

// NetworkHabitatRelationshipResolveSpacesOutput represents the output for network.habitat.relationship.resolveSpaces
type NetworkHabitatRelationshipResolveSpacesOutput struct {
	Spaces []string `json:"spaces"`
}
