package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRelationshipCreateGroupInput represents the input for network.habitat.relationship.createGroup
type NetworkHabitatRelationshipCreateGroupInput struct {
	Description string `json:"description,omitempty"`
	Name        string `json:"name"`
	Space       string `json:"space"`
}

// NetworkHabitatRelationshipCreateGroupOutput represents the output for network.habitat.relationship.createGroup
type NetworkHabitatRelationshipCreateGroupOutput struct {
	Uri string `json:"uri"`
}
