package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRenderSchemaFieldSchema represents a fieldSchema object
type NetworkHabitatRenderSchemaFieldSchema struct {
	DisplayType string `json:"displayType"`
	Label       string `json:"label"`
	Optional    bool   `json:"optional,omitempty"`
	Path        string `json:"path"`
	Priority    string `json:"priority"`
}

// NetworkHabitatRenderSchema represents a network.habitat.render.schema record
type NetworkHabitatRenderSchema struct {
	Description   string                                  `json:"description,omitempty"`
	Fields        []NetworkHabitatRenderSchemaFieldSchema `json:"fields"`
	TargetLexicon string                                  `json:"targetLexicon"`
	Title         string                                  `json:"title"`
}
