package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatRenderSchemaFieldSchema represents a fieldSchema object
type NetworkHabitatRenderSchemaFieldSchema struct {
	LexiconTypeID string `json:"$type"`
	DisplayType   string `json:"displayType"`
	Label         string `json:"label"`
	Optional      bool   `json:"optional,omitempty"`
	Path          string `json:"path"`
	Priority      string `json:"priority"`
}

// MarshalJSON sets $type to "network.habitat.render.schema#fieldSchema" before encoding.
func (t NetworkHabitatRenderSchemaFieldSchema) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.render.schema#fieldSchema"
	type alias NetworkHabitatRenderSchemaFieldSchema
	return json.Marshal(alias(t))
}

// NetworkHabitatRenderSchema represents a network.habitat.render.schema record
type NetworkHabitatRenderSchema struct {
	LexiconTypeID string                                  `json:"$type"`
	Description   string                                  `json:"description,omitempty"`
	Fields        []NetworkHabitatRenderSchemaFieldSchema `json:"fields"`
	TargetLexicon string                                  `json:"targetLexicon"`
	Title         string                                  `json:"title"`
}

// MarshalJSON sets $type to "network.habitat.render.schema" before encoding.
func (t NetworkHabitatRenderSchema) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.render.schema"
	type alias NetworkHabitatRenderSchema
	return json.Marshal(alias(t))
}
