package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatRepoDescribeRepoCollectionMetadata represents a collectionMetadata object
type NetworkHabitatRepoDescribeRepoCollectionMetadata struct {
	LexiconTypeID string        `json:"$type"`
	Grantees      []interface{} `json:"grantees"`
	LastTouched   string        `json:"lastTouched"`
	Nsid          string        `json:"nsid"`
	RecordCount   int64         `json:"recordCount"`
}

// MarshalJSON sets $type to "network.habitat.repo.describeRepo#collectionMetadata" before encoding.
func (t NetworkHabitatRepoDescribeRepoCollectionMetadata) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.repo.describeRepo#collectionMetadata"
	type alias NetworkHabitatRepoDescribeRepoCollectionMetadata
	return json.Marshal(alias(t))
}

// NetworkHabitatRepoDescribeRepoOutput represents the output for network.habitat.repo.describeRepo
type NetworkHabitatRepoDescribeRepoOutput struct {
	Collections     []NetworkHabitatRepoDescribeRepoCollectionMetadata `json:"collections"`
	Did             string                                             `json:"did"`
	DidDoc          interface{}                                        `json:"didDoc"`
	Handle          string                                             `json:"handle"`
	HandleIsCorrect bool                                               `json:"handleIsCorrect"`
}
