package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRepoGetBlobParams represents the input parameters for network.habitat.repo.getBlob
type NetworkHabitatRepoGetBlobParams struct {
	Did string `json:"did"`
	Cid string `json:"cid"`
}
