package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRepoSearchRecordsParams represents the input parameters for network.habitat.repo.searchRecords
type NetworkHabitatRepoSearchRecordsParams struct {
	Collection string   `json:"collection,omitempty"`
	Query      string   `json:"query"`
	Subjects   []string `json:"subjects,omitempty"`
}

// NetworkHabitatRepoSearchRecordsOutput represents the output for network.habitat.repo.searchRecords
type NetworkHabitatRepoSearchRecordsOutput struct {
	Records []NetworkHabitatRepoSearchRecordsRecord `json:"records"`
}

// NetworkHabitatRepoSearchRecordsRecord represents a record object
type NetworkHabitatRepoSearchRecordsRecord struct {
	Uri   string      `json:"uri"`
	Value interface{} `json:"value"`
}
