package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRepoDeleteRecordInput represents the input for network.habitat.repo.deleteRecord
type NetworkHabitatRepoDeleteRecordInput struct {
	Collection string `json:"collection"`
	Repo       string `json:"repo"`
	Rkey       string `json:"rkey"`
}
