package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRepoPutRecordDidGrantee represents a didGrantee object
type NetworkHabitatRepoPutRecordDidGrantee struct {
	Did string `json:"did"`
}

// NetworkHabitatRepoPutRecordCliqueRef represents a cliqueRef object
type NetworkHabitatRepoPutRecordCliqueRef struct {
	Uri string `json:"uri"`
}

// NetworkHabitatRepoPutRecordInput represents the input for network.habitat.repo.putRecord
type NetworkHabitatRepoPutRecordInput struct {
	Collection string        `json:"collection"`
	Grantees   []interface{} `json:"grantees,omitempty"`
	Record     interface{}   `json:"record"`
	Repo       string        `json:"repo"`
	Rkey       string        `json:"rkey"`
	Validate   bool          `json:"validate,omitempty"`
}

// NetworkHabitatRepoPutRecordOutput represents the output for network.habitat.repo.putRecord
type NetworkHabitatRepoPutRecordOutput struct {
	Uri              string `json:"uri"`
	ValidationStatus string `json:"validationStatus,omitempty"`
}
