package habitat

// Code generated by lexgen. DO NOT EDIT.

import "github.com/bluesky-social/indigo/atproto/atdata"

// NetworkHabitatRepoUploadBlobOutput represents the output for network.habitat.repo.uploadBlob
type NetworkHabitatRepoUploadBlobOutput struct {
	Blob atdata.Blob `json:"blob"`
	Cid  string      `json:"cid,omitempty"`
}
