package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRepoListCollectionsCollectionMetadata represents a collectionMetadata object
type NetworkHabitatRepoListCollectionsCollectionMetadata struct {
	Grantees    []interface{} `json:"grantees"`
	LastTouched string        `json:"lastTouched"`
	Nsid        string        `json:"nsid"`
	RecordCount int64         `json:"recordCount"`
}

// NetworkHabitatRepoListCollectionsOutput represents the output for network.habitat.repo.listCollections
type NetworkHabitatRepoListCollectionsOutput struct {
	Collections []NetworkHabitatRepoListCollectionsCollectionMetadata `json:"collections"`
}
