package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRepoCreateGroupInput represents the input for network.habitat.repo.createGroup
type NetworkHabitatRepoCreateGroupInput struct {
	Description string   `json:"description,omitempty"`
	Members     []string `json:"members,omitempty"`
	Name        string   `json:"name"`
	Repo        string   `json:"repo"`
}

// NetworkHabitatRepoCreateGroupOutput represents the output for network.habitat.repo.createGroup
type NetworkHabitatRepoCreateGroupOutput struct {
	Uri string `json:"uri"`
}
