package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRepoGetRecordParams represents the input parameters for network.habitat.repo.getRecord
type NetworkHabitatRepoGetRecordParams struct {
	Repo       string `json:"repo"`
	Collection string `json:"collection"`
	Rkey       string `json:"rkey"`
}

// NetworkHabitatRepoGetRecordOutput represents the output for network.habitat.repo.getRecord
type NetworkHabitatRepoGetRecordOutput struct {
	Value interface{} `json:"value"`
	Uri   string      `json:"uri"`
}
