package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRepoCreateRecordInput represents the input for network.habitat.repo.createRecord
type NetworkHabitatRepoCreateRecordInput struct {
	Collection           string        `json:"collection"`
	CreateGranteesClique bool          `json:"createGranteesClique,omitempty"`
	Grantees             []interface{} `json:"grantees,omitempty"`
	Record               interface{}   `json:"record"`
	Repo                 string        `json:"repo"`
	Rkey                 string        `json:"rkey,omitempty"`
	Validate             bool          `json:"validate,omitempty"`
}

// NetworkHabitatRepoCreateRecordOutput represents the output for network.habitat.repo.createRecord
type NetworkHabitatRepoCreateRecordOutput struct {
	Clique           string `json:"clique,omitempty"`
	Uri              string `json:"uri"`
	ValidationStatus string `json:"validationStatus,omitempty"`
}
