package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRepoListGroupMembersParams represents the input parameters for network.habitat.repo.listGroupMembers
type NetworkHabitatRepoListGroupMembersParams struct {
	Repo string `json:"repo"`
	Rkey string `json:"rkey"`
}

// NetworkHabitatRepoListGroupMembersOutput represents the output for network.habitat.repo.listGroupMembers
type NetworkHabitatRepoListGroupMembersOutput struct {
	Members []string `json:"members"`
}
