package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatRepoListRecordsParams represents the input parameters for network.habitat.repo.listRecords
type NetworkHabitatRepoListRecordsParams struct {
	Collection         string   `json:"collection"`
	Cursor             string   `json:"cursor,omitempty"`
	IncludePermissions bool     `json:"includePermissions,omitempty"`
	Limit              int64    `json:"limit,omitempty"`
	Since              string   `json:"since,omitempty"`
	Subjects           []string `json:"subjects"`
}

// NetworkHabitatRepoListRecordsOutput represents the output for network.habitat.repo.listRecords
type NetworkHabitatRepoListRecordsOutput struct {
	Cursor  string                                `json:"cursor,omitempty"`
	Records []NetworkHabitatRepoListRecordsRecord `json:"records"`
}

// NetworkHabitatRepoListRecordsRecord represents a record object
type NetworkHabitatRepoListRecordsRecord struct {
	LexiconTypeID string        `json:"$type"`
	Permissions   []interface{} `json:"permissions,omitempty"`
	Uri           string        `json:"uri"`
	Value         interface{}   `json:"value"`
}

// MarshalJSON sets $type to "network.habitat.repo.listRecords#record" before encoding.
func (t NetworkHabitatRepoListRecordsRecord) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.repo.listRecords#record"
	type alias NetworkHabitatRepoListRecordsRecord
	return json.Marshal(alias(t))
}
