package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRepoEditGroupInput represents the input for network.habitat.repo.editGroup
type NetworkHabitatRepoEditGroupInput struct {
	AddMembers    []string `json:"addMembers,omitempty"`
	Description   string   `json:"description,omitempty"`
	Name          string   `json:"name,omitempty"`
	RemoveMembers []string `json:"removeMembers,omitempty"`
	Repo          string   `json:"repo"`
	Rkey          string   `json:"rkey"`
}

// NetworkHabitatRepoEditGroupOutput represents the output for network.habitat.repo.editGroup
type NetworkHabitatRepoEditGroupOutput struct {
	Uri string `json:"uri"`
}
