package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRepoDescribeRepoCollectionMetadata represents a collectionMetadata object
type NetworkHabitatRepoDescribeRepoCollectionMetadata struct {
	Grantees    []interface{} `json:"grantees"`
	LastTouched string        `json:"lastTouched"`
	Nsid        string        `json:"nsid"`
	RecordCount int64         `json:"recordCount"`
}

// NetworkHabitatRepoDescribeRepoOutput represents the output for network.habitat.repo.describeRepo
type NetworkHabitatRepoDescribeRepoOutput struct {
	Collections     []NetworkHabitatRepoDescribeRepoCollectionMetadata `json:"collections"`
	Did             string                                             `json:"did"`
	DidDoc          interface{}                                        `json:"didDoc"`
	Handle          string                                             `json:"handle"`
	HandleIsCorrect bool                                               `json:"handleIsCorrect"`
}
