package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSearchRemoveCollectionInput represents the input for network.habitat.search.removeCollection
type NetworkHabitatSearchRemoveCollectionInput struct {
	Collection string `json:"collection"`
	Org        string `json:"org"`
}
