package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatSearchListCollectionsCollection represents a collection object
type NetworkHabitatSearchListCollectionsCollection struct {
	LexiconTypeID    string   `json:"$type"`
	Collection       string   `json:"collection"`
	CrawlableFields  []string `json:"crawlableFields,omitempty"`
	FilterableFields []string `json:"filterableFields,omitempty"`
}

// MarshalJSON sets $type to "network.habitat.search.listCollections#collection" before encoding.
func (t NetworkHabitatSearchListCollectionsCollection) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.search.listCollections#collection"
	type alias NetworkHabitatSearchListCollectionsCollection
	return json.Marshal(alias(t))
}

// NetworkHabitatSearchListCollectionsParams represents the input parameters for network.habitat.search.listCollections
type NetworkHabitatSearchListCollectionsParams struct {
	Org string `json:"org"`
}

// NetworkHabitatSearchListCollectionsOutput represents the output for network.habitat.search.listCollections
type NetworkHabitatSearchListCollectionsOutput struct {
	Collections []NetworkHabitatSearchListCollectionsCollection `json:"collections"`
	Defaults    []string                                        `json:"defaults"`
}
