package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSearchListCollectionsParams represents the input parameters for network.habitat.search.listCollections
type NetworkHabitatSearchListCollectionsParams struct {
	Org string `json:"org"`
}

// NetworkHabitatSearchListCollectionsOutput represents the output for network.habitat.search.listCollections
type NetworkHabitatSearchListCollectionsOutput struct {
	Collections []string `json:"collections"`
	Defaults    []string `json:"defaults"`
}
