package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatSearchConfig represents a network.habitat.search.config record
type NetworkHabitatSearchConfig struct {
	LexiconTypeID string `json:"$type"`
	UpdatedAt     string `json:"updatedAt"`
}

// MarshalJSON sets $type to "network.habitat.search.config" before encoding.
func (t NetworkHabitatSearchConfig) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.search.config"
	type alias NetworkHabitatSearchConfig
	return json.Marshal(alias(t))
}
