package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSearchQueryParams represents the input parameters for network.habitat.search.query
type NetworkHabitatSearchQueryParams struct {
	Cursor string `json:"cursor,omitempty"`
	Limit  int64  `json:"limit,omitempty"`
	Q      string `json:"q"`
}

// NetworkHabitatSearchQueryOutput represents the output for network.habitat.search.query
type NetworkHabitatSearchQueryOutput struct {
	Cursor  string                                `json:"cursor,omitempty"`
	Results []NetworkHabitatSearchQueryResultView `json:"results"`
}

// NetworkHabitatSearchQueryResultView represents a resultView object
type NetworkHabitatSearchQueryResultView struct {
	Rank       int64  `json:"rank,omitempty"`
	RecordType string `json:"recordType"`
	Snippet    string `json:"snippet,omitempty"`
	SpaceUri   string `json:"spaceUri"`
	Uri        string `json:"uri"`
}
