package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSearchAddCollectionInput represents the input for network.habitat.search.addCollection
type NetworkHabitatSearchAddCollectionInput struct {
	Collection       string   `json:"collection"`
	CrawlableFields  []string `json:"crawlableFields,omitempty"`
	FilterableFields []string `json:"filterableFields,omitempty"`
	Org              string   `json:"org"`
}
