package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSimplespaceDefsAllowList represents a allowList object
type NetworkHabitatSimplespaceDefsAllowList struct {
	Allowed []string `json:"allowed"`
}

// NetworkHabitatSimplespaceDefsOpen represents a open object
type NetworkHabitatSimplespaceDefsOpen struct {
}

// NetworkHabitatSimplespaceDefsSpaceConfig represents a spaceConfig object
type NetworkHabitatSimplespaceDefsSpaceConfig struct {
	AppAccess   interface{} `json:"appAccess"`
	ManagingApp string      `json:"managingApp,omitempty"`
	Policy      string      `json:"policy"`
}
