package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSimplespaceCheckUserAccessParams represents the input parameters for network.habitat.simplespace.checkUserAccess
type NetworkHabitatSimplespaceCheckUserAccessParams struct {
	ClientId string `json:"clientId,omitempty"`
	Space    string `json:"space"`
	User     string `json:"user"`
}

// NetworkHabitatSimplespaceCheckUserAccessOutput represents the output for network.habitat.simplespace.checkUserAccess
type NetworkHabitatSimplespaceCheckUserAccessOutput struct {
	Authorized bool `json:"authorized"`
}
