package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSimplespaceAddMemberInput represents the input for network.habitat.simplespace.addMember
type NetworkHabitatSimplespaceAddMemberInput struct {
	Did   string `json:"did"`
	Space string `json:"space"`
}
