package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatSimplespaceListMembersParams represents the input parameters for network.habitat.simplespace.listMembers
type NetworkHabitatSimplespaceListMembersParams struct {
	Cursor string `json:"cursor,omitempty"`
	Limit  int64  `json:"limit,omitempty"`
	Space  string `json:"space"`
}

// NetworkHabitatSimplespaceListMembersOutput represents the output for network.habitat.simplespace.listMembers
type NetworkHabitatSimplespaceListMembersOutput struct {
	Cursor  string                                       `json:"cursor,omitempty"`
	Members []NetworkHabitatSimplespaceListMembersMember `json:"members"`
}

// NetworkHabitatSimplespaceListMembersMember represents a member object
type NetworkHabitatSimplespaceListMembersMember struct {
	LexiconTypeID string `json:"$type"`
	Did           string `json:"did"`
}

// MarshalJSON sets $type to "network.habitat.simplespace.listMembers#member" before encoding.
func (t NetworkHabitatSimplespaceListMembersMember) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.simplespace.listMembers#member"
	type alias NetworkHabitatSimplespaceListMembersMember
	return json.Marshal(alias(t))
}
