package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSimplespaceCreateSpaceInput represents the input for network.habitat.simplespace.createSpace
type NetworkHabitatSimplespaceCreateSpaceInput struct {
	Config *NetworkHabitatSimplespaceDefsSpaceConfig `json:"config,omitempty"`
	Did    string                                    `json:"did"`
	Skey   string                                    `json:"skey,omitempty"`
	Type   string                                    `json:"type"`
}

// NetworkHabitatSimplespaceCreateSpaceOutput represents the output for network.habitat.simplespace.createSpace
type NetworkHabitatSimplespaceCreateSpaceOutput struct {
	Uri string `json:"uri"`
}
