package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSimplespaceRemoveMemberInput represents the input for network.habitat.simplespace.removeMember
type NetworkHabitatSimplespaceRemoveMemberInput struct {
	Did   string `json:"did"`
	Space string `json:"space"`
}
