package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSimplespaceDeleteSpaceInput represents the input for network.habitat.simplespace.deleteSpace
type NetworkHabitatSimplespaceDeleteSpaceInput struct {
	Space string `json:"space"`
}
