package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatSimplespaceDefsAllowList represents a allowList object
type NetworkHabitatSimplespaceDefsAllowList struct {
	LexiconTypeID string   `json:"$type"`
	Allowed       []string `json:"allowed"`
}

// MarshalJSON sets $type to "network.habitat.simplespace.defs#allowList" before encoding.
func (t NetworkHabitatSimplespaceDefsAllowList) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.simplespace.defs#allowList"
	type alias NetworkHabitatSimplespaceDefsAllowList
	return json.Marshal(alias(t))
}

// NetworkHabitatSimplespaceDefsOpen represents a open object
type NetworkHabitatSimplespaceDefsOpen struct {
	LexiconTypeID string `json:"$type"`
}

// MarshalJSON sets $type to "network.habitat.simplespace.defs#open" before encoding.
func (t NetworkHabitatSimplespaceDefsOpen) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.simplespace.defs#open"
	type alias NetworkHabitatSimplespaceDefsOpen
	return json.Marshal(alias(t))
}

// NetworkHabitatSimplespaceDefsSpaceConfig represents a spaceConfig object
type NetworkHabitatSimplespaceDefsSpaceConfig struct {
	LexiconTypeID string      `json:"$type"`
	AppAccess     interface{} `json:"appAccess"`
	ManagingApp   string      `json:"managingApp,omitempty"`
	Policy        string      `json:"policy"`
}

// MarshalJSON sets $type to "network.habitat.simplespace.defs#spaceConfig" before encoding.
func (t NetworkHabitatSimplespaceDefsSpaceConfig) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.simplespace.defs#spaceConfig"
	type alias NetworkHabitatSimplespaceDefsSpaceConfig
	return json.Marshal(alias(t))
}
