package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSimplespaceListMembersParams represents the input parameters for network.habitat.simplespace.listMembers
type NetworkHabitatSimplespaceListMembersParams struct {
	Cursor string `json:"cursor,omitempty"`
	Limit  int64  `json:"limit,omitempty"`
	Space  string `json:"space"`
}

// NetworkHabitatSimplespaceListMembersOutput represents the output for network.habitat.simplespace.listMembers
type NetworkHabitatSimplespaceListMembersOutput struct {
	Cursor  string                                       `json:"cursor,omitempty"`
	Members []NetworkHabitatSimplespaceListMembersMember `json:"members"`
}

// NetworkHabitatSimplespaceListMembersMember represents a member object
type NetworkHabitatSimplespaceListMembersMember struct {
	Did string `json:"did"`
}
