package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSpaceCreateRecordInput represents the input for network.habitat.space.createRecord
type NetworkHabitatSpaceCreateRecordInput struct {
	Collection string      `json:"collection"`
	Record     interface{} `json:"record"`
	Repo       string      `json:"repo"`
	Rkey       string      `json:"rkey,omitempty"`
	Space      string      `json:"space"`
	Validate   bool        `json:"validate,omitempty"`
}

// NetworkHabitatSpaceCreateRecordOutput represents the output for network.habitat.space.createRecord
type NetworkHabitatSpaceCreateRecordOutput struct {
	Cid              string `json:"cid"`
	Uri              string `json:"uri"`
	ValidationStatus string `json:"validationStatus,omitempty"`
}
