package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSpaceGetRepoOplogParams represents the input parameters for network.habitat.space.getRepoOplog
type NetworkHabitatSpaceGetRepoOplogParams struct {
	Limit int64  `json:"limit,omitempty"`
	Repo  string `json:"repo"`
	Since string `json:"since,omitempty"`
	Space string `json:"space"`
}

// NetworkHabitatSpaceGetRepoOplogOutput represents the output for network.habitat.space.getRepoOplog
type NetworkHabitatSpaceGetRepoOplogOutput struct {
	Cursor  string                                  `json:"cursor,omitempty"`
	Records []NetworkHabitatSpaceGetRepoOplogRecord `json:"records"`
}

// NetworkHabitatSpaceGetRepoOplogRecord represents a record object
type NetworkHabitatSpaceGetRepoOplogRecord struct {
	Collection string      `json:"collection"`
	Rev        string      `json:"rev"`
	Rkey       string      `json:"rkey"`
	Value      interface{} `json:"value"`
}
