package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSpaceRemoveAppAccessInput represents the input for network.habitat.space.removeAppAccess
type NetworkHabitatSpaceRemoveAppAccessInput struct {
	ClientId string `json:"clientId"`
	Space    string `json:"space"`
}

// NetworkHabitatSpaceRemoveAppAccessOutput represents the output for network.habitat.space.removeAppAccess
type NetworkHabitatSpaceRemoveAppAccessOutput struct {
}
