package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSpaceGetRepoParams represents the input parameters for network.habitat.space.getRepo
type NetworkHabitatSpaceGetRepoParams struct {
	ExcludeValues bool   `json:"excludeValues,omitempty"`
	Repo          string `json:"repo"`
	Space         string `json:"space"`
}
