package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatSpaceApplyWritesCreate represents a create object
type NetworkHabitatSpaceApplyWritesCreate struct {
	LexiconTypeID string      `json:"$type"`
	Collection    string      `json:"collection"`
	Rkey          string      `json:"rkey,omitempty"`
	Value         interface{} `json:"value"`
}

// MarshalJSON sets $type to "network.habitat.space.applyWrites#create" before encoding.
func (t NetworkHabitatSpaceApplyWritesCreate) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.space.applyWrites#create"
	type alias NetworkHabitatSpaceApplyWritesCreate
	return json.Marshal(alias(t))
}

// NetworkHabitatSpaceApplyWritesCreateResult represents a createResult object
type NetworkHabitatSpaceApplyWritesCreateResult struct {
	LexiconTypeID    string `json:"$type"`
	Cid              string `json:"cid"`
	Uri              string `json:"uri"`
	ValidationStatus string `json:"validationStatus,omitempty"`
}

// MarshalJSON sets $type to "network.habitat.space.applyWrites#createResult" before encoding.
func (t NetworkHabitatSpaceApplyWritesCreateResult) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.space.applyWrites#createResult"
	type alias NetworkHabitatSpaceApplyWritesCreateResult
	return json.Marshal(alias(t))
}

// NetworkHabitatSpaceApplyWritesDelete represents a delete object
type NetworkHabitatSpaceApplyWritesDelete struct {
	LexiconTypeID string `json:"$type"`
	Collection    string `json:"collection"`
	Rkey          string `json:"rkey"`
}

// MarshalJSON sets $type to "network.habitat.space.applyWrites#delete" before encoding.
func (t NetworkHabitatSpaceApplyWritesDelete) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.space.applyWrites#delete"
	type alias NetworkHabitatSpaceApplyWritesDelete
	return json.Marshal(alias(t))
}

// NetworkHabitatSpaceApplyWritesDeleteResult represents a deleteResult object
type NetworkHabitatSpaceApplyWritesDeleteResult struct {
	LexiconTypeID string `json:"$type"`
}

// MarshalJSON sets $type to "network.habitat.space.applyWrites#deleteResult" before encoding.
func (t NetworkHabitatSpaceApplyWritesDeleteResult) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.space.applyWrites#deleteResult"
	type alias NetworkHabitatSpaceApplyWritesDeleteResult
	return json.Marshal(alias(t))
}

// NetworkHabitatSpaceApplyWritesInput represents the input for network.habitat.space.applyWrites
type NetworkHabitatSpaceApplyWritesInput struct {
	Repo     string        `json:"repo"`
	Space    string        `json:"space"`
	Validate bool          `json:"validate,omitempty"`
	Writes   []interface{} `json:"writes"`
}

// NetworkHabitatSpaceApplyWritesOutput represents the output for network.habitat.space.applyWrites
type NetworkHabitatSpaceApplyWritesOutput struct {
	Results []interface{} `json:"results,omitempty"`
}

// NetworkHabitatSpaceApplyWritesUpdate represents a update object
type NetworkHabitatSpaceApplyWritesUpdate struct {
	LexiconTypeID string      `json:"$type"`
	Collection    string      `json:"collection"`
	Rkey          string      `json:"rkey"`
	Value         interface{} `json:"value"`
}

// MarshalJSON sets $type to "network.habitat.space.applyWrites#update" before encoding.
func (t NetworkHabitatSpaceApplyWritesUpdate) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.space.applyWrites#update"
	type alias NetworkHabitatSpaceApplyWritesUpdate
	return json.Marshal(alias(t))
}

// NetworkHabitatSpaceApplyWritesUpdateResult represents a updateResult object
type NetworkHabitatSpaceApplyWritesUpdateResult struct {
	LexiconTypeID    string `json:"$type"`
	Cid              string `json:"cid"`
	Uri              string `json:"uri"`
	ValidationStatus string `json:"validationStatus,omitempty"`
}

// MarshalJSON sets $type to "network.habitat.space.applyWrites#updateResult" before encoding.
func (t NetworkHabitatSpaceApplyWritesUpdateResult) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.space.applyWrites#updateResult"
	type alias NetworkHabitatSpaceApplyWritesUpdateResult
	return json.Marshal(alias(t))
}
