package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSpaceGetBlobParams represents the input parameters for network.habitat.space.getBlob
type NetworkHabitatSpaceGetBlobParams struct {
	Cid   string `json:"cid"`
	Space string `json:"space"`
}
