package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSpaceRemoveMemberInput represents the input for network.habitat.space.removeMember
type NetworkHabitatSpaceRemoveMemberInput struct {
	Did   string `json:"did"`
	Space string `json:"space"`
}
