package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSpaceListRepoOpsParams represents the input parameters for network.habitat.space.listRepoOps
type NetworkHabitatSpaceListRepoOpsParams struct {
	ExcludeValues bool   `json:"excludeValues,omitempty"`
	Limit         int64  `json:"limit,omitempty"`
	Repo          string `json:"repo"`
	Since         string `json:"since,omitempty"`
	Space         string `json:"space"`
}

// NetworkHabitatSpaceListRepoOpsOutput represents the output for network.habitat.space.listRepoOps
type NetworkHabitatSpaceListRepoOpsOutput struct {
	Commit NetworkHabitatSpaceDefsSignedCommit     `json:"commit,omitempty"`
	Cursor string                                  `json:"cursor,omitempty"`
	Ops    []NetworkHabitatSpaceListRepoOpsOpEntry `json:"ops"`
}

// NetworkHabitatSpaceListRepoOpsOpEntry represents a opEntry object
type NetworkHabitatSpaceListRepoOpsOpEntry struct {
	Cid        string      `json:"cid"`
	Collection string      `json:"collection"`
	Prev       string      `json:"prev"`
	Rev        string      `json:"rev"`
	Rkey       string      `json:"rkey"`
	Value      interface{} `json:"value,omitempty"`
}
