package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSpaceNotifyCredentialRevokedInput represents the input for network.habitat.space.notifyCredentialRevoked
type NetworkHabitatSpaceNotifyCredentialRevokedInput struct {
	Jtis  []string `json:"jtis"`
	Space string   `json:"space"`
}
