package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSpacePutRecordInput represents the input for network.habitat.space.putRecord
type NetworkHabitatSpacePutRecordInput struct {
	Collection string      `json:"collection"`
	Record     interface{} `json:"record"`
	Rkey       string      `json:"rkey"`
	Space      string      `json:"space,omitempty"`
}

// NetworkHabitatSpacePutRecordOutput represents the output for network.habitat.space.putRecord
type NetworkHabitatSpacePutRecordOutput struct {
	Uri string `json:"uri"`
}
