package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSpaceNotifyCredentialRevokedInput represents the input for network.habitat.space.notifyCredentialRevoked
type NetworkHabitatSpaceNotifyCredentialRevokedInput struct {
	Credentials []string `json:"credentials"`
	Space       string   `json:"space"`
}
