package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSpaceCreateSpaceInput represents the input for network.habitat.space.createSpace
type NetworkHabitatSpaceCreateSpaceInput struct {
	Skey string `json:"skey,omitempty"`
	Type string `json:"type"`
}

// NetworkHabitatSpaceCreateSpaceOutput represents the output for network.habitat.space.createSpace
type NetworkHabitatSpaceCreateSpaceOutput struct {
	Uri string `json:"uri"`
}
