package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSpaceListReposParams represents the input parameters for network.habitat.space.listRepos
type NetworkHabitatSpaceListReposParams struct {
	Cursor string `json:"cursor,omitempty"`
	Limit  int64  `json:"limit,omitempty"`
	Space  string `json:"space"`
}

// NetworkHabitatSpaceListReposOutput represents the output for network.habitat.space.listRepos
type NetworkHabitatSpaceListReposOutput struct {
	Cursor string                             `json:"cursor,omitempty"`
	Repos  []NetworkHabitatSpaceListReposRepo `json:"repos"`
}

// NetworkHabitatSpaceListReposRepo represents a repo object
type NetworkHabitatSpaceListReposRepo struct {
	Did  string      `json:"did"`
	Hash interface{} `json:"hash,omitempty"`
	Rev  string      `json:"rev,omitempty"`
}
