package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSpaceGetSpaceCredentialInput represents the input for network.habitat.space.getSpaceCredential
type NetworkHabitatSpaceGetSpaceCredentialInput struct {
	ClientAttestation string `json:"clientAttestation,omitempty"`
	Space             string `json:"space"`
}

// NetworkHabitatSpaceGetSpaceCredentialOutput represents the output for network.habitat.space.getSpaceCredential
type NetworkHabitatSpaceGetSpaceCredentialOutput struct {
	Credential string `json:"credential"`
}
