package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSpaceNotifyWriteInput represents the input for network.habitat.space.notifyWrite
type NetworkHabitatSpaceNotifyWriteInput struct {
	Hash  interface{} `json:"hash"`
	Repo  string      `json:"repo"`
	Rev   string      `json:"rev"`
	Space string      `json:"space"`
}
