package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatSpaceListSpacesParams represents the input parameters for network.habitat.space.listSpaces
type NetworkHabitatSpaceListSpacesParams struct {
	Cursor string `json:"cursor,omitempty"`
	Did    string `json:"did,omitempty"`
	Limit  int64  `json:"limit,omitempty"`
	Type   string `json:"type,omitempty"`
}

// NetworkHabitatSpaceListSpacesOutput represents the output for network.habitat.space.listSpaces
type NetworkHabitatSpaceListSpacesOutput struct {
	Cursor string                                   `json:"cursor,omitempty"`
	Spaces []NetworkHabitatSpaceListSpacesSpaceView `json:"spaces"`
}

// NetworkHabitatSpaceListSpacesSpaceView represents a spaceView object
type NetworkHabitatSpaceListSpacesSpaceView struct {
	LexiconTypeID string `json:"$type"`
	IsOwner       bool   `json:"isOwner"`
	Uri           string `json:"uri"`
}

// MarshalJSON sets $type to "network.habitat.space.listSpaces#spaceView" before encoding.
func (t NetworkHabitatSpaceListSpacesSpaceView) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.space.listSpaces#spaceView"
	type alias NetworkHabitatSpaceListSpacesSpaceView
	return json.Marshal(alias(t))
}
