package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatSpaceListRecordsParams represents the input parameters for network.habitat.space.listRecords
type NetworkHabitatSpaceListRecordsParams struct {
	Collection    string `json:"collection,omitempty"`
	Cursor        string `json:"cursor,omitempty"`
	ExcludeValues bool   `json:"excludeValues,omitempty"`
	Limit         int64  `json:"limit,omitempty"`
	Repo          string `json:"repo"`
	Reverse       bool   `json:"reverse,omitempty"`
	Space         string `json:"space"`
}

// NetworkHabitatSpaceListRecordsOutput represents the output for network.habitat.space.listRecords
type NetworkHabitatSpaceListRecordsOutput struct {
	Cursor  string                                 `json:"cursor,omitempty"`
	Records []NetworkHabitatSpaceListRecordsRecord `json:"records"`
}

// NetworkHabitatSpaceListRecordsRecord represents a record object
type NetworkHabitatSpaceListRecordsRecord struct {
	LexiconTypeID string      `json:"$type"`
	Cid           string      `json:"cid"`
	Collection    string      `json:"collection"`
	Rkey          string      `json:"rkey"`
	Value         interface{} `json:"value,omitempty"`
}

// MarshalJSON sets $type to "network.habitat.space.listRecords#record" before encoding.
func (t NetworkHabitatSpaceListRecordsRecord) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.space.listRecords#record"
	type alias NetworkHabitatSpaceListRecordsRecord
	return json.Marshal(alias(t))
}
