package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSpaceNotifySpaceDeletedInput represents the input for network.habitat.space.notifySpaceDeleted
type NetworkHabitatSpaceNotifySpaceDeletedInput struct {
	Space string `json:"space"`
}
