package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSpaceDeleteSpaceInput represents the input for network.habitat.space.deleteSpace
type NetworkHabitatSpaceDeleteSpaceInput struct {
	Space string `json:"space"`
}
