package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSpaceAddAppAccessInput represents the input for network.habitat.space.addAppAccess
type NetworkHabitatSpaceAddAppAccessInput struct {
	ClientId string `json:"clientId"`
	Space    string `json:"space"`
}

// NetworkHabitatSpaceAddAppAccessOutput represents the output for network.habitat.space.addAppAccess
type NetworkHabitatSpaceAddAppAccessOutput struct {
	Uri string `json:"uri"`
}
