package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatSpaceSearchRecordsParams represents the input parameters for network.habitat.space.searchRecords
type NetworkHabitatSpaceSearchRecordsParams struct {
	Collection []string `json:"collection,omitempty"`
	Cursor     string   `json:"cursor,omitempty"`
	Limit      int64    `json:"limit,omitempty"`
	Org        string   `json:"org,omitempty"`
	Q          string   `json:"q"`
	Repo       string   `json:"repo,omitempty"`
	Space      string   `json:"space,omitempty"`
}

// NetworkHabitatSpaceSearchRecordsOutput represents the output for network.habitat.space.searchRecords
type NetworkHabitatSpaceSearchRecordsOutput struct {
	Cursor  string                                   `json:"cursor,omitempty"`
	Records []NetworkHabitatSpaceSearchRecordsRecord `json:"records"`
}

// NetworkHabitatSpaceSearchRecordsRecord represents a record object
type NetworkHabitatSpaceSearchRecordsRecord struct {
	LexiconTypeID string      `json:"$type"`
	Cid           string      `json:"cid"`
	Snippet       string      `json:"snippet,omitempty"`
	Space         string      `json:"space"`
	Uri           string      `json:"uri"`
	Value         interface{} `json:"value"`
}

// MarshalJSON sets $type to "network.habitat.space.searchRecords#record" before encoding.
func (t NetworkHabitatSpaceSearchRecordsRecord) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.space.searchRecords#record"
	type alias NetworkHabitatSpaceSearchRecordsRecord
	return json.Marshal(alias(t))
}
