package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSpaceAddMemberInput represents the input for network.habitat.space.addMember
type NetworkHabitatSpaceAddMemberInput struct {
	Did   string `json:"did"`
	Space string `json:"space"`
}
