package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSpaceGetMembersParams represents the input parameters for network.habitat.space.getMembers
type NetworkHabitatSpaceGetMembersParams struct {
	Space string `json:"space"`
}

// NetworkHabitatSpaceGetMembersOutput represents the output for network.habitat.space.getMembers
type NetworkHabitatSpaceGetMembersOutput struct {
	Members []NetworkHabitatSpaceGetMembersMember `json:"members"`
}

// NetworkHabitatSpaceGetMembersMember represents a member object
type NetworkHabitatSpaceGetMembersMember struct {
	Access  string `json:"access,omitempty"`
	AddedAt string `json:"addedAt,omitempty"`
	Did     string `json:"did"`
}
