package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSpaceGetDelegationTokenParams represents the input parameters for network.habitat.space.getDelegationToken
type NetworkHabitatSpaceGetDelegationTokenParams struct {
	Space string `json:"space"`
}

// NetworkHabitatSpaceGetDelegationTokenOutput represents the output for network.habitat.space.getDelegationToken
type NetworkHabitatSpaceGetDelegationTokenOutput struct {
	Token string `json:"token"`
}
