package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSpaceListSpacesParams represents the input parameters for network.habitat.space.listSpaces
type NetworkHabitatSpaceListSpacesParams struct {
	Cursor string `json:"cursor,omitempty"`
	Did    string `json:"did,omitempty"`
	Limit  int64  `json:"limit,omitempty"`
	Type   string `json:"type,omitempty"`
}

// NetworkHabitatSpaceListSpacesOutput represents the output for network.habitat.space.listSpaces
type NetworkHabitatSpaceListSpacesOutput struct {
	Cursor string                                   `json:"cursor,omitempty"`
	Spaces []NetworkHabitatSpaceListSpacesSpaceView `json:"spaces"`
}

// NetworkHabitatSpaceListSpacesSpaceView represents a spaceView object
type NetworkHabitatSpaceListSpacesSpaceView struct {
	MemberCount int64  `json:"memberCount,omitempty"`
	Skey        string `json:"skey,omitempty"`
	Type        string `json:"type"`
	Uri         string `json:"uri"`
}
