package habitat

// Code generated by lexgen. DO NOT EDIT.

import (
	"encoding/json"
	"github.com/bluesky-social/indigo/atproto/atdata"
)

// NetworkHabitatSpaceListReposParams represents the input parameters for network.habitat.space.listRepos
type NetworkHabitatSpaceListReposParams struct {
	Cursor string `json:"cursor,omitempty"`
	Limit  int64  `json:"limit,omitempty"`
	Space  string `json:"space"`
}

// NetworkHabitatSpaceListReposOutput represents the output for network.habitat.space.listRepos
type NetworkHabitatSpaceListReposOutput struct {
	Cursor string                             `json:"cursor,omitempty"`
	Repos  []NetworkHabitatSpaceListReposRepo `json:"repos"`
}

// NetworkHabitatSpaceListReposRepo represents a repo object
type NetworkHabitatSpaceListReposRepo struct {
	LexiconTypeID string       `json:"$type"`
	Did           string       `json:"did"`
	Hash          atdata.Bytes `json:"hash,omitempty"`
	Rev           string       `json:"rev,omitempty"`
}

// MarshalJSON sets $type to "network.habitat.space.listRepos#repo" before encoding.
func (t NetworkHabitatSpaceListReposRepo) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.space.listRepos#repo"
	type alias NetworkHabitatSpaceListReposRepo
	return json.Marshal(alias(t))
}
