package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSpaceGetRecordParams represents the input parameters for network.habitat.space.getRecord
type NetworkHabitatSpaceGetRecordParams struct {
	Collection string `json:"collection"`
	Repo       string `json:"repo,omitempty"`
	Rkey       string `json:"rkey"`
	Space      string `json:"space"`
}

// NetworkHabitatSpaceGetRecordOutput represents the output for network.habitat.space.getRecord
type NetworkHabitatSpaceGetRecordOutput struct {
	Cid   string      `json:"cid"`
	Uri   string      `json:"uri"`
	Value interface{} `json:"value"`
}
