package habitat

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// NetworkHabitatSpaceAppAccess represents a network.habitat.space.appAccess record
type NetworkHabitatSpaceAppAccess struct {
	LexiconTypeID string `json:"$type"`
	CreatedAt     string `json:"createdAt,omitempty"`
	Note          string `json:"note,omitempty"`
}

// MarshalJSON sets $type to "network.habitat.space.appAccess" before encoding.
func (t NetworkHabitatSpaceAppAccess) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "network.habitat.space.appAccess"
	type alias NetworkHabitatSpaceAppAccess
	return json.Marshal(alias(t))
}
