package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSpaceRegisterNotifyInput represents the input for network.habitat.space.registerNotify
type NetworkHabitatSpaceRegisterNotifyInput struct {
	Endpoint string `json:"endpoint"`
	Repo     string `json:"repo,omitempty"`
	Space    string `json:"space"`
}

// NetworkHabitatSpaceRegisterNotifyOutput represents the output for network.habitat.space.registerNotify
type NetworkHabitatSpaceRegisterNotifyOutput struct {
	ExpiresAt string `json:"expiresAt"`
}
