package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSpaceGetLatestCommitParams represents the input parameters for network.habitat.space.getLatestCommit
type NetworkHabitatSpaceGetLatestCommitParams struct {
	Repo  string `json:"repo"`
	Space string `json:"space"`
}

// NetworkHabitatSpaceGetLatestCommitOutput represents the output for network.habitat.space.getLatestCommit
type NetworkHabitatSpaceGetLatestCommitOutput struct {
	Commit NetworkHabitatSpaceDefsSignedCommit `json:"commit,omitempty"`
}
