package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSpaceDefsSignedCommit represents a signedCommit object
type NetworkHabitatSpaceDefsSignedCommit struct {
	Hash interface{} `json:"hash"`
	Ikm  interface{} `json:"ikm"`
	Mac  interface{} `json:"mac"`
	Rev  string      `json:"rev"`
	Sig  interface{} `json:"sig"`
	Ver  int64       `json:"ver"`
}
