package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSyncGetSpaceStateParams represents the input parameters for network.habitat.sync.getSpaceState
type NetworkHabitatSyncGetSpaceStateParams struct {
	Space string `json:"space"`
}

// NetworkHabitatSyncGetSpaceStateOutput represents the output for network.habitat.sync.getSpaceState
type NetworkHabitatSyncGetSpaceStateOutput struct {
	MemberRev string                                     `json:"memberRev"`
	Repos     []NetworkHabitatSyncGetSpaceStateRepoState `json:"repos"`
	Space     string                                     `json:"space"`
	SpaceRev  string                                     `json:"spaceRev"`
	SpaceType string                                     `json:"spaceType"`
}

// NetworkHabitatSyncGetSpaceStateRepoState represents a repoState object
type NetworkHabitatSyncGetSpaceStateRepoState struct {
	Did string `json:"did"`
	Rev string `json:"rev"`
}
