package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSyncSubscribeSpacesSpaceEvent represents a spaceEvent object
type NetworkHabitatSyncSubscribeSpacesSpaceEvent struct {
	Access     string      `json:"access,omitempty"`
	Action     string      `json:"action,omitempty"`
	Collection string      `json:"collection,omitempty"`
	Did        string      `json:"did,omitempty"`
	Idx        int64       `json:"idx,omitempty"`
	MemberRev  string      `json:"memberRev,omitempty"`
	Record     interface{} `json:"record,omitempty"`
	RecordRev  string      `json:"recordRev,omitempty"`
	Repo       string      `json:"repo,omitempty"`
	Rev        string      `json:"rev"`
	Rkey       string      `json:"rkey,omitempty"`
	Space      string      `json:"space,omitempty"`
	SpaceType  string      `json:"spaceType,omitempty"`
	Time       string      `json:"time,omitempty"`
	Type       string      `json:"type"`
}
