package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSyncGetMemberOplogParams represents the input parameters for network.habitat.sync.getMemberOplog
type NetworkHabitatSyncGetMemberOplogParams struct {
	Limit int64  `json:"limit,omitempty"`
	Since string `json:"since,omitempty"`
	Space string `json:"space"`
}

// NetworkHabitatSyncGetMemberOplogOutput represents the output for network.habitat.sync.getMemberOplog
type NetworkHabitatSyncGetMemberOplogOutput struct {
	Cursor string                                     `json:"cursor,omitempty"`
	Ops    []NetworkHabitatSyncGetMemberOplogMemberOp `json:"ops"`
}

// NetworkHabitatSyncGetMemberOplogMemberOp represents a memberOp object
type NetworkHabitatSyncGetMemberOplogMemberOp struct {
	Access string `json:"access,omitempty"`
	Action string `json:"action"`
	Did    string `json:"did"`
	Idx    int64  `json:"idx"`
	Rev    string `json:"rev"`
	Space  string `json:"space"`
}
