package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSyncListRecordChangesParams represents the input parameters for network.habitat.sync.listRecordChanges
type NetworkHabitatSyncListRecordChangesParams struct {
	Limit int64  `json:"limit,omitempty"`
	Repo  string `json:"repo,omitempty"`
	Since string `json:"since,omitempty"`
	Space string `json:"space"`
}

// NetworkHabitatSyncListRecordChangesOutput represents the output for network.habitat.sync.listRecordChanges
type NetworkHabitatSyncListRecordChangesOutput struct {
	Changes []NetworkHabitatSyncListRecordChangesRecordChange `json:"changes"`
	Cursor  string                                            `json:"cursor,omitempty"`
}

// NetworkHabitatSyncListRecordChangesRecordChange represents a recordChange object
type NetworkHabitatSyncListRecordChangesRecordChange struct {
	Action     string      `json:"action"`
	Collection string      `json:"collection"`
	Rev        string      `json:"rev"`
	Rkey       string      `json:"rkey"`
	Space      string      `json:"space"`
	Value      interface{} `json:"value,omitempty"`
}
