package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSyncListSpacesParams represents the input parameters for network.habitat.sync.listSpaces
type NetworkHabitatSyncListSpacesParams struct {
	SpaceTypes []string `json:"spaceTypes,omitempty"`
}

// NetworkHabitatSyncListSpacesOutput represents the output for network.habitat.sync.listSpaces
type NetworkHabitatSyncListSpacesOutput struct {
	Spaces []NetworkHabitatSyncListSpacesSpaceView `json:"spaces"`
}

// NetworkHabitatSyncListSpacesSpaceView represents a spaceView object
type NetworkHabitatSyncListSpacesSpaceView struct {
	CreatedAt string `json:"createdAt,omitempty"`
	MemberRev string `json:"memberRev,omitempty"`
	Space     string `json:"space"`
	SpaceRev  string `json:"spaceRev,omitempty"`
	SpaceType string `json:"spaceType"`
}
