package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatSyncListRecordsParams represents the input parameters for network.habitat.sync.listRecords
type NetworkHabitatSyncListRecordsParams struct {
	Collection string `json:"collection,omitempty"`
	Cursor     string `json:"cursor,omitempty"`
	Limit      int64  `json:"limit,omitempty"`
	Repo       string `json:"repo,omitempty"`
	Space      string `json:"space"`
}

// NetworkHabitatSyncListRecordsOutput represents the output for network.habitat.sync.listRecords
type NetworkHabitatSyncListRecordsOutput struct {
	Cursor  string                                `json:"cursor,omitempty"`
	Records []NetworkHabitatSyncListRecordsRecord `json:"records"`
}

// NetworkHabitatSyncListRecordsRecord represents a record object
type NetworkHabitatSyncListRecordsRecord struct {
	Collection string      `json:"collection"`
	Repo       string      `json:"repo"`
	Rev        string      `json:"rev"`
	Rkey       string      `json:"rkey"`
	Space      string      `json:"space"`
	Value      interface{} `json:"value"`
}
