/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RequireAuthRouteImport } from './routes/_requireAuth'
import { Route as RequireAuthIndexRouteImport } from './routes/_requireAuth/index'
import { Route as RequireAuthUriRouteImport } from './routes/_requireAuth/$uri'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RequireAuthRoute = RequireAuthRouteImport.update({
  id: '/_requireAuth',
  getParentRoute: () => rootRouteImport,
} as any)
const RequireAuthIndexRoute = RequireAuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RequireAuthRoute,
} as any)
const RequireAuthUriRoute = RequireAuthUriRouteImport.update({
  id: '/$uri',
  path: '/$uri',
  getParentRoute: () => RequireAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/$uri': typeof RequireAuthUriRoute
  '/': typeof RequireAuthIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/$uri': typeof RequireAuthUriRoute
  '/': typeof RequireAuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_requireAuth': typeof RequireAuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_requireAuth/$uri': typeof RequireAuthUriRoute
  '/_requireAuth/': typeof RequireAuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/$uri' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/$uri' | '/'
  id:
    | '__root__'
    | '/_requireAuth'
    | '/login'
    | '/_requireAuth/$uri'
    | '/_requireAuth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RequireAuthRoute: typeof RequireAuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_requireAuth': {
      id: '/_requireAuth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RequireAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_requireAuth/': {
      id: '/_requireAuth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RequireAuthIndexRouteImport
      parentRoute: typeof RequireAuthRoute
    }
    '/_requireAuth/$uri': {
      id: '/_requireAuth/$uri'
      path: '/$uri'
      fullPath: '/$uri'
      preLoaderRoute: typeof RequireAuthUriRouteImport
      parentRoute: typeof RequireAuthRoute
    }
  }
}

interface RequireAuthRouteChildren {
  RequireAuthUriRoute: typeof RequireAuthUriRoute
  RequireAuthIndexRoute: typeof RequireAuthIndexRoute
}

const RequireAuthRouteChildren: RequireAuthRouteChildren = {
  RequireAuthUriRoute: RequireAuthUriRoute,
  RequireAuthIndexRoute: RequireAuthIndexRoute,
}

const RequireAuthRouteWithChildren = RequireAuthRoute._addFileChildren(
  RequireAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  RequireAuthRoute: RequireAuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
