package atproto

// Code generated by lexgen. DO NOT EDIT.

// ComAtprotoRepoListRecordsParams represents the input parameters for com.atproto.repo.listRecords
type ComAtprotoRepoListRecordsParams struct {
	Collection string `json:"collection"`
	Cursor     string `json:"cursor,omitempty"`
	Limit      int64  `json:"limit,omitempty"`
	Repo       string `json:"repo"`
	Reverse    bool   `json:"reverse,omitempty"`
}

// ComAtprotoRepoListRecordsOutput represents the output for com.atproto.repo.listRecords
type ComAtprotoRepoListRecordsOutput struct {
	Cursor  string                            `json:"cursor,omitempty"`
	Records []ComAtprotoRepoListRecordsRecord `json:"records"`
}

// ComAtprotoRepoListRecordsRecord represents a record object
type ComAtprotoRepoListRecordsRecord struct {
	Cid   string      `json:"cid"`
	Uri   string      `json:"uri"`
	Value interface{} `json:"value"`
}
