package atproto

// Code generated by lexgen. DO NOT EDIT.

// ComAtprotoRepoDeleteRecordInput represents the input for com.atproto.repo.deleteRecord
type ComAtprotoRepoDeleteRecordInput struct {
	Collection string `json:"collection"`
	Repo       string `json:"repo"`
	Rkey       string `json:"rkey"`
	SwapCommit string `json:"swapCommit,omitempty"`
	SwapRecord string `json:"swapRecord,omitempty"`
}

// ComAtprotoRepoDeleteRecordOutput represents the output for com.atproto.repo.deleteRecord
type ComAtprotoRepoDeleteRecordOutput struct {
	Commit ComAtprotoRepoDefsCommitMeta `json:"commit,omitempty"`
}
