package atproto

// Code generated by lexgen. DO NOT EDIT.

// ComAtprotoRepoCreateRecordInput represents the input for com.atproto.repo.createRecord
type ComAtprotoRepoCreateRecordInput struct {
	Collection string      `json:"collection"`
	Record     interface{} `json:"record"`
	Repo       string      `json:"repo"`
	Rkey       string      `json:"rkey,omitempty"`
	SwapCommit string      `json:"swapCommit,omitempty"`
	Validate   bool        `json:"validate,omitempty"`
}

// ComAtprotoRepoCreateRecordOutput represents the output for com.atproto.repo.createRecord
type ComAtprotoRepoCreateRecordOutput struct {
	Cid              string                       `json:"cid"`
	Commit           ComAtprotoRepoDefsCommitMeta `json:"commit,omitempty"`
	Uri              string                       `json:"uri"`
	ValidationStatus string                       `json:"validationStatus,omitempty"`
}
