package atproto

// Code generated by lexgen. DO NOT EDIT.

// ComAtprotoRepoStrongRefMain represents a main object
type ComAtprotoRepoStrongRefMain struct {
	Cid string `json:"cid"`
	Uri string `json:"uri"`
}
