package atproto

// Code generated by lexgen. DO NOT EDIT.

// ComAtprotoRepoDescribeRepoParams represents the input parameters for com.atproto.repo.describeRepo
type ComAtprotoRepoDescribeRepoParams struct {
	Repo string `json:"repo"`
}

// ComAtprotoRepoDescribeRepoOutput represents the output for com.atproto.repo.describeRepo
type ComAtprotoRepoDescribeRepoOutput struct {
	Collections     []string    `json:"collections"`
	Did             string      `json:"did"`
	DidDoc          interface{} `json:"didDoc"`
	Handle          string      `json:"handle"`
	HandleIsCorrect bool        `json:"handleIsCorrect"`
}
