package atproto

// Code generated by lexgen. DO NOT EDIT.

// ComAtprotoRepoDefsCommitMeta represents a commitMeta object
type ComAtprotoRepoDefsCommitMeta struct {
	Cid string `json:"cid"`
	Rev string `json:"rev"`
}
