package atproto

// Code generated by lexgen. DO NOT EDIT.

// ComAtprotoRepoGetRecordParams represents the input parameters for com.atproto.repo.getRecord
type ComAtprotoRepoGetRecordParams struct {
	Cid        string `json:"cid,omitempty"`
	Collection string `json:"collection"`
	Repo       string `json:"repo"`
	Rkey       string `json:"rkey"`
}

// ComAtprotoRepoGetRecordOutput represents the output for com.atproto.repo.getRecord
type ComAtprotoRepoGetRecordOutput struct {
	Cid   string      `json:"cid,omitempty"`
	Uri   string      `json:"uri"`
	Value interface{} `json:"value"`
}
