package atproto

// Code generated by lexgen. DO NOT EDIT.

// ComAtprotoRepoPutRecordInput represents the input for com.atproto.repo.putRecord
type ComAtprotoRepoPutRecordInput struct {
	Collection string      `json:"collection"`
	Record     interface{} `json:"record"`
	Repo       string      `json:"repo"`
	Rkey       string      `json:"rkey"`
	SwapCommit string      `json:"swapCommit,omitempty"`
	SwapRecord string      `json:"swapRecord,omitempty"`
	Validate   bool        `json:"validate,omitempty"`
}

// ComAtprotoRepoPutRecordOutput represents the output for com.atproto.repo.putRecord
type ComAtprotoRepoPutRecordOutput struct {
	Cid              string                       `json:"cid"`
	Commit           ComAtprotoRepoDefsCommitMeta `json:"commit,omitempty"`
	Uri              string                       `json:"uri"`
	ValidationStatus string                       `json:"validationStatus,omitempty"`
}
