package atproto

// Code generated by lexgen. DO NOT EDIT.

// ComAtprotoServerGetServiceAuthParams represents the input parameters for com.atproto.server.getServiceAuth
type ComAtprotoServerGetServiceAuthParams struct {
	Aud string `json:"aud"`
	Exp int64  `json:"exp,omitempty"`
	Lxm string `json:"lxm,omitempty"`
}

// ComAtprotoServerGetServiceAuthOutput represents the output for com.atproto.server.getServiceAuth
type ComAtprotoServerGetServiceAuthOutput struct {
	Token string `json:"token"`
}
