package atproto

// Code generated by lexgen. DO NOT EDIT.

// ComAtprotoSpaceNotifyWriteInput represents the input for com.atproto.space.notifyWrite
type ComAtprotoSpaceNotifyWriteInput struct {
	Hash  interface{} `json:"hash"`
	Repo  string      `json:"repo"`
	Rev   string      `json:"rev"`
	Space string      `json:"space"`
}
