/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RequireAuthRouteImport } from './routes/_requireAuth'
import { Route as RequireAuthIndexRouteImport } from './routes/_requireAuth/index'
import { Route as RequireAuthHandleHandleRouteImport } from './routes/_requireAuth/handle.$handle'
import { Route as RequireAuthHandlePRkeyRouteImport } from './routes/_requireAuth/$handle.p.$rkey'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RequireAuthRoute = RequireAuthRouteImport.update({
  id: '/_requireAuth',
  getParentRoute: () => rootRouteImport,
} as any)
const RequireAuthIndexRoute = RequireAuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RequireAuthRoute,
} as any)
const RequireAuthHandleHandleRoute = RequireAuthHandleHandleRouteImport.update({
  id: '/handle/$handle',
  path: '/handle/$handle',
  getParentRoute: () => RequireAuthRoute,
} as any)
const RequireAuthHandlePRkeyRoute = RequireAuthHandlePRkeyRouteImport.update({
  id: '/$handle/p/$rkey',
  path: '/$handle/p/$rkey',
  getParentRoute: () => RequireAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/': typeof RequireAuthIndexRoute
  '/handle/$handle': typeof RequireAuthHandleHandleRoute
  '/$handle/p/$rkey': typeof RequireAuthHandlePRkeyRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof RequireAuthIndexRoute
  '/handle/$handle': typeof RequireAuthHandleHandleRoute
  '/$handle/p/$rkey': typeof RequireAuthHandlePRkeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_requireAuth': typeof RequireAuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_requireAuth/': typeof RequireAuthIndexRoute
  '/_requireAuth/handle/$handle': typeof RequireAuthHandleHandleRoute
  '/_requireAuth/$handle/p/$rkey': typeof RequireAuthHandlePRkeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/' | '/handle/$handle' | '/$handle/p/$rkey'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/handle/$handle' | '/$handle/p/$rkey'
  id:
    | '__root__'
    | '/_requireAuth'
    | '/login'
    | '/_requireAuth/'
    | '/_requireAuth/handle/$handle'
    | '/_requireAuth/$handle/p/$rkey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RequireAuthRoute: typeof RequireAuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_requireAuth': {
      id: '/_requireAuth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RequireAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_requireAuth/': {
      id: '/_requireAuth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RequireAuthIndexRouteImport
      parentRoute: typeof RequireAuthRoute
    }
    '/_requireAuth/handle/$handle': {
      id: '/_requireAuth/handle/$handle'
      path: '/handle/$handle'
      fullPath: '/handle/$handle'
      preLoaderRoute: typeof RequireAuthHandleHandleRouteImport
      parentRoute: typeof RequireAuthRoute
    }
    '/_requireAuth/$handle/p/$rkey': {
      id: '/_requireAuth/$handle/p/$rkey'
      path: '/$handle/p/$rkey'
      fullPath: '/$handle/p/$rkey'
      preLoaderRoute: typeof RequireAuthHandlePRkeyRouteImport
      parentRoute: typeof RequireAuthRoute
    }
  }
}

interface RequireAuthRouteChildren {
  RequireAuthIndexRoute: typeof RequireAuthIndexRoute
  RequireAuthHandleHandleRoute: typeof RequireAuthHandleHandleRoute
  RequireAuthHandlePRkeyRoute: typeof RequireAuthHandlePRkeyRoute
}

const RequireAuthRouteChildren: RequireAuthRouteChildren = {
  RequireAuthIndexRoute: RequireAuthIndexRoute,
  RequireAuthHandleHandleRoute: RequireAuthHandleHandleRoute,
  RequireAuthHandlePRkeyRoute: RequireAuthHandlePRkeyRoute,
}

const RequireAuthRouteWithChildren = RequireAuthRoute._addFileChildren(
  RequireAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  RequireAuthRoute: RequireAuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
