package opensocial

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// CommunityOpensocialAcceptance represents a community.opensocial.acceptance record
type CommunityOpensocialAcceptance struct {
	LexiconTypeID string `json:"$type"`
	UpdatedAt     string `json:"updatedAt"`
}

// MarshalJSON sets $type to "community.opensocial.acceptance" before encoding.
func (t CommunityOpensocialAcceptance) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "community.opensocial.acceptance"
	type alias CommunityOpensocialAcceptance
	return json.Marshal(alias(t))
}
