package opensocial

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// CommunityOpensocialAccess represents a community.opensocial.access record
type CommunityOpensocialAccess struct {
	LexiconTypeID string   `json:"$type"`
	Roles         []string `json:"roles"`
	UpdatedAt     string   `json:"updatedAt,omitempty"`
}

// MarshalJSON sets $type to "community.opensocial.access" before encoding.
func (t CommunityOpensocialAccess) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "community.opensocial.access"
	type alias CommunityOpensocialAccess
	return json.Marshal(alias(t))
}
