package opensocial

// Code generated by lexgen. DO NOT EDIT.

// CommunityOpensocialAssignRolesInput represents the input for community.opensocial.assignRoles
type CommunityOpensocialAssignRolesInput struct {
	Member string   `json:"member"`
	Org    string   `json:"org"`
	Roles  []string `json:"roles"`
}
