package opensocial

// Code generated by lexgen. DO NOT EDIT.

// CommunityOpensocialCreateInviteInput represents the input for community.opensocial.createInvite
type CommunityOpensocialCreateInviteInput struct {
	Invitee string   `json:"invitee"`
	Org     string   `json:"org"`
	Roles   []string `json:"roles,omitempty"`
}

// CommunityOpensocialCreateInviteOutput represents the output for community.opensocial.createInvite
type CommunityOpensocialCreateInviteOutput struct {
	Invite CommunityOpensocialDefsInviteView `json:"invite"`
}
