package opensocial

// Code generated by lexgen. DO NOT EDIT.

// CommunityOpensocialCreateSpaceInput represents the input for community.opensocial.createSpace
type CommunityOpensocialCreateSpaceInput struct {
	Org   string   `json:"org"`
	Roles []string `json:"roles,omitempty"`
	Skey  string   `json:"skey,omitempty"`
	Type  string   `json:"type"`
}

// CommunityOpensocialCreateSpaceOutput represents the output for community.opensocial.createSpace
type CommunityOpensocialCreateSpaceOutput struct {
	Uri string `json:"uri"`
}
