package opensocial

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// CommunityOpensocialDefsInviteView represents a inviteView object
type CommunityOpensocialDefsInviteView struct {
	LexiconTypeID string   `json:"$type"`
	CreatedAt     string   `json:"createdAt"`
	Id            string   `json:"id"`
	Invitee       string   `json:"invitee"`
	Org           string   `json:"org"`
	Roles         []string `json:"roles"`
}

// MarshalJSON sets $type to "community.opensocial.defs#inviteView" before encoding.
func (t CommunityOpensocialDefsInviteView) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "community.opensocial.defs#inviteView"
	type alias CommunityOpensocialDefsInviteView
	return json.Marshal(alias(t))
}
