package opensocial

// Code generated by lexgen. DO NOT EDIT.

// CommunityOpensocialDeleteRoleInput represents the input for community.opensocial.deleteRole
type CommunityOpensocialDeleteRoleInput struct {
	Org  string `json:"org"`
	Role string `json:"role"`
}
