package opensocial

// Code generated by lexgen. DO NOT EDIT.

// CommunityOpensocialEjectMemberInput represents the input for community.opensocial.ejectMember
type CommunityOpensocialEjectMemberInput struct {
	Member string `json:"member"`
	Org    string `json:"org"`
}
