package opensocial

// Code generated by lexgen. DO NOT EDIT.

// CommunityOpensocialListPendingInvitesParams represents the input parameters for community.opensocial.listPendingInvites
type CommunityOpensocialListPendingInvitesParams struct {
	Cursor string `json:"cursor,omitempty"`
	Limit  int64  `json:"limit,omitempty"`
	Org    string `json:"org"`
}

// CommunityOpensocialListPendingInvitesOutput represents the output for community.opensocial.listPendingInvites
type CommunityOpensocialListPendingInvitesOutput struct {
	Cursor  string                              `json:"cursor,omitempty"`
	Invites []CommunityOpensocialDefsInviteView `json:"invites"`
}
