package opensocial

// Code generated by lexgen. DO NOT EDIT.

// CommunityOpensocialListInvitesParams represents the input parameters for community.opensocial.listInvites
type CommunityOpensocialListInvitesParams struct {
	Cursor string `json:"cursor,omitempty"`
	Limit  int64  `json:"limit,omitempty"`
}

// CommunityOpensocialListInvitesOutput represents the output for community.opensocial.listInvites
type CommunityOpensocialListInvitesOutput struct {
	Cursor  string                              `json:"cursor,omitempty"`
	Invites []CommunityOpensocialDefsInviteView `json:"invites"`
}
