package opensocial

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// CommunityOpensocialMembership represents a community.opensocial.membership record
type CommunityOpensocialMembership struct {
	LexiconTypeID string   `json:"$type"`
	Roles         []string `json:"roles"`
	UpdatedAt     string   `json:"updatedAt"`
}

// MarshalJSON sets $type to "community.opensocial.membership" before encoding.
func (t CommunityOpensocialMembership) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "community.opensocial.membership"
	type alias CommunityOpensocialMembership
	return json.Marshal(alias(t))
}
