package opensocial

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// CommunityOpensocialMemberProfile represents a community.opensocial.memberProfile record
type CommunityOpensocialMemberProfile struct {
	LexiconTypeID string `json:"$type"`
	AvatarUrl     string `json:"avatarUrl,omitempty"`
	Bio           string `json:"bio,omitempty"`
	DisplayName   string `json:"displayName,omitempty"`
	UpdatedAt     string `json:"updatedAt"`
}

// MarshalJSON sets $type to "community.opensocial.memberProfile" before encoding.
func (t CommunityOpensocialMemberProfile) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "community.opensocial.memberProfile"
	type alias CommunityOpensocialMemberProfile
	return json.Marshal(alias(t))
}
