package opensocial

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// CommunityOpensocialPermissionsActionBinding represents a actionBinding object
type CommunityOpensocialPermissionsActionBinding struct {
	LexiconTypeID string   `json:"$type"`
	Action        string   `json:"action"`
	Roles         []string `json:"roles"`
}

// MarshalJSON sets $type to "community.opensocial.permissions#actionBinding" before encoding.
func (t CommunityOpensocialPermissionsActionBinding) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "community.opensocial.permissions#actionBinding"
	type alias CommunityOpensocialPermissionsActionBinding
	return json.Marshal(alias(t))
}

// CommunityOpensocialPermissionsAssignableBinding represents a assignableBinding object
type CommunityOpensocialPermissionsAssignableBinding struct {
	LexiconTypeID string   `json:"$type"`
	Role          string   `json:"role"`
	Roles         []string `json:"roles"`
}

// MarshalJSON sets $type to "community.opensocial.permissions#assignableBinding" before encoding.
func (t CommunityOpensocialPermissionsAssignableBinding) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "community.opensocial.permissions#assignableBinding"
	type alias CommunityOpensocialPermissionsAssignableBinding
	return json.Marshal(alias(t))
}

// CommunityOpensocialPermissions represents a community.opensocial.permissions record
type CommunityOpensocialPermissions struct {
	LexiconTypeID string                                            `json:"$type"`
	Assignable    []CommunityOpensocialPermissionsAssignableBinding `json:"assignable"`
	Bindings      []CommunityOpensocialPermissionsActionBinding     `json:"bindings"`
	UpdatedAt     string                                            `json:"updatedAt,omitempty"`
}

// MarshalJSON sets $type to "community.opensocial.permissions" before encoding.
func (t CommunityOpensocialPermissions) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "community.opensocial.permissions"
	type alias CommunityOpensocialPermissions
	return json.Marshal(alias(t))
}
