package opensocial

// Code generated by lexgen. DO NOT EDIT.

import (
	"encoding/json"
	"github.com/bluesky-social/indigo/atproto/atdata"
)

// CommunityOpensocialProfile represents a community.opensocial.profile record
type CommunityOpensocialProfile struct {
	LexiconTypeID string       `json:"$type"`
	Avatar        *atdata.Blob `json:"avatar,omitempty"`
	Description   string       `json:"description,omitempty"`
	Name          string       `json:"name"`
	UpdatedAt     string       `json:"updatedAt,omitempty"`
}

// MarshalJSON sets $type to "community.opensocial.profile" before encoding.
func (t CommunityOpensocialProfile) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "community.opensocial.profile"
	type alias CommunityOpensocialProfile
	return json.Marshal(alias(t))
}
