package opensocial

// Code generated by lexgen. DO NOT EDIT.

// CommunityOpensocialPutRoleInput represents the input for community.opensocial.putRole
type CommunityOpensocialPutRoleInput struct {
	Description string `json:"description,omitempty"`
	Name        string `json:"name"`
	Org         string `json:"org"`
	Role        string `json:"role"`
}
