package opensocial

// Code generated by lexgen. DO NOT EDIT.

// CommunityOpensocialRequestJoinInput represents the input for community.opensocial.requestJoin
type CommunityOpensocialRequestJoinInput struct {
	Org string `json:"org"`
}

// CommunityOpensocialRequestJoinOutput represents the output for community.opensocial.requestJoin
type CommunityOpensocialRequestJoinOutput struct {
	Roles []string `json:"roles"`
}
