package opensocial

// Code generated by lexgen. DO NOT EDIT.

// CommunityOpensocialRevokeInviteInput represents the input for community.opensocial.revokeInvite
type CommunityOpensocialRevokeInviteInput struct {
	Id  string `json:"id"`
	Org string `json:"org"`
}
