package opensocial

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// CommunityOpensocialRole represents a community.opensocial.role record
type CommunityOpensocialRole struct {
	LexiconTypeID string `json:"$type"`
	Description   string `json:"description,omitempty"`
	Name          string `json:"name"`
	UpdatedAt     string `json:"updatedAt,omitempty"`
}

// MarshalJSON sets $type to "community.opensocial.role" before encoding.
func (t CommunityOpensocialRole) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "community.opensocial.role"
	type alias CommunityOpensocialRole
	return json.Marshal(alias(t))
}
