package opensocial

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// CommunityOpensocialSpace represents a community.opensocial.space record
type CommunityOpensocialSpace struct {
	LexiconTypeID string `json:"$type"`
	UpdatedAt     string `json:"updatedAt,omitempty"`
	Uri           string `json:"uri"`
}

// MarshalJSON sets $type to "community.opensocial.space" before encoding.
func (t CommunityOpensocialSpace) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "community.opensocial.space"
	type alias CommunityOpensocialSpace
	return json.Marshal(alias(t))
}
