package opensocial

// Code generated by lexgen. DO NOT EDIT.

// CommunityOpensocialUpdateSpaceInput represents the input for community.opensocial.updateSpace
type CommunityOpensocialUpdateSpaceInput struct {
	Roles []string `json:"roles"`
	Space string   `json:"space"`
}
