package opensocial

// Code generated by lexgen. DO NOT EDIT.

// CommunityOpensocialUpdatePermissionsInput represents the input for community.opensocial.updatePermissions
type CommunityOpensocialUpdatePermissionsInput struct {
	Assignable []CommunityOpensocialPermissionsAssignableBinding `json:"assignable"`
	Bindings   []CommunityOpensocialPermissionsActionBinding     `json:"bindings"`
	Org        string                                            `json:"org"`
}
