package opensocial

// Code generated by lexgen. DO NOT EDIT.

// CommunityOpensocialUpdateProfileInput represents the input for community.opensocial.updateProfile
type CommunityOpensocialUpdateProfileInput struct {
	Description string `json:"description,omitempty"`
	JoinPolicy  string `json:"joinPolicy,omitempty"`
	Name        string `json:"name"`
	Org         string `json:"org"`
}
