package opensocial

// Code generated by lexgen. DO NOT EDIT.

import "github.com/bluesky-social/indigo/atproto/atdata"

// CommunityOpensocialUploadImageParams represents the input parameters for community.opensocial.uploadImage
type CommunityOpensocialUploadImageParams struct {
	Org string `json:"org"`
}

// CommunityOpensocialUploadImageOutput represents the output for community.opensocial.uploadImage
type CommunityOpensocialUploadImageOutput struct {
	Blob atdata.Blob `json:"blob"`
}
