tasks:
  docker-build:
    command: docker
    args:
      - build
      - -f
      - '@in(0)'
      - -t
      - '$project'
      - .
    inputs:
    - Dockerfile
    options:
      internal: true
      runFromWorkspaceRoot: true
      cache: false
      runInCI: false
