$schema: https://moonrepo.dev/schemas/tasks.json
fileGroups:
  mod:
    - 'go.mod'
    - 'go.sum'
  src:
    - '**/*.go'
    - '!**/*_test.go'
  test:
    - '**/*.go'
tasks:
  format-check:
    command: golangci-lint fmt -d
  format:
    command: golangci-lint fmt
    preset: utility
  lint-check:
    command: golangci-lint run
  lint:
    command: golangci-lint run --fix
    preset: utility
  build:
    deps:
    - root:build
    inputs:
    - '@group(mod)'
    - '@group(src)'
    command: go 
    args:
    - build
    - -o
    - '@out(0)'
    outputs:
    - /bin/$project
  test:
    deps:
      - ~:build
    inputs:
    - '@group(mod)'
    - '@group(test)'
    command: go
    args:
    - test
    - ./...
  tidy-deps:
    command: go
    args:
    - mod
    - tidy
    preset: utility
  start:
    command: ./bin/$project
    deps:
    - ~:build
    options:
      runFromWorkspaceRoot: true
      envFile:
      - /dev.env
    preset: server
  dev:
    command: air
    args:
    - -c
    - $workspaceRoot/.air.toml
    - --root
    - $workspaceRoot
    - --build.cmd
    - go build -o $workspaceRoot/bin/$project .
    - --build.entrypoint
    - $workspaceRoot/bin/$project
    - --build.include_dir
    - cmd/$project,internal,api,pkg
    - --log.main_only 
    - 'true'
    options:
      envFile:
      - /dev.env
    preset: server
inheritedBy:
  toolchain: go
