tasks:
  dev:
    env:
      DOMAIN: $project.local.habitat.network
      HABITAT_DOMAIN: pear.local.habitat.network
  regenerate:
    command: moon 
    args:
      - generate
      - web-app
      - --to
      - $projectSource
      - --force
      - --
      - --name
      - $project
    preset: utility
    options:
      runFromWorkspaceRoot: true

inheritedBy:
  toolchain: typescript
  layer: application
