package comatproto

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// ComAtprotoRepoDefsCommitMeta represents a commitMeta object
type ComAtprotoRepoDefsCommitMeta struct {
	LexiconTypeID string `json:"$type"`
	Cid           string `json:"cid"`
	Rev           string `json:"rev"`
}

// MarshalJSON sets $type to "com.atproto.repo.defs#commitMeta" before encoding.
func (t ComAtprotoRepoDefsCommitMeta) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "com.atproto.repo.defs#commitMeta"
	type alias ComAtprotoRepoDefsCommitMeta
	return json.Marshal(alias(t))
}
