package comatproto

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// ComAtprotoRepoListRecordsParams represents the input parameters for com.atproto.repo.listRecords
type ComAtprotoRepoListRecordsParams struct {
	Collection string `json:"collection"`
	Cursor     string `json:"cursor,omitempty"`
	Limit      int64  `json:"limit,omitempty"`
	Repo       string `json:"repo"`
	Reverse    bool   `json:"reverse,omitempty"`
}

// ComAtprotoRepoListRecordsOutput represents the output for com.atproto.repo.listRecords
type ComAtprotoRepoListRecordsOutput struct {
	Cursor  string                            `json:"cursor,omitempty"`
	Records []ComAtprotoRepoListRecordsRecord `json:"records"`
}

// ComAtprotoRepoListRecordsRecord represents a record object
type ComAtprotoRepoListRecordsRecord struct {
	LexiconTypeID string      `json:"$type"`
	Cid           string      `json:"cid"`
	Uri           string      `json:"uri"`
	Value         interface{} `json:"value"`
}

// MarshalJSON sets $type to "com.atproto.repo.listRecords#record" before encoding.
func (t ComAtprotoRepoListRecordsRecord) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "com.atproto.repo.listRecords#record"
	type alias ComAtprotoRepoListRecordsRecord
	return json.Marshal(alias(t))
}
