package comatproto

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// ComAtprotoRepoStrongRefMain represents a main object
type ComAtprotoRepoStrongRefMain struct {
	LexiconTypeID string `json:"$type"`
	Cid           string `json:"cid"`
	Uri           string `json:"uri"`
}

// MarshalJSON sets $type to "com.atproto.repo.strongRef#main" before encoding.
func (t ComAtprotoRepoStrongRefMain) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "com.atproto.repo.strongRef#main"
	type alias ComAtprotoRepoStrongRefMain
	return json.Marshal(alias(t))
}
