package comatproto

// Code generated by lexgen. DO NOT EDIT.

// ComAtprotoSimplespaceCheckUserAccessParams represents the input parameters for com.atproto.simplespace.checkUserAccess
type ComAtprotoSimplespaceCheckUserAccessParams struct {
	Access   string `json:"access"`
	ClientId string `json:"clientId,omitempty"`
	Space    string `json:"space"`
	User     string `json:"user"`
}

// ComAtprotoSimplespaceCheckUserAccessOutput represents the output for com.atproto.simplespace.checkUserAccess
type ComAtprotoSimplespaceCheckUserAccessOutput struct {
	Authorized bool `json:"authorized"`
}
