package comatproto

// Code generated by lexgen. DO NOT EDIT.

// ComAtprotoSimplespaceGetSpaceParams represents the input parameters for com.atproto.simplespace.getSpace
type ComAtprotoSimplespaceGetSpaceParams struct {
	Space string `json:"space"`
}

// ComAtprotoSimplespaceGetSpaceOutput represents the output for com.atproto.simplespace.getSpace
type ComAtprotoSimplespaceGetSpaceOutput struct {
	AppAccess   interface{} `json:"appAccess"`
	ReadPolicy  interface{} `json:"readPolicy"`
	Uri         string      `json:"uri"`
	WritePolicy interface{} `json:"writePolicy"`
}
