package comatproto

// Code generated by lexgen. DO NOT EDIT.

// ComAtprotoSimplespaceRemoveMemberInput represents the input for com.atproto.simplespace.removeMember
type ComAtprotoSimplespaceRemoveMemberInput struct {
	Did   string `json:"did"`
	Space string `json:"space"`
}
