package comatproto

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// ComAtprotoSimplespaceListMembersParams represents the input parameters for com.atproto.simplespace.listMembers
type ComAtprotoSimplespaceListMembersParams struct {
	Cursor string `json:"cursor,omitempty"`
	Limit  int64  `json:"limit,omitempty"`
	Space  string `json:"space"`
}

// ComAtprotoSimplespaceListMembersOutput represents the output for com.atproto.simplespace.listMembers
type ComAtprotoSimplespaceListMembersOutput struct {
	Cursor  string                                   `json:"cursor,omitempty"`
	Members []ComAtprotoSimplespaceListMembersMember `json:"members"`
}

// ComAtprotoSimplespaceListMembersMember represents a member object
type ComAtprotoSimplespaceListMembersMember struct {
	LexiconTypeID string `json:"$type"`
	Did           string `json:"did"`
	Read          bool   `json:"read"`
	Write         bool   `json:"write"`
}

// MarshalJSON sets $type to "com.atproto.simplespace.listMembers#member" before encoding.
func (t ComAtprotoSimplespaceListMembersMember) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "com.atproto.simplespace.listMembers#member"
	type alias ComAtprotoSimplespaceListMembersMember
	return json.Marshal(alias(t))
}
