package comatproto

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// ComAtprotoSimplespaceDefsAllowList represents a allowList object
type ComAtprotoSimplespaceDefsAllowList struct {
	LexiconTypeID string   `json:"$type"`
	Allowed       []string `json:"allowed"`
}

// MarshalJSON sets $type to "com.atproto.simplespace.defs#allowList" before encoding.
func (t ComAtprotoSimplespaceDefsAllowList) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "com.atproto.simplespace.defs#allowList"
	type alias ComAtprotoSimplespaceDefsAllowList
	return json.Marshal(alias(t))
}

// ComAtprotoSimplespaceDefsManagingAppPolicy represents a managingAppPolicy object
type ComAtprotoSimplespaceDefsManagingAppPolicy struct {
	LexiconTypeID string `json:"$type"`
	ManagingApp   string `json:"managingApp"`
}

// MarshalJSON sets $type to "com.atproto.simplespace.defs#managingAppPolicy" before encoding.
func (t ComAtprotoSimplespaceDefsManagingAppPolicy) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "com.atproto.simplespace.defs#managingAppPolicy"
	type alias ComAtprotoSimplespaceDefsManagingAppPolicy
	return json.Marshal(alias(t))
}

// ComAtprotoSimplespaceDefsMemberListPolicy represents a memberListPolicy object
type ComAtprotoSimplespaceDefsMemberListPolicy struct {
	LexiconTypeID string `json:"$type"`
}

// MarshalJSON sets $type to "com.atproto.simplespace.defs#memberListPolicy" before encoding.
func (t ComAtprotoSimplespaceDefsMemberListPolicy) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "com.atproto.simplespace.defs#memberListPolicy"
	type alias ComAtprotoSimplespaceDefsMemberListPolicy
	return json.Marshal(alias(t))
}

// ComAtprotoSimplespaceDefsOpen represents a open object
type ComAtprotoSimplespaceDefsOpen struct {
	LexiconTypeID string `json:"$type"`
}

// MarshalJSON sets $type to "com.atproto.simplespace.defs#open" before encoding.
func (t ComAtprotoSimplespaceDefsOpen) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "com.atproto.simplespace.defs#open"
	type alias ComAtprotoSimplespaceDefsOpen
	return json.Marshal(alias(t))
}

// ComAtprotoSimplespaceDefsPublicPolicy represents a publicPolicy object
type ComAtprotoSimplespaceDefsPublicPolicy struct {
	LexiconTypeID string `json:"$type"`
}

// MarshalJSON sets $type to "com.atproto.simplespace.defs#publicPolicy" before encoding.
func (t ComAtprotoSimplespaceDefsPublicPolicy) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "com.atproto.simplespace.defs#publicPolicy"
	type alias ComAtprotoSimplespaceDefsPublicPolicy
	return json.Marshal(alias(t))
}
