package comatproto

// Code generated by lexgen. DO NOT EDIT.

// ComAtprotoSimplespacePutMemberInput represents the input for com.atproto.simplespace.putMember
type ComAtprotoSimplespacePutMemberInput struct {
	Did   string `json:"did"`
	Read  bool   `json:"read"`
	Space string `json:"space"`
	Write bool   `json:"write"`
}
