package comatproto

// Code generated by lexgen. DO NOT EDIT.

// ComAtprotoSimplespaceCreateSpaceInput represents the input for com.atproto.simplespace.createSpace
type ComAtprotoSimplespaceCreateSpaceInput struct {
	AppAccess   interface{} `json:"appAccess"`
	ReadPolicy  interface{} `json:"readPolicy"`
	Skey        string      `json:"skey,omitempty"`
	Type        string      `json:"type"`
	WritePolicy interface{} `json:"writePolicy"`
}

// ComAtprotoSimplespaceCreateSpaceOutput represents the output for com.atproto.simplespace.createSpace
type ComAtprotoSimplespaceCreateSpaceOutput struct {
	Uri string `json:"uri"`
}
