package comatproto

// Code generated by lexgen. DO NOT EDIT.

// ComAtprotoSimplespaceDeleteSpaceInput represents the input for com.atproto.simplespace.deleteSpace
type ComAtprotoSimplespaceDeleteSpaceInput struct {
	Space string `json:"space"`
}
