package comatproto

// Code generated by lexgen. DO NOT EDIT.

// ComAtprotoSimplespaceUpdateSpaceInput represents the input for com.atproto.simplespace.updateSpace
type ComAtprotoSimplespaceUpdateSpaceInput struct {
	AppAccess   interface{} `json:"appAccess,omitempty"`
	ReadPolicy  interface{} `json:"readPolicy,omitempty"`
	Space       string      `json:"space"`
	WritePolicy interface{} `json:"writePolicy,omitempty"`
}
