package comatproto

// Code generated by lexgen. DO NOT EDIT.

// ComAtprotoSpaceNotifyCredentialRevokedInput represents the input for com.atproto.space.notifyCredentialRevoked
type ComAtprotoSpaceNotifyCredentialRevokedInput struct {
	Credentials []string `json:"credentials"`
	Space       string   `json:"space"`
}
