package comatproto

// Code generated by lexgen. DO NOT EDIT.

import (
	"encoding/json"
	"github.com/bluesky-social/indigo/atproto/atdata"
)

// ComAtprotoSpaceDefsSignedCommit represents a signedCommit object
type ComAtprotoSpaceDefsSignedCommit struct {
	LexiconTypeID string       `json:"$type"`
	Hash          atdata.Bytes `json:"hash"`
	Ikm           atdata.Bytes `json:"ikm"`
	Mac           atdata.Bytes `json:"mac"`
	Rev           string       `json:"rev"`
	Sig           atdata.Bytes `json:"sig"`
	Ver           int64        `json:"ver"`
}

// MarshalJSON sets $type to "com.atproto.space.defs#signedCommit" before encoding.
func (t ComAtprotoSpaceDefsSignedCommit) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "com.atproto.space.defs#signedCommit"
	type alias ComAtprotoSpaceDefsSignedCommit
	return json.Marshal(alias(t))
}
