package comatproto

// Code generated by lexgen. DO NOT EDIT.

// ComAtprotoSpaceUnregisterNotifyInput represents the input for com.atproto.space.unregisterNotify
type ComAtprotoSpaceUnregisterNotifyInput struct {
	Service string `json:"service"`
	Space   string `json:"space"`
}
