package comatproto

// Code generated by lexgen. DO NOT EDIT.

// ComAtprotoSpaceGetRecordParams represents the input parameters for com.atproto.space.getRecord
type ComAtprotoSpaceGetRecordParams struct {
	Collection string `json:"collection"`
	Repo       string `json:"repo"`
	Rkey       string `json:"rkey"`
	Space      string `json:"space"`
}

// ComAtprotoSpaceGetRecordOutput represents the output for com.atproto.space.getRecord
type ComAtprotoSpaceGetRecordOutput struct {
	Cid   string      `json:"cid"`
	Uri   string      `json:"uri"`
	Value interface{} `json:"value"`
}
