package comatproto

// Code generated by lexgen. DO NOT EDIT.

import (
	"encoding/json"
	"github.com/bluesky-social/indigo/atproto/atdata"
)

// ComAtprotoSpaceListReposParams represents the input parameters for com.atproto.space.listRepos
type ComAtprotoSpaceListReposParams struct {
	Cursor string `json:"cursor,omitempty"`
	Limit  int64  `json:"limit,omitempty"`
	Space  string `json:"space"`
}

// ComAtprotoSpaceListReposOutput represents the output for com.atproto.space.listRepos
type ComAtprotoSpaceListReposOutput struct {
	Cursor string                         `json:"cursor,omitempty"`
	Repos  []ComAtprotoSpaceListReposRepo `json:"repos"`
}

// ComAtprotoSpaceListReposRepo represents a repo object
type ComAtprotoSpaceListReposRepo struct {
	LexiconTypeID string       `json:"$type"`
	Did           string       `json:"did"`
	Hash          atdata.Bytes `json:"hash"`
	RepoRev       string       `json:"repoRev"`
	SpaceRev      string       `json:"spaceRev"`
}

// MarshalJSON sets $type to "com.atproto.space.listRepos#repo" before encoding.
func (t ComAtprotoSpaceListReposRepo) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "com.atproto.space.listRepos#repo"
	type alias ComAtprotoSpaceListReposRepo
	return json.Marshal(alias(t))
}
