package comatproto

// Code generated by lexgen. DO NOT EDIT.

// ComAtprotoSpaceGetSpaceCredentialInput represents the input for com.atproto.space.getSpaceCredential
type ComAtprotoSpaceGetSpaceCredentialInput struct {
	ClientAttestation string `json:"clientAttestation,omitempty"`
	Space             string `json:"space"`
}

// ComAtprotoSpaceGetSpaceCredentialOutput represents the output for com.atproto.space.getSpaceCredential
type ComAtprotoSpaceGetSpaceCredentialOutput struct {
	Credential string `json:"credential"`
}
