package comatproto

// Code generated by lexgen. DO NOT EDIT.

// ComAtprotoSpaceDeleteRecordInput represents the input for com.atproto.space.deleteRecord
type ComAtprotoSpaceDeleteRecordInput struct {
	Collection string `json:"collection"`
	Repo       string `json:"repo"`
	Rkey       string `json:"rkey"`
	Space      string `json:"space"`
}

// ComAtprotoSpaceDeleteRecordOutput represents the output for com.atproto.space.deleteRecord
type ComAtprotoSpaceDeleteRecordOutput struct {
}
