package comatproto

// Code generated by lexgen. DO NOT EDIT.

// ComAtprotoSpaceGetLatestCommitParams represents the input parameters for com.atproto.space.getLatestCommit
type ComAtprotoSpaceGetLatestCommitParams struct {
	Repo  string `json:"repo"`
	Space string `json:"space"`
}

// ComAtprotoSpaceGetLatestCommitOutput represents the output for com.atproto.space.getLatestCommit
type ComAtprotoSpaceGetLatestCommitOutput struct {
	Commit ComAtprotoSpaceDefsSignedCommit `json:"commit"`
}
