package comatproto

// Code generated by lexgen. DO NOT EDIT.

// ComAtprotoSpaceGetBlobParams represents the input parameters for com.atproto.space.getBlob
type ComAtprotoSpaceGetBlobParams struct {
	Cid   string `json:"cid"`
	Repo  string `json:"repo"`
	Space string `json:"space"`
}
