package comatproto

// Code generated by lexgen. DO NOT EDIT.

// ComAtprotoSpaceGetDelegationTokenParams represents the input parameters for com.atproto.space.getDelegationToken
type ComAtprotoSpaceGetDelegationTokenParams struct {
	Space string `json:"space"`
}

// ComAtprotoSpaceGetDelegationTokenOutput represents the output for com.atproto.space.getDelegationToken
type ComAtprotoSpaceGetDelegationTokenOutput struct {
	Token string `json:"token"`
}
