package comatproto

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// ComAtprotoSpaceListSpacesParams represents the input parameters for com.atproto.space.listSpaces
type ComAtprotoSpaceListSpacesParams struct {
	Cursor    string `json:"cursor,omitempty"`
	Did       string `json:"did,omitempty"`
	Limit     int64  `json:"limit,omitempty"`
	SpaceType string `json:"spaceType,omitempty"`
}

// ComAtprotoSpaceListSpacesOutput represents the output for com.atproto.space.listSpaces
type ComAtprotoSpaceListSpacesOutput struct {
	Cursor string                               `json:"cursor,omitempty"`
	Spaces []ComAtprotoSpaceListSpacesSpaceView `json:"spaces"`
}

// ComAtprotoSpaceListSpacesSpaceView represents a spaceView object
type ComAtprotoSpaceListSpacesSpaceView struct {
	LexiconTypeID string `json:"$type"`
	Uri           string `json:"uri"`
}

// MarshalJSON sets $type to "com.atproto.space.listSpaces#spaceView" before encoding.
func (t ComAtprotoSpaceListSpacesSpaceView) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "com.atproto.space.listSpaces#spaceView"
	type alias ComAtprotoSpaceListSpacesSpaceView
	return json.Marshal(alias(t))
}
