package comatproto

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// ComAtprotoSpaceApplyWritesCreate represents a create object
type ComAtprotoSpaceApplyWritesCreate struct {
	LexiconTypeID string      `json:"$type"`
	Collection    string      `json:"collection"`
	Rkey          string      `json:"rkey,omitempty"`
	Value         interface{} `json:"value"`
}

// MarshalJSON sets $type to "com.atproto.space.applyWrites#create" before encoding.
func (t ComAtprotoSpaceApplyWritesCreate) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "com.atproto.space.applyWrites#create"
	type alias ComAtprotoSpaceApplyWritesCreate
	return json.Marshal(alias(t))
}

// ComAtprotoSpaceApplyWritesCreateResult represents a createResult object
type ComAtprotoSpaceApplyWritesCreateResult struct {
	LexiconTypeID    string `json:"$type"`
	Cid              string `json:"cid"`
	Uri              string `json:"uri"`
	ValidationStatus string `json:"validationStatus,omitempty"`
}

// MarshalJSON sets $type to "com.atproto.space.applyWrites#createResult" before encoding.
func (t ComAtprotoSpaceApplyWritesCreateResult) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "com.atproto.space.applyWrites#createResult"
	type alias ComAtprotoSpaceApplyWritesCreateResult
	return json.Marshal(alias(t))
}

// ComAtprotoSpaceApplyWritesDelete represents a delete object
type ComAtprotoSpaceApplyWritesDelete struct {
	LexiconTypeID string `json:"$type"`
	Collection    string `json:"collection"`
	Rkey          string `json:"rkey"`
}

// MarshalJSON sets $type to "com.atproto.space.applyWrites#delete" before encoding.
func (t ComAtprotoSpaceApplyWritesDelete) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "com.atproto.space.applyWrites#delete"
	type alias ComAtprotoSpaceApplyWritesDelete
	return json.Marshal(alias(t))
}

// ComAtprotoSpaceApplyWritesDeleteResult represents a deleteResult object
type ComAtprotoSpaceApplyWritesDeleteResult struct {
	LexiconTypeID string `json:"$type"`
}

// MarshalJSON sets $type to "com.atproto.space.applyWrites#deleteResult" before encoding.
func (t ComAtprotoSpaceApplyWritesDeleteResult) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "com.atproto.space.applyWrites#deleteResult"
	type alias ComAtprotoSpaceApplyWritesDeleteResult
	return json.Marshal(alias(t))
}

// ComAtprotoSpaceApplyWritesInput represents the input for com.atproto.space.applyWrites
type ComAtprotoSpaceApplyWritesInput struct {
	Repo     string        `json:"repo"`
	Space    string        `json:"space"`
	Validate bool          `json:"validate,omitempty"`
	Writes   []interface{} `json:"writes"`
}

// ComAtprotoSpaceApplyWritesOutput represents the output for com.atproto.space.applyWrites
type ComAtprotoSpaceApplyWritesOutput struct {
	Results []interface{} `json:"results,omitempty"`
}

// ComAtprotoSpaceApplyWritesUpdate represents a update object
type ComAtprotoSpaceApplyWritesUpdate struct {
	LexiconTypeID string      `json:"$type"`
	Collection    string      `json:"collection"`
	Rkey          string      `json:"rkey"`
	Value         interface{} `json:"value"`
}

// MarshalJSON sets $type to "com.atproto.space.applyWrites#update" before encoding.
func (t ComAtprotoSpaceApplyWritesUpdate) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "com.atproto.space.applyWrites#update"
	type alias ComAtprotoSpaceApplyWritesUpdate
	return json.Marshal(alias(t))
}

// ComAtprotoSpaceApplyWritesUpdateResult represents a updateResult object
type ComAtprotoSpaceApplyWritesUpdateResult struct {
	LexiconTypeID    string `json:"$type"`
	Cid              string `json:"cid"`
	Uri              string `json:"uri"`
	ValidationStatus string `json:"validationStatus,omitempty"`
}

// MarshalJSON sets $type to "com.atproto.space.applyWrites#updateResult" before encoding.
func (t ComAtprotoSpaceApplyWritesUpdateResult) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "com.atproto.space.applyWrites#updateResult"
	type alias ComAtprotoSpaceApplyWritesUpdateResult
	return json.Marshal(alias(t))
}
