package comatproto

// Code generated by lexgen. DO NOT EDIT.

import "github.com/bluesky-social/indigo/atproto/atdata"

// ComAtprotoSpaceNotifyWriteInput represents the input for com.atproto.space.notifyWrite
type ComAtprotoSpaceNotifyWriteInput struct {
	Hash         atdata.Bytes `json:"hash"`
	PrevSpaceRev string       `json:"prevSpaceRev,omitempty"`
	Repo         string       `json:"repo"`
	RepoRev      string       `json:"repoRev"`
	Space        string       `json:"space"`
	SpaceRev     string       `json:"spaceRev,omitempty"`
}
