package comatproto

// Code generated by lexgen. DO NOT EDIT.

// ComAtprotoSpaceRegisterNotifyInput represents the input for com.atproto.space.registerNotify
type ComAtprotoSpaceRegisterNotifyInput struct {
	Service string `json:"service"`
	Space   string `json:"space"`
}

// ComAtprotoSpaceRegisterNotifyOutput represents the output for com.atproto.space.registerNotify
type ComAtprotoSpaceRegisterNotifyOutput struct {
	ExpiresAt string `json:"expiresAt"`
}
