package comatproto

// Code generated by lexgen. DO NOT EDIT.

// ComAtprotoSpacePutRecordInput represents the input for com.atproto.space.putRecord
type ComAtprotoSpacePutRecordInput struct {
	Collection string      `json:"collection"`
	Record     interface{} `json:"record"`
	Repo       string      `json:"repo"`
	Rkey       string      `json:"rkey"`
	Space      string      `json:"space"`
	Validate   bool        `json:"validate,omitempty"`
}

// ComAtprotoSpacePutRecordOutput represents the output for com.atproto.space.putRecord
type ComAtprotoSpacePutRecordOutput struct {
	Cid              string `json:"cid"`
	Uri              string `json:"uri"`
	ValidationStatus string `json:"validationStatus,omitempty"`
}
