package comatproto

// Code generated by lexgen. DO NOT EDIT.

// ComAtprotoSpaceCreateRecordInput represents the input for com.atproto.space.createRecord
type ComAtprotoSpaceCreateRecordInput struct {
	Collection string      `json:"collection"`
	Record     interface{} `json:"record"`
	Repo       string      `json:"repo"`
	Rkey       string      `json:"rkey,omitempty"`
	Space      string      `json:"space"`
	Validate   bool        `json:"validate,omitempty"`
}

// ComAtprotoSpaceCreateRecordOutput represents the output for com.atproto.space.createRecord
type ComAtprotoSpaceCreateRecordOutput struct {
	Cid              string `json:"cid"`
	Uri              string `json:"uri"`
	ValidationStatus string `json:"validationStatus,omitempty"`
}
