package comatproto

// Code generated by lexgen. DO NOT EDIT.

// ComAtprotoSpaceListBlobsParams represents the input parameters for com.atproto.space.listBlobs
type ComAtprotoSpaceListBlobsParams struct {
	Cursor string `json:"cursor,omitempty"`
	Limit  int64  `json:"limit,omitempty"`
	Repo   string `json:"repo"`
	Since  string `json:"since,omitempty"`
	Space  string `json:"space"`
}

// ComAtprotoSpaceListBlobsOutput represents the output for com.atproto.space.listBlobs
type ComAtprotoSpaceListBlobsOutput struct {
	Cids   []string `json:"cids"`
	Cursor string   `json:"cursor,omitempty"`
}
