package comatproto

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// ComAtprotoSpaceListRepoOpsParams represents the input parameters for com.atproto.space.listRepoOps
type ComAtprotoSpaceListRepoOpsParams struct {
	Cursor        string `json:"cursor,omitempty"`
	ExcludeValues bool   `json:"excludeValues,omitempty"`
	Limit         int64  `json:"limit,omitempty"`
	Repo          string `json:"repo"`
	Since         string `json:"since,omitempty"`
	Space         string `json:"space"`
}

// ComAtprotoSpaceListRepoOpsOutput represents the output for com.atproto.space.listRepoOps
type ComAtprotoSpaceListRepoOpsOutput struct {
	Commit *ComAtprotoSpaceDefsSignedCommit    `json:"commit,omitempty"`
	Cursor string                              `json:"cursor,omitempty"`
	Ops    []ComAtprotoSpaceListRepoOpsOpEntry `json:"ops"`
}

// ComAtprotoSpaceListRepoOpsOpEntry represents a opEntry object
type ComAtprotoSpaceListRepoOpsOpEntry struct {
	LexiconTypeID string      `json:"$type"`
	Cid           string      `json:"cid"`
	Collection    string      `json:"collection"`
	Prev          string      `json:"prev"`
	Rev           string      `json:"rev"`
	Rkey          string      `json:"rkey"`
	Value         interface{} `json:"value,omitempty"`
}

// MarshalJSON sets $type to "com.atproto.space.listRepoOps#opEntry" before encoding.
func (t ComAtprotoSpaceListRepoOpsOpEntry) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "com.atproto.space.listRepoOps#opEntry"
	type alias ComAtprotoSpaceListRepoOpsOpEntry
	return json.Marshal(alias(t))
}
