package comatproto

// Code generated by lexgen. DO NOT EDIT.

import "encoding/json"

// ComAtprotoSpaceListRecordsParams represents the input parameters for com.atproto.space.listRecords
type ComAtprotoSpaceListRecordsParams struct {
	Collection    string `json:"collection,omitempty"`
	Cursor        string `json:"cursor,omitempty"`
	ExcludeValues bool   `json:"excludeValues,omitempty"`
	Limit         int64  `json:"limit,omitempty"`
	Repo          string `json:"repo"`
	Reverse       bool   `json:"reverse,omitempty"`
	Space         string `json:"space"`
}

// ComAtprotoSpaceListRecordsOutput represents the output for com.atproto.space.listRecords
type ComAtprotoSpaceListRecordsOutput struct {
	Cursor  string                             `json:"cursor,omitempty"`
	Records []ComAtprotoSpaceListRecordsRecord `json:"records"`
}

// ComAtprotoSpaceListRecordsRecord represents a record object
type ComAtprotoSpaceListRecordsRecord struct {
	LexiconTypeID string      `json:"$type"`
	Cid           string      `json:"cid"`
	Collection    string      `json:"collection"`
	Rkey          string      `json:"rkey"`
	Value         interface{} `json:"value,omitempty"`
}

// MarshalJSON sets $type to "com.atproto.space.listRecords#record" before encoding.
func (t ComAtprotoSpaceListRecordsRecord) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "com.atproto.space.listRecords#record"
	type alias ComAtprotoSpaceListRecordsRecord
	return json.Marshal(alias(t))
}
