package comatproto

// Code generated by lexgen. DO NOT EDIT.

// ComAtprotoSpaceNotifySpaceDeletedInput represents the input for com.atproto.space.notifySpaceDeleted
type ComAtprotoSpaceNotifySpaceDeletedInput struct {
	Space string `json:"space"`
}
