/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RequireAuthRouteImport } from './routes/_requireAuth'
import { Route as DevtoolsRouteImport } from './routes/devtools'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OauthLoginRouteImport } from './routes/oauth-login'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as RequireAuthIndexRouteImport } from './routes/_requireAuth/index'
import { Route as RequireAuthDataRouteImport } from './routes/_requireAuth/data'
import { Route as RequireAuthPermissionsRouteImport } from './routes/_requireAuth/permissions'
import { Route as RequireAuthSearchRouteImport } from './routes/_requireAuth/search'
import { Route as CommunityCreateRouteImport } from './routes/community/create'
import { Route as LoginHabitatRouteImport } from './routes/login/habitat'
import { Route as RequireAuthBlobTestIndexRouteImport } from './routes/_requireAuth/blob-test/index'
import { Route as RequireAuthOrgsIndexRouteImport } from './routes/_requireAuth/orgs/index'
import { Route as RequireAuthOrgsOrgRouteImport } from './routes/_requireAuth/orgs/$org'
import { Route as RequireAuthPearTestIndexRouteImport } from './routes/_requireAuth/pear-test/index'
import { Route as RequireAuthPearTestViewRouteImport } from './routes/_requireAuth/pear-test/view'
import { Route as RequireAuthPermissionsIndexRouteImport } from './routes/_requireAuth/permissions/index'
import { Route as RequireAuthPermissionsLexiconsRouteImport } from './routes/_requireAuth/permissions/lexicons'
import { Route as RequireAuthPermissionsPeopleRouteImport } from './routes/_requireAuth/permissions/people'
import { Route as RequireAuthSpacesIndexRouteImport } from './routes/_requireAuth/spaces/index'
import { Route as RequireAuthOrgsOrgIndexRouteImport } from './routes/_requireAuth/orgs/$org/index'
import { Route as RequireAuthOrgsOrgSettingsRouteImport } from './routes/_requireAuth/orgs/$org/settings'
import { Route as RequireAuthPermissionsLexiconsIndexRouteImport } from './routes/_requireAuth/permissions/lexicons/index'
import { Route as RequireAuthPermissionsLexiconsCollectionRouteImport } from './routes/_requireAuth/permissions/lexicons/$collection'
import { Route as RequireAuthPermissionsPeopleDidRouteImport } from './routes/_requireAuth/permissions/people/$did'
import { Route as RequireAuthSpacesSpaceOwnerIndexRouteImport } from './routes/_requireAuth/spaces/$spaceOwner.index'
import { Route as RequireAuthSpacesTypeSpaceTypeRouteImport } from './routes/_requireAuth/spaces/type.$spaceType'
import { Route as RequireAuthOrgsOrgSettingsIndexRouteImport } from './routes/_requireAuth/orgs/$org/settings/index'
import { Route as RequireAuthOrgsOrgSettingsAppsRouteImport } from './routes/_requireAuth/orgs/$org/settings/apps'
import { Route as RequireAuthOrgsOrgSettingsBrandingRouteImport } from './routes/_requireAuth/orgs/$org/settings/branding'
import { Route as RequireAuthOrgsOrgSettingsCapabilitiesRouteImport } from './routes/_requireAuth/orgs/$org/settings/capabilities'
import { Route as RequireAuthOrgsOrgSettingsMcpRouteImport } from './routes/_requireAuth/orgs/$org/settings/mcp'
import { Route as RequireAuthOrgsOrgSettingsMembersRouteImport } from './routes/_requireAuth/orgs/$org/settings/members'
import { Route as RequireAuthOrgsOrgSettingsRolesRouteImport } from './routes/_requireAuth/orgs/$org/settings/roles'
import { Route as RequireAuthOrgsOrgSettingsSearchRouteImport } from './routes/_requireAuth/orgs/$org/settings/search'
import { Route as RequireAuthSpacesSpaceOwnerSpaceTypeIndexRouteImport } from './routes/_requireAuth/spaces/$spaceOwner.$spaceType.index'
import { Route as RequireAuthOrgsOrgSettingsAppClientKeyRouteImport } from './routes/_requireAuth/orgs/$org/settings/app.$clientKey'
import { Route as RequireAuthSpacesSpaceOwnerSpaceTypeSpaceKeyIndexRouteImport } from './routes/_requireAuth/spaces/$spaceOwner.$spaceType.$spaceKey.index'
import { Route as RequireAuthSpacesSpaceOwnerSpaceTypeSpaceKeyRecordOwnerIndexRouteImport } from './routes/_requireAuth/spaces/$spaceOwner.$spaceType.$spaceKey.$recordOwner.index'
import { Route as RequireAuthSpacesSpaceOwnerSpaceTypeSpaceKeyRecordOwnerRecordTypeRecordKeyRouteImport } from './routes/_requireAuth/spaces/$spaceOwner.$spaceType.$spaceKey.$recordOwner.$recordType.$recordKey'

const RequireAuthRoute = RequireAuthRouteImport.update({
  id: '/_requireAuth',
  getParentRoute: () => rootRouteImport,
} as any)
const DevtoolsRoute = DevtoolsRouteImport.update({
  id: '/devtools',
  path: '/devtools',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthLoginRoute = OauthLoginRouteImport.update({
  id: '/oauth-login',
  path: '/oauth-login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RequireAuthIndexRoute = RequireAuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RequireAuthRoute,
} as any)
const RequireAuthDataRoute = RequireAuthDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => RequireAuthRoute,
} as any)
const RequireAuthPermissionsRoute = RequireAuthPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => RequireAuthRoute,
} as any)
const RequireAuthSearchRoute = RequireAuthSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => RequireAuthRoute,
} as any)
const CommunityCreateRoute = CommunityCreateRouteImport.update({
  id: '/community/create',
  path: '/community/create',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginHabitatRoute = LoginHabitatRouteImport.update({
  id: '/habitat',
  path: '/habitat',
  getParentRoute: () => LoginRoute,
} as any)
const RequireAuthBlobTestIndexRoute =
  RequireAuthBlobTestIndexRouteImport.update({
    id: '/blob-test/',
    path: '/blob-test/',
    getParentRoute: () => RequireAuthRoute,
  } as any)
const RequireAuthOrgsIndexRoute = RequireAuthOrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => RequireAuthRoute,
} as any)
const RequireAuthOrgsOrgRoute = RequireAuthOrgsOrgRouteImport.update({
  id: '/orgs/$org',
  path: '/orgs/$org',
  getParentRoute: () => RequireAuthRoute,
} as any)
const RequireAuthPearTestIndexRoute =
  RequireAuthPearTestIndexRouteImport.update({
    id: '/pear-test/',
    path: '/pear-test/',
    getParentRoute: () => RequireAuthRoute,
  } as any)
const RequireAuthPearTestViewRoute = RequireAuthPearTestViewRouteImport.update({
  id: '/pear-test/view',
  path: '/pear-test/view',
  getParentRoute: () => RequireAuthRoute,
} as any)
const RequireAuthPermissionsIndexRoute =
  RequireAuthPermissionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RequireAuthPermissionsRoute,
  } as any)
const RequireAuthPermissionsLexiconsRoute =
  RequireAuthPermissionsLexiconsRouteImport.update({
    id: '/lexicons',
    path: '/lexicons',
    getParentRoute: () => RequireAuthPermissionsRoute,
  } as any)
const RequireAuthPermissionsPeopleRoute =
  RequireAuthPermissionsPeopleRouteImport.update({
    id: '/people',
    path: '/people',
    getParentRoute: () => RequireAuthPermissionsRoute,
  } as any)
const RequireAuthSpacesIndexRoute = RequireAuthSpacesIndexRouteImport.update({
  id: '/spaces/',
  path: '/spaces/',
  getParentRoute: () => RequireAuthRoute,
} as any)
const RequireAuthOrgsOrgIndexRoute = RequireAuthOrgsOrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RequireAuthOrgsOrgRoute,
} as any)
const RequireAuthOrgsOrgSettingsRoute =
  RequireAuthOrgsOrgSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => RequireAuthOrgsOrgRoute,
  } as any)
const RequireAuthPermissionsLexiconsIndexRoute =
  RequireAuthPermissionsLexiconsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RequireAuthPermissionsLexiconsRoute,
  } as any)
const RequireAuthPermissionsLexiconsCollectionRoute =
  RequireAuthPermissionsLexiconsCollectionRouteImport.update({
    id: '/$collection',
    path: '/$collection',
    getParentRoute: () => RequireAuthPermissionsLexiconsRoute,
  } as any)
const RequireAuthPermissionsPeopleDidRoute =
  RequireAuthPermissionsPeopleDidRouteImport.update({
    id: '/$did',
    path: '/$did',
    getParentRoute: () => RequireAuthPermissionsPeopleRoute,
  } as any)
const RequireAuthSpacesSpaceOwnerIndexRoute =
  RequireAuthSpacesSpaceOwnerIndexRouteImport.update({
    id: '/spaces/$spaceOwner/',
    path: '/spaces/$spaceOwner/',
    getParentRoute: () => RequireAuthRoute,
  } as any)
const RequireAuthSpacesTypeSpaceTypeRoute =
  RequireAuthSpacesTypeSpaceTypeRouteImport.update({
    id: '/spaces/type/$spaceType',
    path: '/spaces/type/$spaceType',
    getParentRoute: () => RequireAuthRoute,
  } as any)
const RequireAuthOrgsOrgSettingsIndexRoute =
  RequireAuthOrgsOrgSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RequireAuthOrgsOrgSettingsRoute,
  } as any)
const RequireAuthOrgsOrgSettingsAppsRoute =
  RequireAuthOrgsOrgSettingsAppsRouteImport.update({
    id: '/apps',
    path: '/apps',
    getParentRoute: () => RequireAuthOrgsOrgSettingsRoute,
  } as any)
const RequireAuthOrgsOrgSettingsBrandingRoute =
  RequireAuthOrgsOrgSettingsBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => RequireAuthOrgsOrgSettingsRoute,
  } as any)
const RequireAuthOrgsOrgSettingsCapabilitiesRoute =
  RequireAuthOrgsOrgSettingsCapabilitiesRouteImport.update({
    id: '/capabilities',
    path: '/capabilities',
    getParentRoute: () => RequireAuthOrgsOrgSettingsRoute,
  } as any)
const RequireAuthOrgsOrgSettingsMcpRoute =
  RequireAuthOrgsOrgSettingsMcpRouteImport.update({
    id: '/mcp',
    path: '/mcp',
    getParentRoute: () => RequireAuthOrgsOrgSettingsRoute,
  } as any)
const RequireAuthOrgsOrgSettingsMembersRoute =
  RequireAuthOrgsOrgSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => RequireAuthOrgsOrgSettingsRoute,
  } as any)
const RequireAuthOrgsOrgSettingsRolesRoute =
  RequireAuthOrgsOrgSettingsRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => RequireAuthOrgsOrgSettingsRoute,
  } as any)
const RequireAuthOrgsOrgSettingsSearchRoute =
  RequireAuthOrgsOrgSettingsSearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => RequireAuthOrgsOrgSettingsRoute,
  } as any)
const RequireAuthSpacesSpaceOwnerSpaceTypeIndexRoute =
  RequireAuthSpacesSpaceOwnerSpaceTypeIndexRouteImport.update({
    id: '/spaces/$spaceOwner/$spaceType/',
    path: '/spaces/$spaceOwner/$spaceType/',
    getParentRoute: () => RequireAuthRoute,
  } as any)
const RequireAuthOrgsOrgSettingsAppClientKeyRoute =
  RequireAuthOrgsOrgSettingsAppClientKeyRouteImport.update({
    id: '/app/$clientKey',
    path: '/app/$clientKey',
    getParentRoute: () => RequireAuthOrgsOrgSettingsRoute,
  } as any)
const RequireAuthSpacesSpaceOwnerSpaceTypeSpaceKeyIndexRoute =
  RequireAuthSpacesSpaceOwnerSpaceTypeSpaceKeyIndexRouteImport.update({
    id: '/spaces/$spaceOwner/$spaceType/$spaceKey/',
    path: '/spaces/$spaceOwner/$spaceType/$spaceKey/',
    getParentRoute: () => RequireAuthRoute,
  } as any)
const RequireAuthSpacesSpaceOwnerSpaceTypeSpaceKeyRecordOwnerIndexRoute =
  RequireAuthSpacesSpaceOwnerSpaceTypeSpaceKeyRecordOwnerIndexRouteImport.update(
    {
      id: '/spaces/$spaceOwner/$spaceType/$spaceKey/$recordOwner/',
      path: '/spaces/$spaceOwner/$spaceType/$spaceKey/$recordOwner/',
      getParentRoute: () => RequireAuthRoute,
    } as any,
  )
const RequireAuthSpacesSpaceOwnerSpaceTypeSpaceKeyRecordOwnerRecordTypeRecordKeyRoute =
  RequireAuthSpacesSpaceOwnerSpaceTypeSpaceKeyRecordOwnerRecordTypeRecordKeyRouteImport.update(
    {
      id: '/spaces/$spaceOwner/$spaceType/$spaceKey/$recordOwner/$recordType/$recordKey',
      path: '/spaces/$spaceOwner/$spaceType/$spaceKey/$recordOwner/$recordType/$recordKey',
      getParentRoute: () => RequireAuthRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof RequireAuthIndexRoute
  '/devtools': typeof DevtoolsRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRouteWithChildren
  '/oauth-login': typeof OauthLoginRoute
  '/onboard': typeof OnboardRoute
  '/data': typeof RequireAuthDataRoute
  '/permissions': typeof RequireAuthPermissionsRouteWithChildren
  '/search': typeof RequireAuthSearchRoute
  '/community/create': typeof CommunityCreateRoute
  '/login/habitat': typeof LoginHabitatRoute
  '/orgs/$org': typeof RequireAuthOrgsOrgRouteWithChildren
  '/pear-test/view': typeof RequireAuthPearTestViewRoute
  '/permissions/lexicons': typeof RequireAuthPermissionsLexiconsRouteWithChildren
  '/permissions/people': typeof RequireAuthPermissionsPeopleRouteWithChildren
  '/blob-test/': typeof RequireAuthBlobTestIndexRoute
  '/orgs/': typeof RequireAuthOrgsIndexRoute
  '/pear-test/': typeof RequireAuthPearTestIndexRoute
  '/permissions/': typeof RequireAuthPermissionsIndexRoute
  '/spaces/': typeof RequireAuthSpacesIndexRoute
  '/orgs/$org/settings': typeof RequireAuthOrgsOrgSettingsRouteWithChildren
  '/permissions/lexicons/$collection': typeof RequireAuthPermissionsLexiconsCollectionRoute
  '/permissions/people/$did': typeof RequireAuthPermissionsPeopleDidRoute
  '/spaces/type/$spaceType': typeof RequireAuthSpacesTypeSpaceTypeRoute
  '/orgs/$org/': typeof RequireAuthOrgsOrgIndexRoute
  '/permissions/lexicons/': typeof RequireAuthPermissionsLexiconsIndexRoute
  '/spaces/$spaceOwner/': typeof RequireAuthSpacesSpaceOwnerIndexRoute
  '/orgs/$org/settings/apps': typeof RequireAuthOrgsOrgSettingsAppsRoute
  '/orgs/$org/settings/branding': typeof RequireAuthOrgsOrgSettingsBrandingRoute
  '/orgs/$org/settings/capabilities': typeof RequireAuthOrgsOrgSettingsCapabilitiesRoute
  '/orgs/$org/settings/mcp': typeof RequireAuthOrgsOrgSettingsMcpRoute
  '/orgs/$org/settings/members': typeof RequireAuthOrgsOrgSettingsMembersRoute
  '/orgs/$org/settings/roles': typeof RequireAuthOrgsOrgSettingsRolesRoute
  '/orgs/$org/settings/search': typeof RequireAuthOrgsOrgSettingsSearchRoute
  '/orgs/$org/settings/': typeof RequireAuthOrgsOrgSettingsIndexRoute
  '/spaces/$spaceOwner/$spaceType/': typeof RequireAuthSpacesSpaceOwnerSpaceTypeIndexRoute
  '/orgs/$org/settings/app/$clientKey': typeof RequireAuthOrgsOrgSettingsAppClientKeyRoute
  '/spaces/$spaceOwner/$spaceType/$spaceKey/': typeof RequireAuthSpacesSpaceOwnerSpaceTypeSpaceKeyIndexRoute
  '/spaces/$spaceOwner/$spaceType/$spaceKey/$recordOwner/': typeof RequireAuthSpacesSpaceOwnerSpaceTypeSpaceKeyRecordOwnerIndexRoute
  '/spaces/$spaceOwner/$spaceType/$spaceKey/$recordOwner/$recordType/$recordKey': typeof RequireAuthSpacesSpaceOwnerSpaceTypeSpaceKeyRecordOwnerRecordTypeRecordKeyRoute
}
export interface FileRoutesByTo {
  '/devtools': typeof DevtoolsRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRouteWithChildren
  '/oauth-login': typeof OauthLoginRoute
  '/onboard': typeof OnboardRoute
  '/data': typeof RequireAuthDataRoute
  '/search': typeof RequireAuthSearchRoute
  '/community/create': typeof CommunityCreateRoute
  '/login/habitat': typeof LoginHabitatRoute
  '/': typeof RequireAuthIndexRoute
  '/pear-test/view': typeof RequireAuthPearTestViewRoute
  '/permissions/people': typeof RequireAuthPermissionsPeopleRouteWithChildren
  '/blob-test': typeof RequireAuthBlobTestIndexRoute
  '/orgs': typeof RequireAuthOrgsIndexRoute
  '/pear-test': typeof RequireAuthPearTestIndexRoute
  '/permissions': typeof RequireAuthPermissionsIndexRoute
  '/spaces': typeof RequireAuthSpacesIndexRoute
  '/permissions/lexicons/$collection': typeof RequireAuthPermissionsLexiconsCollectionRoute
  '/permissions/people/$did': typeof RequireAuthPermissionsPeopleDidRoute
  '/spaces/type/$spaceType': typeof RequireAuthSpacesTypeSpaceTypeRoute
  '/orgs/$org': typeof RequireAuthOrgsOrgIndexRoute
  '/permissions/lexicons': typeof RequireAuthPermissionsLexiconsIndexRoute
  '/spaces/$spaceOwner': typeof RequireAuthSpacesSpaceOwnerIndexRoute
  '/orgs/$org/settings/apps': typeof RequireAuthOrgsOrgSettingsAppsRoute
  '/orgs/$org/settings/branding': typeof RequireAuthOrgsOrgSettingsBrandingRoute
  '/orgs/$org/settings/capabilities': typeof RequireAuthOrgsOrgSettingsCapabilitiesRoute
  '/orgs/$org/settings/mcp': typeof RequireAuthOrgsOrgSettingsMcpRoute
  '/orgs/$org/settings/members': typeof RequireAuthOrgsOrgSettingsMembersRoute
  '/orgs/$org/settings/roles': typeof RequireAuthOrgsOrgSettingsRolesRoute
  '/orgs/$org/settings/search': typeof RequireAuthOrgsOrgSettingsSearchRoute
  '/orgs/$org/settings': typeof RequireAuthOrgsOrgSettingsIndexRoute
  '/spaces/$spaceOwner/$spaceType': typeof RequireAuthSpacesSpaceOwnerSpaceTypeIndexRoute
  '/orgs/$org/settings/app/$clientKey': typeof RequireAuthOrgsOrgSettingsAppClientKeyRoute
  '/spaces/$spaceOwner/$spaceType/$spaceKey': typeof RequireAuthSpacesSpaceOwnerSpaceTypeSpaceKeyIndexRoute
  '/spaces/$spaceOwner/$spaceType/$spaceKey/$recordOwner': typeof RequireAuthSpacesSpaceOwnerSpaceTypeSpaceKeyRecordOwnerIndexRoute
  '/spaces/$spaceOwner/$spaceType/$spaceKey/$recordOwner/$recordType/$recordKey': typeof RequireAuthSpacesSpaceOwnerSpaceTypeSpaceKeyRecordOwnerRecordTypeRecordKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_requireAuth': typeof RequireAuthRouteWithChildren
  '/devtools': typeof DevtoolsRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRouteWithChildren
  '/oauth-login': typeof OauthLoginRoute
  '/onboard': typeof OnboardRoute
  '/_requireAuth/data': typeof RequireAuthDataRoute
  '/_requireAuth/permissions': typeof RequireAuthPermissionsRouteWithChildren
  '/_requireAuth/search': typeof RequireAuthSearchRoute
  '/community/create': typeof CommunityCreateRoute
  '/login/habitat': typeof LoginHabitatRoute
  '/_requireAuth/': typeof RequireAuthIndexRoute
  '/_requireAuth/orgs/$org': typeof RequireAuthOrgsOrgRouteWithChildren
  '/_requireAuth/pear-test/view': typeof RequireAuthPearTestViewRoute
  '/_requireAuth/permissions/lexicons': typeof RequireAuthPermissionsLexiconsRouteWithChildren
  '/_requireAuth/permissions/people': typeof RequireAuthPermissionsPeopleRouteWithChildren
  '/_requireAuth/blob-test/': typeof RequireAuthBlobTestIndexRoute
  '/_requireAuth/orgs/': typeof RequireAuthOrgsIndexRoute
  '/_requireAuth/pear-test/': typeof RequireAuthPearTestIndexRoute
  '/_requireAuth/permissions/': typeof RequireAuthPermissionsIndexRoute
  '/_requireAuth/spaces/': typeof RequireAuthSpacesIndexRoute
  '/_requireAuth/orgs/$org/settings': typeof RequireAuthOrgsOrgSettingsRouteWithChildren
  '/_requireAuth/permissions/lexicons/$collection': typeof RequireAuthPermissionsLexiconsCollectionRoute
  '/_requireAuth/permissions/people/$did': typeof RequireAuthPermissionsPeopleDidRoute
  '/_requireAuth/spaces/type/$spaceType': typeof RequireAuthSpacesTypeSpaceTypeRoute
  '/_requireAuth/orgs/$org/': typeof RequireAuthOrgsOrgIndexRoute
  '/_requireAuth/permissions/lexicons/': typeof RequireAuthPermissionsLexiconsIndexRoute
  '/_requireAuth/spaces/$spaceOwner/': typeof RequireAuthSpacesSpaceOwnerIndexRoute
  '/_requireAuth/orgs/$org/settings/apps': typeof RequireAuthOrgsOrgSettingsAppsRoute
  '/_requireAuth/orgs/$org/settings/branding': typeof RequireAuthOrgsOrgSettingsBrandingRoute
  '/_requireAuth/orgs/$org/settings/capabilities': typeof RequireAuthOrgsOrgSettingsCapabilitiesRoute
  '/_requireAuth/orgs/$org/settings/mcp': typeof RequireAuthOrgsOrgSettingsMcpRoute
  '/_requireAuth/orgs/$org/settings/members': typeof RequireAuthOrgsOrgSettingsMembersRoute
  '/_requireAuth/orgs/$org/settings/roles': typeof RequireAuthOrgsOrgSettingsRolesRoute
  '/_requireAuth/orgs/$org/settings/search': typeof RequireAuthOrgsOrgSettingsSearchRoute
  '/_requireAuth/orgs/$org/settings/': typeof RequireAuthOrgsOrgSettingsIndexRoute
  '/_requireAuth/spaces/$spaceOwner/$spaceType/': typeof RequireAuthSpacesSpaceOwnerSpaceTypeIndexRoute
  '/_requireAuth/orgs/$org/settings/app/$clientKey': typeof RequireAuthOrgsOrgSettingsAppClientKeyRoute
  '/_requireAuth/spaces/$spaceOwner/$spaceType/$spaceKey/': typeof RequireAuthSpacesSpaceOwnerSpaceTypeSpaceKeyIndexRoute
  '/_requireAuth/spaces/$spaceOwner/$spaceType/$spaceKey/$recordOwner/': typeof RequireAuthSpacesSpaceOwnerSpaceTypeSpaceKeyRecordOwnerIndexRoute
  '/_requireAuth/spaces/$spaceOwner/$spaceType/$spaceKey/$recordOwner/$recordType/$recordKey': typeof RequireAuthSpacesSpaceOwnerSpaceTypeSpaceKeyRecordOwnerRecordTypeRecordKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/devtools'
    | '/explore'
    | '/login'
    | '/oauth-login'
    | '/onboard'
    | '/data'
    | '/permissions'
    | '/search'
    | '/community/create'
    | '/login/habitat'
    | '/orgs/$org'
    | '/pear-test/view'
    | '/permissions/lexicons'
    | '/permissions/people'
    | '/blob-test/'
    | '/orgs/'
    | '/pear-test/'
    | '/permissions/'
    | '/spaces/'
    | '/orgs/$org/settings'
    | '/permissions/lexicons/$collection'
    | '/permissions/people/$did'
    | '/spaces/type/$spaceType'
    | '/orgs/$org/'
    | '/permissions/lexicons/'
    | '/spaces/$spaceOwner/'
    | '/orgs/$org/settings/apps'
    | '/orgs/$org/settings/branding'
    | '/orgs/$org/settings/capabilities'
    | '/orgs/$org/settings/mcp'
    | '/orgs/$org/settings/members'
    | '/orgs/$org/settings/roles'
    | '/orgs/$org/settings/search'
    | '/orgs/$org/settings/'
    | '/spaces/$spaceOwner/$spaceType/'
    | '/orgs/$org/settings/app/$clientKey'
    | '/spaces/$spaceOwner/$spaceType/$spaceKey/'
    | '/spaces/$spaceOwner/$spaceType/$spaceKey/$recordOwner/'
    | '/spaces/$spaceOwner/$spaceType/$spaceKey/$recordOwner/$recordType/$recordKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/devtools'
    | '/explore'
    | '/login'
    | '/oauth-login'
    | '/onboard'
    | '/data'
    | '/search'
    | '/community/create'
    | '/login/habitat'
    | '/'
    | '/pear-test/view'
    | '/permissions/people'
    | '/blob-test'
    | '/orgs'
    | '/pear-test'
    | '/permissions'
    | '/spaces'
    | '/permissions/lexicons/$collection'
    | '/permissions/people/$did'
    | '/spaces/type/$spaceType'
    | '/orgs/$org'
    | '/permissions/lexicons'
    | '/spaces/$spaceOwner'
    | '/orgs/$org/settings/apps'
    | '/orgs/$org/settings/branding'
    | '/orgs/$org/settings/capabilities'
    | '/orgs/$org/settings/mcp'
    | '/orgs/$org/settings/members'
    | '/orgs/$org/settings/roles'
    | '/orgs/$org/settings/search'
    | '/orgs/$org/settings'
    | '/spaces/$spaceOwner/$spaceType'
    | '/orgs/$org/settings/app/$clientKey'
    | '/spaces/$spaceOwner/$spaceType/$spaceKey'
    | '/spaces/$spaceOwner/$spaceType/$spaceKey/$recordOwner'
    | '/spaces/$spaceOwner/$spaceType/$spaceKey/$recordOwner/$recordType/$recordKey'
  id:
    | '__root__'
    | '/_requireAuth'
    | '/devtools'
    | '/explore'
    | '/login'
    | '/oauth-login'
    | '/onboard'
    | '/_requireAuth/data'
    | '/_requireAuth/permissions'
    | '/_requireAuth/search'
    | '/community/create'
    | '/login/habitat'
    | '/_requireAuth/'
    | '/_requireAuth/orgs/$org'
    | '/_requireAuth/pear-test/view'
    | '/_requireAuth/permissions/lexicons'
    | '/_requireAuth/permissions/people'
    | '/_requireAuth/blob-test/'
    | '/_requireAuth/orgs/'
    | '/_requireAuth/pear-test/'
    | '/_requireAuth/permissions/'
    | '/_requireAuth/spaces/'
    | '/_requireAuth/orgs/$org/settings'
    | '/_requireAuth/permissions/lexicons/$collection'
    | '/_requireAuth/permissions/people/$did'
    | '/_requireAuth/spaces/type/$spaceType'
    | '/_requireAuth/orgs/$org/'
    | '/_requireAuth/permissions/lexicons/'
    | '/_requireAuth/spaces/$spaceOwner/'
    | '/_requireAuth/orgs/$org/settings/apps'
    | '/_requireAuth/orgs/$org/settings/branding'
    | '/_requireAuth/orgs/$org/settings/capabilities'
    | '/_requireAuth/orgs/$org/settings/mcp'
    | '/_requireAuth/orgs/$org/settings/members'
    | '/_requireAuth/orgs/$org/settings/roles'
    | '/_requireAuth/orgs/$org/settings/search'
    | '/_requireAuth/orgs/$org/settings/'
    | '/_requireAuth/spaces/$spaceOwner/$spaceType/'
    | '/_requireAuth/orgs/$org/settings/app/$clientKey'
    | '/_requireAuth/spaces/$spaceOwner/$spaceType/$spaceKey/'
    | '/_requireAuth/spaces/$spaceOwner/$spaceType/$spaceKey/$recordOwner/'
    | '/_requireAuth/spaces/$spaceOwner/$spaceType/$spaceKey/$recordOwner/$recordType/$recordKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RequireAuthRoute: typeof RequireAuthRouteWithChildren
  DevtoolsRoute: typeof DevtoolsRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRouteWithChildren
  OauthLoginRoute: typeof OauthLoginRoute
  OnboardRoute: typeof OnboardRoute
  CommunityCreateRoute: typeof CommunityCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_requireAuth': {
      id: '/_requireAuth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof RequireAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devtools': {
      id: '/devtools'
      path: '/devtools'
      fullPath: '/devtools'
      preLoaderRoute: typeof DevtoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth-login': {
      id: '/oauth-login'
      path: '/oauth-login'
      fullPath: '/oauth-login'
      preLoaderRoute: typeof OauthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_requireAuth/': {
      id: '/_requireAuth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RequireAuthIndexRouteImport
      parentRoute: typeof RequireAuthRoute
    }
    '/_requireAuth/data': {
      id: '/_requireAuth/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof RequireAuthDataRouteImport
      parentRoute: typeof RequireAuthRoute
    }
    '/_requireAuth/permissions': {
      id: '/_requireAuth/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof RequireAuthPermissionsRouteImport
      parentRoute: typeof RequireAuthRoute
    }
    '/_requireAuth/search': {
      id: '/_requireAuth/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof RequireAuthSearchRouteImport
      parentRoute: typeof RequireAuthRoute
    }
    '/community/create': {
      id: '/community/create'
      path: '/community/create'
      fullPath: '/community/create'
      preLoaderRoute: typeof CommunityCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/habitat': {
      id: '/login/habitat'
      path: '/habitat'
      fullPath: '/login/habitat'
      preLoaderRoute: typeof LoginHabitatRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_requireAuth/blob-test/': {
      id: '/_requireAuth/blob-test/'
      path: '/blob-test'
      fullPath: '/blob-test/'
      preLoaderRoute: typeof RequireAuthBlobTestIndexRouteImport
      parentRoute: typeof RequireAuthRoute
    }
    '/_requireAuth/orgs/': {
      id: '/_requireAuth/orgs/'
      path: '/orgs'
      fullPath: '/orgs/'
      preLoaderRoute: typeof RequireAuthOrgsIndexRouteImport
      parentRoute: typeof RequireAuthRoute
    }
    '/_requireAuth/orgs/$org': {
      id: '/_requireAuth/orgs/$org'
      path: '/orgs/$org'
      fullPath: '/orgs/$org'
      preLoaderRoute: typeof RequireAuthOrgsOrgRouteImport
      parentRoute: typeof RequireAuthRoute
    }
    '/_requireAuth/pear-test/': {
      id: '/_requireAuth/pear-test/'
      path: '/pear-test'
      fullPath: '/pear-test/'
      preLoaderRoute: typeof RequireAuthPearTestIndexRouteImport
      parentRoute: typeof RequireAuthRoute
    }
    '/_requireAuth/pear-test/view': {
      id: '/_requireAuth/pear-test/view'
      path: '/pear-test/view'
      fullPath: '/pear-test/view'
      preLoaderRoute: typeof RequireAuthPearTestViewRouteImport
      parentRoute: typeof RequireAuthRoute
    }
    '/_requireAuth/permissions/': {
      id: '/_requireAuth/permissions/'
      path: '/'
      fullPath: '/permissions/'
      preLoaderRoute: typeof RequireAuthPermissionsIndexRouteImport
      parentRoute: typeof RequireAuthPermissionsRoute
    }
    '/_requireAuth/permissions/lexicons': {
      id: '/_requireAuth/permissions/lexicons'
      path: '/lexicons'
      fullPath: '/permissions/lexicons'
      preLoaderRoute: typeof RequireAuthPermissionsLexiconsRouteImport
      parentRoute: typeof RequireAuthPermissionsRoute
    }
    '/_requireAuth/permissions/people': {
      id: '/_requireAuth/permissions/people'
      path: '/people'
      fullPath: '/permissions/people'
      preLoaderRoute: typeof RequireAuthPermissionsPeopleRouteImport
      parentRoute: typeof RequireAuthPermissionsRoute
    }
    '/_requireAuth/spaces/': {
      id: '/_requireAuth/spaces/'
      path: '/spaces'
      fullPath: '/spaces/'
      preLoaderRoute: typeof RequireAuthSpacesIndexRouteImport
      parentRoute: typeof RequireAuthRoute
    }
    '/_requireAuth/orgs/$org/': {
      id: '/_requireAuth/orgs/$org/'
      path: '/'
      fullPath: '/orgs/$org/'
      preLoaderRoute: typeof RequireAuthOrgsOrgIndexRouteImport
      parentRoute: typeof RequireAuthOrgsOrgRoute
    }
    '/_requireAuth/orgs/$org/settings': {
      id: '/_requireAuth/orgs/$org/settings'
      path: '/settings'
      fullPath: '/orgs/$org/settings'
      preLoaderRoute: typeof RequireAuthOrgsOrgSettingsRouteImport
      parentRoute: typeof RequireAuthOrgsOrgRoute
    }
    '/_requireAuth/permissions/lexicons/': {
      id: '/_requireAuth/permissions/lexicons/'
      path: '/'
      fullPath: '/permissions/lexicons/'
      preLoaderRoute: typeof RequireAuthPermissionsLexiconsIndexRouteImport
      parentRoute: typeof RequireAuthPermissionsLexiconsRoute
    }
    '/_requireAuth/permissions/lexicons/$collection': {
      id: '/_requireAuth/permissions/lexicons/$collection'
      path: '/$collection'
      fullPath: '/permissions/lexicons/$collection'
      preLoaderRoute: typeof RequireAuthPermissionsLexiconsCollectionRouteImport
      parentRoute: typeof RequireAuthPermissionsLexiconsRoute
    }
    '/_requireAuth/permissions/people/$did': {
      id: '/_requireAuth/permissions/people/$did'
      path: '/$did'
      fullPath: '/permissions/people/$did'
      preLoaderRoute: typeof RequireAuthPermissionsPeopleDidRouteImport
      parentRoute: typeof RequireAuthPermissionsPeopleRoute
    }
    '/_requireAuth/spaces/$spaceOwner/': {
      id: '/_requireAuth/spaces/$spaceOwner/'
      path: '/spaces/$spaceOwner'
      fullPath: '/spaces/$spaceOwner/'
      preLoaderRoute: typeof RequireAuthSpacesSpaceOwnerIndexRouteImport
      parentRoute: typeof RequireAuthRoute
    }
    '/_requireAuth/spaces/type/$spaceType': {
      id: '/_requireAuth/spaces/type/$spaceType'
      path: '/spaces/type/$spaceType'
      fullPath: '/spaces/type/$spaceType'
      preLoaderRoute: typeof RequireAuthSpacesTypeSpaceTypeRouteImport
      parentRoute: typeof RequireAuthRoute
    }
    '/_requireAuth/orgs/$org/settings/': {
      id: '/_requireAuth/orgs/$org/settings/'
      path: '/'
      fullPath: '/orgs/$org/settings/'
      preLoaderRoute: typeof RequireAuthOrgsOrgSettingsIndexRouteImport
      parentRoute: typeof RequireAuthOrgsOrgSettingsRoute
    }
    '/_requireAuth/orgs/$org/settings/apps': {
      id: '/_requireAuth/orgs/$org/settings/apps'
      path: '/apps'
      fullPath: '/orgs/$org/settings/apps'
      preLoaderRoute: typeof RequireAuthOrgsOrgSettingsAppsRouteImport
      parentRoute: typeof RequireAuthOrgsOrgSettingsRoute
    }
    '/_requireAuth/orgs/$org/settings/branding': {
      id: '/_requireAuth/orgs/$org/settings/branding'
      path: '/branding'
      fullPath: '/orgs/$org/settings/branding'
      preLoaderRoute: typeof RequireAuthOrgsOrgSettingsBrandingRouteImport
      parentRoute: typeof RequireAuthOrgsOrgSettingsRoute
    }
    '/_requireAuth/orgs/$org/settings/capabilities': {
      id: '/_requireAuth/orgs/$org/settings/capabilities'
      path: '/capabilities'
      fullPath: '/orgs/$org/settings/capabilities'
      preLoaderRoute: typeof RequireAuthOrgsOrgSettingsCapabilitiesRouteImport
      parentRoute: typeof RequireAuthOrgsOrgSettingsRoute
    }
    '/_requireAuth/orgs/$org/settings/mcp': {
      id: '/_requireAuth/orgs/$org/settings/mcp'
      path: '/mcp'
      fullPath: '/orgs/$org/settings/mcp'
      preLoaderRoute: typeof RequireAuthOrgsOrgSettingsMcpRouteImport
      parentRoute: typeof RequireAuthOrgsOrgSettingsRoute
    }
    '/_requireAuth/orgs/$org/settings/members': {
      id: '/_requireAuth/orgs/$org/settings/members'
      path: '/members'
      fullPath: '/orgs/$org/settings/members'
      preLoaderRoute: typeof RequireAuthOrgsOrgSettingsMembersRouteImport
      parentRoute: typeof RequireAuthOrgsOrgSettingsRoute
    }
    '/_requireAuth/orgs/$org/settings/roles': {
      id: '/_requireAuth/orgs/$org/settings/roles'
      path: '/roles'
      fullPath: '/orgs/$org/settings/roles'
      preLoaderRoute: typeof RequireAuthOrgsOrgSettingsRolesRouteImport
      parentRoute: typeof RequireAuthOrgsOrgSettingsRoute
    }
    '/_requireAuth/orgs/$org/settings/search': {
      id: '/_requireAuth/orgs/$org/settings/search'
      path: '/search'
      fullPath: '/orgs/$org/settings/search'
      preLoaderRoute: typeof RequireAuthOrgsOrgSettingsSearchRouteImport
      parentRoute: typeof RequireAuthOrgsOrgSettingsRoute
    }
    '/_requireAuth/spaces/$spaceOwner/$spaceType/': {
      id: '/_requireAuth/spaces/$spaceOwner/$spaceType/'
      path: '/spaces/$spaceOwner/$spaceType'
      fullPath: '/spaces/$spaceOwner/$spaceType/'
      preLoaderRoute: typeof RequireAuthSpacesSpaceOwnerSpaceTypeIndexRouteImport
      parentRoute: typeof RequireAuthRoute
    }
    '/_requireAuth/orgs/$org/settings/app/$clientKey': {
      id: '/_requireAuth/orgs/$org/settings/app/$clientKey'
      path: '/app/$clientKey'
      fullPath: '/orgs/$org/settings/app/$clientKey'
      preLoaderRoute: typeof RequireAuthOrgsOrgSettingsAppClientKeyRouteImport
      parentRoute: typeof RequireAuthOrgsOrgSettingsRoute
    }
    '/_requireAuth/spaces/$spaceOwner/$spaceType/$spaceKey/': {
      id: '/_requireAuth/spaces/$spaceOwner/$spaceType/$spaceKey/'
      path: '/spaces/$spaceOwner/$spaceType/$spaceKey'
      fullPath: '/spaces/$spaceOwner/$spaceType/$spaceKey/'
      preLoaderRoute: typeof RequireAuthSpacesSpaceOwnerSpaceTypeSpaceKeyIndexRouteImport
      parentRoute: typeof RequireAuthRoute
    }
    '/_requireAuth/spaces/$spaceOwner/$spaceType/$spaceKey/$recordOwner/': {
      id: '/_requireAuth/spaces/$spaceOwner/$spaceType/$spaceKey/$recordOwner/'
      path: '/spaces/$spaceOwner/$spaceType/$spaceKey/$recordOwner'
      fullPath: '/spaces/$spaceOwner/$spaceType/$spaceKey/$recordOwner/'
      preLoaderRoute: typeof RequireAuthSpacesSpaceOwnerSpaceTypeSpaceKeyRecordOwnerIndexRouteImport
      parentRoute: typeof RequireAuthRoute
    }
    '/_requireAuth/spaces/$spaceOwner/$spaceType/$spaceKey/$recordOwner/$recordType/$recordKey': {
      id: '/_requireAuth/spaces/$spaceOwner/$spaceType/$spaceKey/$recordOwner/$recordType/$recordKey'
      path: '/spaces/$spaceOwner/$spaceType/$spaceKey/$recordOwner/$recordType/$recordKey'
      fullPath: '/spaces/$spaceOwner/$spaceType/$spaceKey/$recordOwner/$recordType/$recordKey'
      preLoaderRoute: typeof RequireAuthSpacesSpaceOwnerSpaceTypeSpaceKeyRecordOwnerRecordTypeRecordKeyRouteImport
      parentRoute: typeof RequireAuthRoute
    }
  }
}

interface RequireAuthPermissionsLexiconsRouteChildren {
  RequireAuthPermissionsLexiconsCollectionRoute: typeof RequireAuthPermissionsLexiconsCollectionRoute
  RequireAuthPermissionsLexiconsIndexRoute: typeof RequireAuthPermissionsLexiconsIndexRoute
}

const RequireAuthPermissionsLexiconsRouteChildren: RequireAuthPermissionsLexiconsRouteChildren =
  {
    RequireAuthPermissionsLexiconsCollectionRoute:
      RequireAuthPermissionsLexiconsCollectionRoute,
    RequireAuthPermissionsLexiconsIndexRoute:
      RequireAuthPermissionsLexiconsIndexRoute,
  }

const RequireAuthPermissionsLexiconsRouteWithChildren =
  RequireAuthPermissionsLexiconsRoute._addFileChildren(
    RequireAuthPermissionsLexiconsRouteChildren,
  )

interface RequireAuthPermissionsPeopleRouteChildren {
  RequireAuthPermissionsPeopleDidRoute: typeof RequireAuthPermissionsPeopleDidRoute
}

const RequireAuthPermissionsPeopleRouteChildren: RequireAuthPermissionsPeopleRouteChildren =
  {
    RequireAuthPermissionsPeopleDidRoute: RequireAuthPermissionsPeopleDidRoute,
  }

const RequireAuthPermissionsPeopleRouteWithChildren =
  RequireAuthPermissionsPeopleRoute._addFileChildren(
    RequireAuthPermissionsPeopleRouteChildren,
  )

interface RequireAuthPermissionsRouteChildren {
  RequireAuthPermissionsLexiconsRoute: typeof RequireAuthPermissionsLexiconsRouteWithChildren
  RequireAuthPermissionsPeopleRoute: typeof RequireAuthPermissionsPeopleRouteWithChildren
  RequireAuthPermissionsIndexRoute: typeof RequireAuthPermissionsIndexRoute
}

const RequireAuthPermissionsRouteChildren: RequireAuthPermissionsRouteChildren =
  {
    RequireAuthPermissionsLexiconsRoute:
      RequireAuthPermissionsLexiconsRouteWithChildren,
    RequireAuthPermissionsPeopleRoute:
      RequireAuthPermissionsPeopleRouteWithChildren,
    RequireAuthPermissionsIndexRoute: RequireAuthPermissionsIndexRoute,
  }

const RequireAuthPermissionsRouteWithChildren =
  RequireAuthPermissionsRoute._addFileChildren(
    RequireAuthPermissionsRouteChildren,
  )

interface RequireAuthOrgsOrgSettingsRouteChildren {
  RequireAuthOrgsOrgSettingsAppsRoute: typeof RequireAuthOrgsOrgSettingsAppsRoute
  RequireAuthOrgsOrgSettingsBrandingRoute: typeof RequireAuthOrgsOrgSettingsBrandingRoute
  RequireAuthOrgsOrgSettingsCapabilitiesRoute: typeof RequireAuthOrgsOrgSettingsCapabilitiesRoute
  RequireAuthOrgsOrgSettingsMcpRoute: typeof RequireAuthOrgsOrgSettingsMcpRoute
  RequireAuthOrgsOrgSettingsMembersRoute: typeof RequireAuthOrgsOrgSettingsMembersRoute
  RequireAuthOrgsOrgSettingsRolesRoute: typeof RequireAuthOrgsOrgSettingsRolesRoute
  RequireAuthOrgsOrgSettingsSearchRoute: typeof RequireAuthOrgsOrgSettingsSearchRoute
  RequireAuthOrgsOrgSettingsIndexRoute: typeof RequireAuthOrgsOrgSettingsIndexRoute
  RequireAuthOrgsOrgSettingsAppClientKeyRoute: typeof RequireAuthOrgsOrgSettingsAppClientKeyRoute
}

const RequireAuthOrgsOrgSettingsRouteChildren: RequireAuthOrgsOrgSettingsRouteChildren =
  {
    RequireAuthOrgsOrgSettingsAppsRoute: RequireAuthOrgsOrgSettingsAppsRoute,
    RequireAuthOrgsOrgSettingsBrandingRoute:
      RequireAuthOrgsOrgSettingsBrandingRoute,
    RequireAuthOrgsOrgSettingsCapabilitiesRoute:
      RequireAuthOrgsOrgSettingsCapabilitiesRoute,
    RequireAuthOrgsOrgSettingsMcpRoute: RequireAuthOrgsOrgSettingsMcpRoute,
    RequireAuthOrgsOrgSettingsMembersRoute:
      RequireAuthOrgsOrgSettingsMembersRoute,
    RequireAuthOrgsOrgSettingsRolesRoute: RequireAuthOrgsOrgSettingsRolesRoute,
    RequireAuthOrgsOrgSettingsSearchRoute:
      RequireAuthOrgsOrgSettingsSearchRoute,
    RequireAuthOrgsOrgSettingsIndexRoute: RequireAuthOrgsOrgSettingsIndexRoute,
    RequireAuthOrgsOrgSettingsAppClientKeyRoute:
      RequireAuthOrgsOrgSettingsAppClientKeyRoute,
  }

const RequireAuthOrgsOrgSettingsRouteWithChildren =
  RequireAuthOrgsOrgSettingsRoute._addFileChildren(
    RequireAuthOrgsOrgSettingsRouteChildren,
  )

interface RequireAuthOrgsOrgRouteChildren {
  RequireAuthOrgsOrgSettingsRoute: typeof RequireAuthOrgsOrgSettingsRouteWithChildren
  RequireAuthOrgsOrgIndexRoute: typeof RequireAuthOrgsOrgIndexRoute
}

const RequireAuthOrgsOrgRouteChildren: RequireAuthOrgsOrgRouteChildren = {
  RequireAuthOrgsOrgSettingsRoute: RequireAuthOrgsOrgSettingsRouteWithChildren,
  RequireAuthOrgsOrgIndexRoute: RequireAuthOrgsOrgIndexRoute,
}

const RequireAuthOrgsOrgRouteWithChildren =
  RequireAuthOrgsOrgRoute._addFileChildren(RequireAuthOrgsOrgRouteChildren)

interface RequireAuthRouteChildren {
  RequireAuthDataRoute: typeof RequireAuthDataRoute
  RequireAuthPermissionsRoute: typeof RequireAuthPermissionsRouteWithChildren
  RequireAuthSearchRoute: typeof RequireAuthSearchRoute
  RequireAuthIndexRoute: typeof RequireAuthIndexRoute
  RequireAuthOrgsOrgRoute: typeof RequireAuthOrgsOrgRouteWithChildren
  RequireAuthPearTestViewRoute: typeof RequireAuthPearTestViewRoute
  RequireAuthBlobTestIndexRoute: typeof RequireAuthBlobTestIndexRoute
  RequireAuthOrgsIndexRoute: typeof RequireAuthOrgsIndexRoute
  RequireAuthPearTestIndexRoute: typeof RequireAuthPearTestIndexRoute
  RequireAuthSpacesIndexRoute: typeof RequireAuthSpacesIndexRoute
  RequireAuthSpacesTypeSpaceTypeRoute: typeof RequireAuthSpacesTypeSpaceTypeRoute
  RequireAuthSpacesSpaceOwnerIndexRoute: typeof RequireAuthSpacesSpaceOwnerIndexRoute
  RequireAuthSpacesSpaceOwnerSpaceTypeIndexRoute: typeof RequireAuthSpacesSpaceOwnerSpaceTypeIndexRoute
  RequireAuthSpacesSpaceOwnerSpaceTypeSpaceKeyIndexRoute: typeof RequireAuthSpacesSpaceOwnerSpaceTypeSpaceKeyIndexRoute
  RequireAuthSpacesSpaceOwnerSpaceTypeSpaceKeyRecordOwnerIndexRoute: typeof RequireAuthSpacesSpaceOwnerSpaceTypeSpaceKeyRecordOwnerIndexRoute
  RequireAuthSpacesSpaceOwnerSpaceTypeSpaceKeyRecordOwnerRecordTypeRecordKeyRoute: typeof RequireAuthSpacesSpaceOwnerSpaceTypeSpaceKeyRecordOwnerRecordTypeRecordKeyRoute
}

const RequireAuthRouteChildren: RequireAuthRouteChildren = {
  RequireAuthDataRoute: RequireAuthDataRoute,
  RequireAuthPermissionsRoute: RequireAuthPermissionsRouteWithChildren,
  RequireAuthSearchRoute: RequireAuthSearchRoute,
  RequireAuthIndexRoute: RequireAuthIndexRoute,
  RequireAuthOrgsOrgRoute: RequireAuthOrgsOrgRouteWithChildren,
  RequireAuthPearTestViewRoute: RequireAuthPearTestViewRoute,
  RequireAuthBlobTestIndexRoute: RequireAuthBlobTestIndexRoute,
  RequireAuthOrgsIndexRoute: RequireAuthOrgsIndexRoute,
  RequireAuthPearTestIndexRoute: RequireAuthPearTestIndexRoute,
  RequireAuthSpacesIndexRoute: RequireAuthSpacesIndexRoute,
  RequireAuthSpacesTypeSpaceTypeRoute: RequireAuthSpacesTypeSpaceTypeRoute,
  RequireAuthSpacesSpaceOwnerIndexRoute: RequireAuthSpacesSpaceOwnerIndexRoute,
  RequireAuthSpacesSpaceOwnerSpaceTypeIndexRoute:
    RequireAuthSpacesSpaceOwnerSpaceTypeIndexRoute,
  RequireAuthSpacesSpaceOwnerSpaceTypeSpaceKeyIndexRoute:
    RequireAuthSpacesSpaceOwnerSpaceTypeSpaceKeyIndexRoute,
  RequireAuthSpacesSpaceOwnerSpaceTypeSpaceKeyRecordOwnerIndexRoute:
    RequireAuthSpacesSpaceOwnerSpaceTypeSpaceKeyRecordOwnerIndexRoute,
  RequireAuthSpacesSpaceOwnerSpaceTypeSpaceKeyRecordOwnerRecordTypeRecordKeyRoute:
    RequireAuthSpacesSpaceOwnerSpaceTypeSpaceKeyRecordOwnerRecordTypeRecordKeyRoute,
}

const RequireAuthRouteWithChildren = RequireAuthRoute._addFileChildren(
  RequireAuthRouteChildren,
)

interface LoginRouteChildren {
  LoginHabitatRoute: typeof LoginHabitatRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginHabitatRoute: LoginHabitatRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  RequireAuthRoute: RequireAuthRouteWithChildren,
  DevtoolsRoute: DevtoolsRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRouteWithChildren,
  OauthLoginRoute: OauthLoginRoute,
  OnboardRoute: OnboardRoute,
  CommunityCreateRoute: CommunityCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
