// Code generated by MockGen. DO NOT EDIT.
// Source: internal/node/controller/pds.go
//
// Generated by this command:
//
//	mockgen -source=internal/node/controller/pds.go -package mocks -destination=internal/node/controller/mocks/mock_pds.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	types "github.com/eagraf/habitat-new/core/api"
	config "github.com/eagraf/habitat-new/internal/node/config"
	gomock "go.uber.org/mock/gomock"
)

// MockPDSClientI is a mock of PDSClientI interface.
type MockPDSClientI struct {
	ctrl     *gomock.Controller
	recorder *MockPDSClientIMockRecorder
}

// MockPDSClientIMockRecorder is the mock recorder for MockPDSClientI.
type MockPDSClientIMockRecorder struct {
	mock *MockPDSClientI
}

// NewMockPDSClientI creates a new mock instance.
func NewMockPDSClientI(ctrl *gomock.Controller) *MockPDSClientI {
	mock := &MockPDSClientI{ctrl: ctrl}
	mock.recorder = &MockPDSClientIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPDSClientI) EXPECT() *MockPDSClientIMockRecorder {
	return m.recorder
}

// CreateAccount mocks base method.
func (m *MockPDSClientI) CreateAccount(nodeConfig *config.NodeConfig, email, handle, password, inviteCode string) (types.PDSCreateAccountResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", nodeConfig, email, handle, password, inviteCode)
	ret0, _ := ret[0].(types.PDSCreateAccountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockPDSClientIMockRecorder) CreateAccount(nodeConfig, email, handle, password, inviteCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockPDSClientI)(nil).CreateAccount), nodeConfig, email, handle, password, inviteCode)
}

// CreateSession mocks base method.
func (m *MockPDSClientI) CreateSession(identifier, password string) (types.PDSCreateSessionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", identifier, password)
	ret0, _ := ret[0].(types.PDSCreateSessionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockPDSClientIMockRecorder) CreateSession(identifier, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockPDSClientI)(nil).CreateSession), identifier, password)
}

// GetInviteCode mocks base method.
func (m *MockPDSClientI) GetInviteCode(nodeConfig *config.NodeConfig) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInviteCode", nodeConfig)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInviteCode indicates an expected call of GetInviteCode.
func (mr *MockPDSClientIMockRecorder) GetInviteCode(nodeConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInviteCode", reflect.TypeOf((*MockPDSClientI)(nil).GetInviteCode), nodeConfig)
}
