/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RequireAuthRouteImport } from './routes/_requireAuth'
import { Route as RequireAuthIndexRouteImport } from './routes/_requireAuth/index'

const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RequireAuthRoute = RequireAuthRouteImport.update({
  id: '/_requireAuth',
  getParentRoute: () => rootRouteImport,
} as any)
const RequireAuthIndexRoute = RequireAuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RequireAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof RequireAuthIndexRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/': typeof RequireAuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_requireAuth': typeof RequireAuthRouteWithChildren
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/_requireAuth/': typeof RequireAuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/onboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/onboard' | '/'
  id: '__root__' | '/_requireAuth' | '/login' | '/onboard' | '/_requireAuth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RequireAuthRoute: typeof RequireAuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardRoute: typeof OnboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_requireAuth': {
      id: '/_requireAuth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof RequireAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_requireAuth/': {
      id: '/_requireAuth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RequireAuthIndexRouteImport
      parentRoute: typeof RequireAuthRoute
    }
  }
}

interface RequireAuthRouteChildren {
  RequireAuthIndexRoute: typeof RequireAuthIndexRoute
}

const RequireAuthRouteChildren: RequireAuthRouteChildren = {
  RequireAuthIndexRoute: RequireAuthIndexRoute,
}

const RequireAuthRouteWithChildren = RequireAuthRoute._addFileChildren(
  RequireAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  RequireAuthRoute: RequireAuthRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardRoute: OnboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
