/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RequireAuthRouteImport } from './routes/_requireAuth'
import { Route as RequireAuthIndexRouteImport } from './routes/_requireAuth/index'
import { Route as RequireAuthV2RouteImport } from './routes/_requireAuth/v2'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RequireAuthRoute = RequireAuthRouteImport.update({
  id: '/_requireAuth',
  getParentRoute: () => rootRouteImport,
} as any)
const RequireAuthIndexRoute = RequireAuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RequireAuthRoute,
} as any)
const RequireAuthV2Route = RequireAuthV2RouteImport.update({
  id: '/v2',
  path: '/v2',
  getParentRoute: () => RequireAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/v2': typeof RequireAuthV2Route
  '/': typeof RequireAuthIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/v2': typeof RequireAuthV2Route
  '/': typeof RequireAuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_requireAuth': typeof RequireAuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_requireAuth/v2': typeof RequireAuthV2Route
  '/_requireAuth/': typeof RequireAuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/v2' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/v2' | '/'
  id:
    | '__root__'
    | '/_requireAuth'
    | '/login'
    | '/_requireAuth/v2'
    | '/_requireAuth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RequireAuthRoute: typeof RequireAuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_requireAuth': {
      id: '/_requireAuth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RequireAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_requireAuth/': {
      id: '/_requireAuth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RequireAuthIndexRouteImport
      parentRoute: typeof RequireAuthRoute
    }
    '/_requireAuth/v2': {
      id: '/_requireAuth/v2'
      path: '/v2'
      fullPath: '/v2'
      preLoaderRoute: typeof RequireAuthV2RouteImport
      parentRoute: typeof RequireAuthRoute
    }
  }
}

interface RequireAuthRouteChildren {
  RequireAuthV2Route: typeof RequireAuthV2Route
  RequireAuthIndexRoute: typeof RequireAuthIndexRoute
}

const RequireAuthRouteChildren: RequireAuthRouteChildren = {
  RequireAuthV2Route: RequireAuthV2Route,
  RequireAuthIndexRoute: RequireAuthIndexRoute,
}

const RequireAuthRouteWithChildren = RequireAuthRoute._addFileChildren(
  RequireAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  RequireAuthRoute: RequireAuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
