/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MemberRouteImport } from './routes/_member'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DotwellKnownDidDotjsonRouteImport } from './routes/[.]well-known.did[.]json'
import { Route as MemberIndexRouteImport } from './routes/_member/index'
import { Route as MemberOrgsRouteImport } from './routes/_member/orgs'
import { Route as ApiDownloadRouteImport } from './routes/api.download'
import { Route as ApiLiveRouteImport } from './routes/api.live'
import { Route as ApiUploadRouteImport } from './routes/api.upload'
import { Route as OauthCallbackRouteImport } from './routes/oauth.callback'
import { Route as OauthClientMetadataDotjsonRouteImport } from './routes/oauth.client-metadata[.]json'
import { Route as XrpcNsidRouteImport } from './routes/xrpc.$nsid'

const MemberRoute = MemberRouteImport.update({
  id: '/_member',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownDidDotjsonRoute = DotwellKnownDidDotjsonRouteImport.update({
  id: '/.well-known/did.json',
  path: '/.well-known/did.json',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberIndexRoute = MemberIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MemberRoute,
} as any)
const MemberOrgsRoute = MemberOrgsRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => MemberRoute,
} as any)
const ApiDownloadRoute = ApiDownloadRouteImport.update({
  id: '/api/download',
  path: '/api/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveRoute = ApiLiveRouteImport.update({
  id: '/api/live',
  path: '/api/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthClientMetadataDotjsonRoute =
  OauthClientMetadataDotjsonRouteImport.update({
    id: '/oauth/client-metadata.json',
    path: '/oauth/client-metadata.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const XrpcNsidRoute = XrpcNsidRouteImport.update({
  id: '/xrpc/$nsid',
  path: '/xrpc/$nsid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MemberIndexRoute
  '/login': typeof LoginRoute
  '/.well-known/did.json': typeof DotwellKnownDidDotjsonRoute
  '/orgs': typeof MemberOrgsRoute
  '/api/download': typeof ApiDownloadRoute
  '/api/live': typeof ApiLiveRoute
  '/api/upload': typeof ApiUploadRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/client-metadata.json': typeof OauthClientMetadataDotjsonRoute
  '/xrpc/$nsid': typeof XrpcNsidRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/.well-known/did.json': typeof DotwellKnownDidDotjsonRoute
  '/orgs': typeof MemberOrgsRoute
  '/api/download': typeof ApiDownloadRoute
  '/api/live': typeof ApiLiveRoute
  '/api/upload': typeof ApiUploadRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/client-metadata.json': typeof OauthClientMetadataDotjsonRoute
  '/xrpc/$nsid': typeof XrpcNsidRoute
  '/': typeof MemberIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_member': typeof MemberRouteWithChildren
  '/login': typeof LoginRoute
  '/.well-known/did.json': typeof DotwellKnownDidDotjsonRoute
  '/_member/orgs': typeof MemberOrgsRoute
  '/api/download': typeof ApiDownloadRoute
  '/api/live': typeof ApiLiveRoute
  '/api/upload': typeof ApiUploadRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/client-metadata.json': typeof OauthClientMetadataDotjsonRoute
  '/xrpc/$nsid': typeof XrpcNsidRoute
  '/_member/': typeof MemberIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/.well-known/did.json'
    | '/orgs'
    | '/api/download'
    | '/api/live'
    | '/api/upload'
    | '/oauth/callback'
    | '/oauth/client-metadata.json'
    | '/xrpc/$nsid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/.well-known/did.json'
    | '/orgs'
    | '/api/download'
    | '/api/live'
    | '/api/upload'
    | '/oauth/callback'
    | '/oauth/client-metadata.json'
    | '/xrpc/$nsid'
    | '/'
  id:
    | '__root__'
    | '/_member'
    | '/login'
    | '/.well-known/did.json'
    | '/_member/orgs'
    | '/api/download'
    | '/api/live'
    | '/api/upload'
    | '/oauth/callback'
    | '/oauth/client-metadata.json'
    | '/xrpc/$nsid'
    | '/_member/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MemberRoute: typeof MemberRouteWithChildren
  LoginRoute: typeof LoginRoute
  DotwellKnownDidDotjsonRoute: typeof DotwellKnownDidDotjsonRoute
  ApiDownloadRoute: typeof ApiDownloadRoute
  ApiLiveRoute: typeof ApiLiveRoute
  ApiUploadRoute: typeof ApiUploadRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  OauthClientMetadataDotjsonRoute: typeof OauthClientMetadataDotjsonRoute
  XrpcNsidRoute: typeof XrpcNsidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_member': {
      id: '/_member'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/did.json': {
      id: '/.well-known/did.json'
      path: '/.well-known/did.json'
      fullPath: '/.well-known/did.json'
      preLoaderRoute: typeof DotwellKnownDidDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_member/': {
      id: '/_member/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MemberIndexRouteImport
      parentRoute: typeof MemberRoute
    }
    '/_member/orgs': {
      id: '/_member/orgs'
      path: '/orgs'
      fullPath: '/orgs'
      preLoaderRoute: typeof MemberOrgsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/api/download': {
      id: '/api/download'
      path: '/api/download'
      fullPath: '/api/download'
      preLoaderRoute: typeof ApiDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live': {
      id: '/api/live'
      path: '/api/live'
      fullPath: '/api/live'
      preLoaderRoute: typeof ApiLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/client-metadata.json': {
      id: '/oauth/client-metadata.json'
      path: '/oauth/client-metadata.json'
      fullPath: '/oauth/client-metadata.json'
      preLoaderRoute: typeof OauthClientMetadataDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xrpc/$nsid': {
      id: '/xrpc/$nsid'
      path: '/xrpc/$nsid'
      fullPath: '/xrpc/$nsid'
      preLoaderRoute: typeof XrpcNsidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MemberRouteChildren {
  MemberOrgsRoute: typeof MemberOrgsRoute
  MemberIndexRoute: typeof MemberIndexRoute
}

const MemberRouteChildren: MemberRouteChildren = {
  MemberOrgsRoute: MemberOrgsRoute,
  MemberIndexRoute: MemberIndexRoute,
}

const MemberRouteWithChildren =
  MemberRoute._addFileChildren(MemberRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MemberRoute: MemberRouteWithChildren,
  LoginRoute: LoginRoute,
  DotwellKnownDidDotjsonRoute: DotwellKnownDidDotjsonRoute,
  ApiDownloadRoute: ApiDownloadRoute,
  ApiLiveRoute: ApiLiveRoute,
  ApiUploadRoute: ApiUploadRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  OauthClientMetadataDotjsonRoute: OauthClientMetadataDotjsonRoute,
  XrpcNsidRoute: XrpcNsidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
