// Package schema embeds the SQL migrations that create the tables for the GORM
// models of habitat's stores, one directory per dialect.
//
// The migrations are generated by Atlas from the stores' models; see
// cmd/pear/README.md. Do not edit them by hand without rehashing (moon run
// pear:migration-hash).
package schema

import (
	"embed"
	"fmt"
	"io/fs"

	"github.com/habitat-network/habitat/internal/db"
)

//go:embed postgres/*.sql sqlite/*.sql
var migrations embed.FS

// Migrations returns the SQL migrations for dialect, for [db.Migrate].
func Migrations(dialect db.Dialect) (fs.FS, error) {
	switch dialect {
	case db.Postgres:
		return fs.Sub(migrations, "postgres")
	case db.Sqlite:
		return fs.Sub(migrations, "sqlite")
	default:
		return nil, fmt.Errorf("unsupported dialect: %q", dialect)
	}
}
